INSERT INTO `tweets` (`film_id`, `tweet`, `status`, `truth_rule`, `truth_naive`) VALUES
(4,"HASHTAG gateway cinema araneta cubao URL",2,0,0),
(4,"siis mampir yuuk gt gt URL HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(4,"lebih nendang nonton HASHTAG di 4dx USERNAME diskon rp 55 000 dgn kode bms4dxcgv hanya di bookmyshow s amp k URL",2,0,0),
(4,"biar kekinian jg HASHTAG HASHTAG xxl scp samarinda URL",2,0,0),
(4,"nak tngk JUDULFILM",2,0,0),
(4,"bila kawan ajak tengok JUDULFILM kat kl and kau masih kat pahang jahatnyaaa hmmm nak ikutttt",2,0,0),
(4,"USERNAME jom tengok JUDULFILM",2,0,0),
(4,"michelle pengen boil sepot pelali omg HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(4,"HASHTAG kendrick lamar dna HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(4,"JUDULFILM watching fast amp furious 8 at cinemaximum akasya avm URL URL",2,0,0),
(4,"HASHTAG kifupi wameshindwa kutengeneza filamu nzuri itakayomshawishi mtu kuketi na kuitizama acheni bhana fast and furiou URL",2,0,0),
(4,"kan bego ya mau update path JUDULFILM terus gaada jadinya ga update tapi ternyata namanya the fate and furious 8",2,0,0),
(4,"JUDULFILM ke 2 kalinya URL URL",2,0,0),
(4,"team pacet ngoro peterongan HASHTAG HASHTAG URL",2,0,0),
(4,"keturutan juga JUDULFILM na HASHTAG",2,0,0),
(4,"lhoh tormund HASHTAG",2,0,0),
(4,"actually fast and furious yang first punya belum pernah tengok abeh ni JUDULFILM dah keluar",2,0,0),
(4,"gaston udah ga sama le fou lagi disini tapi sama baby face jason statam HASHTAG HASHTAG",2,0,0),
(4,"akhirnya bisa juga nonton JUDULFILM basura xxi URL",2,0,0),
(4,"HASHTAG at USERNAME in balikes r bandirma URL URL",2,0,0),
(4,"kayaknya dr semua tiket yg tercetak tulisan judulnya JUDULFILM semua padahal judul aslinya the URL",2,0,0),
(4,"beauty and the beast tak tgk power rangers tak tgk JUDULFILM tak tgk just semua tak tgk HASHTAG",2,0,0),
(4,"HASHTAG kucek mata dl HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(4,"penonton indonesia nyumbang 119 miliar buat rekor yg dicetak ff8 gile URL",2,0,0),
(4,"nak tengok JUDULFILM lagii",2,0,0),
(4,"ada kek yg ngajakin nonton JUDULFILM ogah bgt kl nonton sendiri",2,0,0),
(4,"USERNAME ni sbb lepas tengok JUDULFILM",2,0,0),
(4,"21 4 HASHTAG HASHTAG narasimha telugu 2nd wk HASHTAG srinarasimha 2nd wk HASHTAG sowjanya 2nd wk HASHTAG sukanya",2,0,0),
(4,"who cares dh nk masuk kali ke 3 tgk movie JUDULFILM",2,0,0),
(4,"ternyata kenji ponakan saya jadi artis di film HASHTAG berperan sebagai brian carlos URL",1,0,0),
(4,"again HASHTAG 21 cineplex xxi supermall pakuwon indah URL",1,0,0),
(4,"nasib emak2 gak bakalan bz nnton JUDULFILM krn ada larangan bawa anak2 penuh cinta",1,0,0),
(4,"kena tengok JUDULFILM sebab assigment sepanjang berada dalam wayang macam satu penderitaan panjang",1,0,0),
(4,"gajahmada cinema tegal jumat 21 april 2017 cinema 4 JUDULFILM dewasa 12 30 15 10 17 50 20 30",1,0,0),
(4,"vin diesel amp dwayne johnson akan kembali tampil di fast amp furious 9 dan 10 HASHTAG HASHTAG URL independent",1,0,0),
(45,"wuh jom bissan mom JUDULFILM",2,0,0),
(45,"USERNAME marilah kita JUDULFILM from di babikan oleh pemanggil2 nokhorom",2,0,0),
(45,"JUDULFILM mbo cinemas in subang jaya selangor URL URL URL",2,0,0),
(45,"JUDULFILM at USERNAME in petaling jaya selangor",2,0,0),
(45,"JUDULFILM at USERNAME in petaling jaya selangor URL",2,0,0),
(45,"siapa dah tengok JUDULFILM",2,0,0),
(45,"nak tengok JUDULFILM HASHTAG",2,0,0),
(45,"nak tengok JUDULFILM plsssss",2,0,0),
(45,"JUDULFILM utah URL",2,0,0),
(45,"JUDULFILM saki senpai URL",2,0,0),
(45,"nasus gt renekton JUDULFILM",2,0,0),
(45,"JUDULFILM dah keluar n here i am still tak tengok fast8",2,0,0),
(45,"ahjskddk broom broom JUDULFILM me car URL",2,0,0),
(45,"USERNAME bila JUDULFILM keluar",2,0,0),
(45,"setakat jam 2 11 a m tiada sebarang spoiler JUDULFILM",2,0,0),
(45,"JUDULFILM mbo cinemas in subang jaya selangor URL",2,0,0),
(45,"jadual mcm nak mtk cuti mcm i shud JUDULFILM from this hell nak aku keje 5 hr straight nuts HASHTAG",2,0,0),
(45,"HASHTAG JUDULFILM blu ray dvd digital hd JUDULFILM blu ray dvd digital hd daniel kaluuya URL HASHTAG HASHTAG",2,0,0),
(45,"mau nonton JUDULFILM dari sebelum keluar di xxi sampe udah mau kelar di xxi belom zempet zempet zedih",2,0,0),
(45,"stopsbd JUDULFILM URL",2,0,0),
(45,"nak tgk JUDULFILM nak tgk JUDULFILM",2,0,0),
(45,"JUDULFILM HASHTAG URL",2,0,0),
(45,"USERNAME USERNAME USERNAME USERNAME samakale aniesor mendikbud belum klar udah JUDULFILM",2,0,0),
(45,"JUDULFILM at USERNAME in petaling jaya selangor w USERNAME USERNAME URL",2,0,0),
(45,"JUDULFILM at USERNAME in petaling jaya selangor URL URL",2,0,0),
(45,"USERNAME kemarin kan ada filmnya JUDULFILM",2,0,0),
(45,"JUDULFILM golden screen cinemas gsc USERNAME in petaling jaya selangor URL URL",2,0,0),
(45,"kudu banget yak kita ng eoong cuma no no cuma untuk mantengin JUDULFILM URL URL",2,0,0),
(45,"USERNAME jom tengok JUDULFILM",2,0,0),
(45,"nak tgk JUDULFILM",2,0,0),
(45,"mau tengok movie JUDULFILM",2,0,0),
(45,"JUDULFILM at USERNAME in petaling jaya selangor URL",2,0,0),
(45,"JUDULFILM ya feeling lil bihh",2,0,0),
(45,"33 jyj JUDULFILM 34 jyj back seat 35 jyj found you 36 jyj the boy s letter 37 jyj fallen leaves 38 jyj nine",2,0,0),
(45,"mypov URL HASHTAG HASHTAG URL",2,0,0),
(45,"iconic mm URL",2,0,0),
(45,"tkde lg ke yg tgk cte JUDULFILM",2,0,0),
(45,"nak tengoj thor ngan JUDULFILM sahajaa",2,0,0),
(45,"USERNAME abg dh tgk movie JUDULFILM klau dh nnt tlg review ya",2,0,0),
(45,"bilal asif ki ziada taaref kar di thi such an ugly shot to JUDULFILM",2,0,0),
(45,"nak tengok JUDULFILM",2,0,0),
(45,"mv jyj JUDULFILM URL",2,0,0),
(45,"cerita JUDULFILM best dak",1,0,0),
(45,"dalam hall 9 layan JUDULFILM",1,0,0),
(45,"kesian tengok bila ada kawan sendiri kena cubit peha kanan peha kiri pon terasa so please JUDULFILM from her life she deserve better",1,0,0),
(45,"i have to taubat now JUDULFILM dosa JUDULFILM buka pintu fly dosa flyy hahahahahaha kelakar URL",1,0,0),
(45,"JUDULFILM of your comfort zone la khaleeda tak kemana kalau takut",1,0,0),
(45,"untuk mengorbankan diri then JUDULFILM nak",1,0,0),
(45,"USERNAME dah tgk online smlm mesia lembap giler kuar kt wayang mcm JUDULFILM ngn the silent voice ngadap fyp la cani ermmm ermmm",1,0,0),
(45,"please lah aku taknak nampak benda yg tak sepatutnya kat tl aku so please JUDULFILM thanks",1,0,0),
(45,"lagu u2 stuck in a moment HASHTAG t JUDULFILM of bercerita tentang michael hutchence vokalis inxs yg bunuh diri pd thn 1997 HASHTAG",1,0,0),
(45,"movie JUDULFILM ni memang baru keluar dekat wayang malaysia ke apesal aku rasa aku dah tengok online sebulan lepas dekat 123movies hd siap",1,0,0),
(45,"wey wong ckp kt aku JUDULFILM",1,0,0),
(45,"moga jalan yang dipilih ni diredhai allah risiko masih ada but faliq need to JUDULFILM from his comfort zone",1,0,0),
(123,"kemarin USERNAME USERNAME URL",2,0,0),
(123,"HASHTAG ada yang punya ebook JUDULFILM aku mau minta bole gak",2,0,0),
(123,"nonton mulu kerjaannya JUDULFILM at USERNAME URL",2,0,0),
(123,"yaelaa JUDULFILM at USERNAME URL",2,0,0),
(123,"terus berkarya pak URL",2,0,0),
(123,"telat ye JUDULFILM with stefany at cinema xxi URL",2,0,0),
(123,"beli tiket ghost in the shell nontonnya JUDULFILM HASHTAG HASHTAG HASHTAG",2,0,0),
(123,"USERNAME USERNAME yeu JUDULFILM",2,0,0),
(123,"jjs makassar meet up kumpul di bioskop sblm jam 4 yg mau ikut nobar JUDULFILM tapi bisa kumpul di mcd juga abis nobar",2,0,0),
(123,"ajakin nonton JUDULFILM a 3 nonton the guys waee v URL",2,0,0),
(123,"takutnya dikalahin sm penasaran JUDULFILM with faustina and mama at USERNAME URL",2,0,0),
(123,"HASHTAG kamis HASHTAG JUDULFILM 12 15 14 00 15 45 17 30 19 15 21 00",2,0,0),
(123,"belon nonton kong JUDULFILM ff8 solusi cari nakajab nya plaakk",2,0,0),
(123,"jika ada pasien yg datang padaku dan tak punya uang aku ingin sekali bilang tak usah bayar leorio",2,0,0),
(123,"USERNAME kartini blm ada JUDULFILM guaa",2,0,0),
(123,"21 4 rajawali studio 2 JUDULFILM r 11 00 14 45 htm rp 25 000",2,0,0),
(123,"JUDULFILM URL HASHTAG HASHTAG HASHTAG",2,0,0),
(123,"apapun bisa didapatkan dengan uang leorio",2,0,0),
(123,"USERNAME nonton kartini apa JUDULFILM kang hehe",2,0,0),
(123,"jum at 21 april 2017 USERNAME std 2 JUDULFILM r 12 45 16 50 URL",2,0,0),
(123,"jum at 21 april 2017 USERNAME fast amp furious 8 JUDULFILM the guys kartini stip dan pensil",2,0,0),
(123,"USERNAME pemain JUDULFILM URL",2,0,0),
(123,"USERNAME abis itu JUDULFILM yaaa",2,0,0),
(123,"USERNAME halu JUDULFILM oony",2,0,0),
(123,"USERNAME JUDULFILM HASHTAG",2,0,0),
(123,"USERNAME ak kangen burger king kangen JUDULFILM kangen dear nathan kangen mba asih juga",2,0,0),
(123,"JUDULFILM URL HASHTAG HASHTAG",2,0,0),
(123,"pengen nonton JUDULFILM",2,0,0),
(123,"dimana pun kita berada kita akan selalu menjadi teman selamanya gon",2,0,0),
(123,"USERNAME USERNAME USERNAME USERNAME USERNAME ga ah lu kan rasa JUDULFILM",2,0,0),
(123,"kita datang bersama sama maka kita harus keluar bersama sama juga gon",2,0,0),
(123,"USERNAME minat dm yaaa trilogi JUDULFILM ada peter hendrick sama maddah",2,0,0),
(123,"bahh ini tetangga malem jumat nonton JUDULFILM pake speaker ntapss",2,0,0),
(123,"dari dear nanthan JUDULFILM sampe fast furious keluar gak ada yang ajakin gue nonton HASHTAG",2,0,0),
(123,"8 fakta mengerikan film JUDULFILM film horor terbaru yang diangkat dari kisah nyata URL",1,0,0),
(123,"USERNAME liat ini gt reaksi orang korea menonton film indonesia film horror JUDULFILM URL via USERNAME",1,0,0),
(123,"selamat hari kartini URL",1,0,0),
(123,"yg ngebet banget dari tadi minta nonton ini kaya berani ajah kmu de JUDULFILM with melly at USERNAME URL",1,0,0),
(123,"pengen nonton JUDULFILM tapi ga berani URL",1,0,0),
(123,"rekor amp pendapatan fantastis JUDULFILM berkat kursi berkafan URL URL",1,0,0),
(123,"USERNAME maksud luh mungkin kartini belom ada trus luh nonton JUDULFILM gitu kali yee belibet amat dah kalimat luh",1,0,0),
(46,"hai masih edisi JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(46,"lapas kerobokan gelar drama musikal hari JUDULFILM URL",2,0,0),
(46,"JUDULFILM HASHTAG HASHTAG HASHTAG URL",2,0,0),
(46,"hari JUDULFILM hotel aston berkunjung ke makassar terkini URL",2,0,0),
(46,"USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME heh lagi jd ibu JUDULFILM haru kalem dulu HASHTAG",2,0,0),
(46,"hari JUDULFILM hotel aston berkunjung ke makassar terkini URL URL",2,0,0),
(46,"HASHTAG hari JUDULFILM hotel aston berkunjung ke makassar terkini URL URL",2,0,0),
(46,"hari JUDULFILM hotel aston berkunjung ke makassar terkini URL URL URL",2,0,0),
(46,"HASHTAG HASHTAG hari JUDULFILM hotel aston berkunjung ke makassar terkini URL URL",2,0,0),
(46,"HASHTAG HASHTAG HASHTAG hari JUDULFILM hotel aston berkunjung ke makassar terkini URL URL",2,0,0),
(46,"terimakasih ra JUDULFILM",2,0,0),
(46,"happy JUDULFILM day s semoga aja ada link download nya yaa canda doank wkwkwk URL",2,0,0),
(46,"katanya ini hari ibu kita JUDULFILM dan saya cuma berharap semoga saatnya nanti akan ada hari dimana URL",2,0,0),
(46,"JUDULFILM gemaaasshh wisma mandiri 2 kebon sirih URL",2,0,0),
(46,"kenyal silaturahmi JUDULFILM ibf chapter padang sumatera barat URL",2,0,0),
(46,"selamat hari JUDULFILM dan selamat ulang tahun kek pic URL",1,0,0),
(46,"selamat hari JUDULFILM semoga perempuan indonesia semakin maju lagi tahun ini dan tahun berikutnya HASHTAG",1,0,0),
(46,"selamat hari JUDULFILM buat jagoan nya aku di jkt48 yaa USERNAME kamu kuat dan aku tau kamu pasti selalu kuat URL",1,0,0),
(46,"keceriaan kita hari ini dalam rangka memperingati hari JUDULFILM cantik cantik URL",1,0,0),
(46,"URL tidak hanya milik rembang tapi milik nasional bahkan dunia HASHTAG HASHTAG",1,0,0),
(46,"selamat hari JUDULFILM teruntuk perempuan indonesia taman sari USERNAME 21 april URL",1,0,0),
(46,"URL HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG bokep barat cantik hari JUDULFILM bea cukai beri motivasi seimba",1,0,0),
(46,"selamat hari JUDULFILM teruslah bermimpi teruslah bermimpi bermimpilah selama engkau masih dapat bermimpi r a URL",1,0,0),
(46,"panggung gerakan dalam rangka peringatan hari JUDULFILM with imawati cabang umy di depan monumen serangan 11 maret URL",1,0,0),
(46,"selamat hari JUDULFILM URL HASHTAG HASHTAG URL",1,0,0),
(46,"real candid JUDULFILM masa kini URL",1,0,0),
(46,"selamat hari JUDULFILM selamat hari wanita2 tangguh selamat hari dimana kedudukan wanita setara dengan pria URL",1,0,0),
(46,"polwan di bali rayakan hari JUDULFILM dengan bagi bagi bunga detikcom URL HASHTAG URL",1,0,0),
(46,"ra JUDULFILM tidak menyakiti diri dan semen kaki dalam berjuang HASHTAG HASHTAG",1,0,0),
(46,"USERNAME gelap tersingkir terang terarsir semoga cahaya JUDULFILM abadi di hati sepanjang masa tak hanya saat 21 april saja HASHTAG",1,0,0),
(46,"cek gt polwan di bali rayakan hari JUDULFILM dengan bagi bagi bunga URL",1,0,0),
(55,"demi JUDULFILM with anissa at bioskop raya teather URL",2,0,0),
(55,"JUDULFILM 2017 URL URL URL",2,0,0),
(55,"nonton JUDULFILM di bioskop hai hai assalamualaikum nama saya elis dan saya sudah URL HASHTAG",2,0,0),
(55,"trs yg JUDULFILM gmn skr URL URL",2,0,0),
(55,"HASHTAG from kfmmsurabaya with URL JUDULFILM bakalan di URL URL",2,0,0),
(55,"HASHTAG yuuk di mega bekasi HASHTAG putarfilm with USERNAME nikah itu sakral URL URL",2,0,0),
(55,"behind the scene JUDULFILM video fullnya bisa ditonton di youtube channel fmm daqu movie yuk nonton URL URL",2,0,0),
(55,"nonton JUDULFILM dulu HASHTAG mall jogja",2,0,0),
(55,"HASHTAG USERNAME with USERNAME JUDULFILM tinggal tersisa 3 layar blok m URL URL",2,0,0),
(55,"JUDULFILM tinggal tersisa 3 layar blok m square jam 14 45 mega bekasi jam 14 45 cgv jwalk jogja URL URL",2,0,0),
(55,"USERNAME USERNAME uni nonton yg JUDULFILM aja",2,0,0),
(55,"mau nonton JUDULFILM tapi sama siapa yaaa",2,0,0),
(55,"51 JUDULFILM 2017 1 5 5 URL",2,0,0),
(55,"JUDULFILM tapi kejebak hujan",2,0,0),
(55,"JUDULFILM banget at USERNAME URL",2,0,0),
(55,"jadwal tayang JUDULFILM hari ini silahkan cek jadwalnya pilih jam tayangnya ajak temen dan saudara buat non URL",2,0,0),
(55,"JUDULFILM joox mini konser JUDULFILM HASHTAG d mall kota kasablanka URL",2,0,0),
(55,"data perolehan HASHTAG s d 16 4 HASHTAG 240 559 HASHTAG 604 HASHTAG 5 434 URL URL",2,0,0),
(55,"data perolehan HASHTAG s d 16 4 HASHTAG 240 559 HASHTAG 604 HASHTAG 5 434 HASHTAG 7 692 HASHTAG URL URL",2,0,0),
(55,"trailer JUDULFILM 13 april di bioskop URL",2,0,0),
(55,"HASHTAG kesampaian juga nithalolinga anthy ngatmari HASHTAG URL",2,0,0),
(55,"udah maen JUDULFILM HASHTAG HASHTAG HASHTAG",2,0,0),
(55,"catatan saya untuk HASHTAG dari USERNAME USERNAME dan menampilkan USERNAME masih tayang URL",2,0,0),
(55,"JUDULFILM mari dikejarrrrr HASHTAG HASHTAG HASHTAG URL",2,0,0),
(55,"JUDULFILM mari dikejarrrrrr with at USERNAME pic URL URL",2,0,0),
(55,"data penonton dari USERNAME HASHTAG 240 559 HASHTAG 604 HASHTAG 5 434 dan HASHTAG 2 369 486",2,0,0),
(55,"JUDULFILM yuk",2,0,0),
(55,"aww sanasini buka kartu ae babyboss apa dah JUDULFILM kwkkww apa danur wkwkw URL URL",2,0,0),
(55,"pen nonton HASHTAG URL",2,0,0),
(55,"JUDULFILM stip dan pensil kkk",2,0,0),
(55,"pengen nonton trailer JUDULFILM 13 april di bioskop URL lewat USERNAME",2,0,0),
(55,"USERNAME gimana hasil penontonya HASHTAG om mencapai targetkah",2,0,0),
(55,"HASHTAG ayoooo yg blm nonton JUDULFILM nya langsung aja merapat ke URL",2,0,0),
(55,"HASHTAG HASHTAG ayoooo yg blm nonton JUDULFILM nya langsung aja merapat ke URL",2,0,0),
(55,"te el hari ini judulnya JUDULFILM kabeh kenapa bogor cuma di puter di ccm doang sih HASHTAG",2,0,0),
(55,"jai jai bajrang bali JUDULFILM",2,0,0),
(55,"review USERNAME JUDULFILM URL HASHTAG URL",2,0,0),
(55,"USERNAME JUDULFILM HASHTAG yuk ikutan USERNAME USERNAME USERNAME USERNAME USERNAME",2,0,0),
(55,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAGHASHTAG HASHTAG HASHTAG",2,0,0),
(55,"dari pada ngejar kamu mending HASHTAG aja at USERNAME URL HASHTAG",2,0,0),
(55,"i liked a USERNAME video URL JUDULFILM tayang hari ini HASHTAG",2,0,0),
(55,"kasian sih film JUDULFILM rilis pas para film film besar rilis juga untung masih ada satu bioskop di sini yg nayangin",1,0,0),
(55,"serius nanya film JUDULFILM itu bercerita tentang mui yah",1,0,0),
(55,"seberapa pantas JUDULFILM URL URL",1,0,0),
(55,"seberapa pantas JUDULFILM URL HASHTAG URL",1,0,0),
(55,"regrann from USERNAME bismilah perjuangan belum berakhir JUDULFILM sudah URL",1,0,0),
(55,"yeay full seat di studio 3 yang belum nonton JUDULFILM karya film maker muslim yuk di bioskop pic URL",1,0,0),
(55,"sementara itu JUDULFILM nambah 1 jadwal pertunjukan di blok m square jadi total ada 6 jadwal pertunjukan",1,0,0),
(2,"menyesal tgk JUDULFILM tgh2 mlm ni myy head is throbbing",2,0,0),
(2,"di pilkada ini ga ada neh yg jadi JUDULFILM",2,0,0),
(2,"yah diajak nonton JUDULFILM ternyata udah punya bajakannya di laptop",2,0,0),
(2,"thank god masih sempat nonton JUDULFILM yang tinggal tayang 1 pertunjukan di 1 bioskop performance nya jessica chastain flawless",2,0,0),
(2,"buset JUDULFILM tinggal satu kali jam tayang",2,0,0),
(2,"JUDULFILM movie review bahasa indonesia URL melalui USERNAME",2,0,0),
(98,"HASHTAG english3d HASHTAG malayalam HASHTAG tamil URL",2,0,0),
(98,"HASHTAG layan animasi sat",2,0,0),
(98,"day JUDULFILM w ima alfathar dzeko wiranata amp arjuna van persie sastranegara at USERNAME URL",2,0,0),
(98,"bilunyuh emeeezh JUDULFILM URL",2,0,0),
(98,"efek nggak ada gawean JUDULFILM URL",2,0,0),
(98,"sebelum ke panggung baca dulu ulasan ni agar tak menyesal URL via USERNAME",2,0,0),
(98,"nak tengok JUDULFILM hehehe comel betullah smurfs ni",2,0,0),
(119,"lock buat editing bts HASHTAG amp pensil tayang sabtu di trans w oke luqman amp 3 others at md entertainment pic URL",2,0,0),
(119,"HASHTAG amp pensil with lutfiahkarenina dian and aulia at USERNAME URL",2,0,0),
(119,"HASHTAG dan HASHTAG amp pensil menunggu giliran setelah makan",2,0,0),
(119,"jones mah nontonnya sendiri aja HASHTAG amp pinsil HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(119,"nonton dlu kaka HASHTAG amp pensil URL",2,0,0),
(3,"terniat nonton ini sendiri JUDULFILM at USERNAME URL",2,0,0),
(3,"lanjut JUDULFILM at kaputren ms URL",2,0,0),
(3,"tak rasa nktgk sgt ff8 tp teringin nk tgk JUDULFILM lg",2,0,0),
(3,"sudah terlebih dahulu y gaes JUDULFILM with kemala and rosalinda ruswandi URL",2,0,0),
(3,"JUDULFILM movie bykon oki HASHTAG",2,0,0),
(3,"JUDULFILM udah ada bluray nyah ngahaha HASHTAG",2,0,0),
(3,"yuhuu JUDULFILM URL",2,0,0),
(3,"finally yg dinanti2 thx moo JUDULFILM with dwikecil URL",2,0,0),
(3,"JUDULFILM imax novo cinema in qatar w USERNAME URL URL URL",2,0,0),
(3,"at HASHTAG with elghali USERNAME allah yastr men elez3aaaj",2,0,0),
(3,"pengen nonton JUDULFILM jugak URL HASHTAG",2,0,0),
(3,"nemenin ajalah JUDULFILM URL",2,0,0),
(3,"JUDULFILM golden screen cinemas gsc USERNAME in subang jaya",2,0,0),
(3,"ngebujuk meren ah JUDULFILM with azrieldaru URL",2,0,0),
(3,"JUDULFILM ni taknak pulak dia keluar kat facebook",2,0,0),
(3,"nonton diriku sendiri JUDULFILM with ramadhani at USERNAME URL",2,0,0),
(3,"menit ke 40 si anak bayik bobok padahal tadinya ngekek2 nonton JUDULFILM w fajar at suite room 385 URL",2,0,0),
(3,"telegraaf JUDULFILM URL",2,0,0),
(3,"we hate each other JUDULFILM sedang tayang di bioskop indonesia HASHTAG URL",2,0,0),
(3,"sambung lagi JUDULFILM",2,0,0),
(3,"JUDULFILM mbo cinemas in subang jaya selangor URL URL",2,0,0),
(3,"JUDULFILM HASHTAG mbo cinemas in subang jaya selangor",2,0,0),
(3,"keturutan JUDULFILM at USERNAME URL URL",2,0,0),
(3,"ala takde sape nak teman tgk JUDULFILM",2,0,0),
(3,"sebelum berangkat JUDULFILM with ridho valent URL",2,0,0),
(3,"siapa yang sudah nonton HASHTAG di cinemaxx masih punya tiketnya ikutan kuisnya di facebook dan instagram yuk URL",2,0,0),
(3,"yain aja JUDULFILM at rumahlah URL",2,0,0),
(3,"USERNAME awk nak tgk JUDULFILM tak kat cinema",2,0,0),
(3,"watching JUDULFILM at pt jalantol lingkarluar jakarta pt jlj jorr head office URL",2,0,0),
(3,"lucu kayanya nih JUDULFILM with elsa azriel and azka at USERNAME URL",1,0,0),
(3,"mblo amat mblo JUDULFILM at perumnas teluk URL",1,0,0),
(3,"yah smurf nya dah habis watching JUDULFILM at xxi cinema ciputa world URL",1,0,0),
(3,"kehadiran seorang bayi biasanya disambut gembira oleh keluarga namun apa jadinya jika seorang bayi justru menjad URL",1,0,0),
(3,"USERNAME JUDULFILM studio 3 plaza bogor 2 sound mendem br jln 15 mnt distop info perbaikan 5 mnt ini udah 30 mnt gk kelar2",1,0,0),
(3,"terniat nonton ini sendiri JUDULFILM at USERNAME URL URL",2,0,0),
(3,"lanjut JUDULFILM at kaputren ms URL URL",2,0,0),
(3,"tak rasa nktgk sgt ff8 tp teringin nk tgk JUDULFILM lg HASHTAG",2,0,0),
(3,"sudah terlebih dahulu y gaes JUDULFILM with kemala and rosalinda ruswandi URL URL",2,0,0),
(3,"JUDULFILM movie bykon oki",2,0,0),
(3,"JUDULFILM udah ada bluray nyah ngahaha",2,0,0),
(3,"JUDULFILM imax novo cinema in qatar w USERNAME",2,0,0),
(3,"wkwkw JUDULFILM with feri URL",2,0,0),
(3,"at HASHTAG with elghali USERNAME",2,0,0),
(3,"pengen nonton JUDULFILM jugak URL",2,0,0),
(3,"nemenin ajalah JUDULFILM URL URL",2,0,0),
(3,"JUDULFILM golden screen cinemas gsc USERNAME in subang jaya selangor URL",2,0,0),
(3,"ngebujuk meren ah JUDULFILM with azrieldaru URL URL",2,0,0),
(3,"HASHTAG JUDULFILM ni taknak pulak dia keluar kat facebook",2,0,0),
(3,"nonton diriku sendiri JUDULFILM with ramadhani at USERNAME URL HASHTAG",2,0,0),
(3,"menit ke 40 si anak bayik bobok padahal tadinya ngekek2 nonton JUDULFILM w fajar at suite room 385 URL URL",2,0,0),
(3,"telegraaf JUDULFILM URL URL",2,0,0),
(3,"sambung lagi JUDULFILM HASHTAG",2,0,0),
(3,"anjir bayi nya bisa ngomong wkwk JUDULFILM URL",2,0,0),
(3,"JUDULFILM mbo cinemas in subang jaya selangor URL",2,0,0),
(3,"JUDULFILM mbo cinemas in subang jaya URL",2,0,0),
(3,"keturutan JUDULFILM at USERNAME URL",2,0,0),
(3,"USERNAME seronok je layan movie JUDULFILM tadi hahah tak fikir nak pi check jadual pun",2,0,0),
(3,"JUDULFILM with mawadah and deajeng URL",2,0,0),
(3,"sebelum berangkat JUDULFILM with ridho valent URL URL",2,0,0),
(3,"siapa yang sudah nonton HASHTAG di cinemaxx masih punya tiketnya ikutan kuisnya di facebook dan instagram yuk URL URL",2,0,0),
(3,"ucul anet bikin gemay dah ah wkwk JUDULFILM URL",2,0,0),
(3,"JUDULFILM at kementrian pu pr bws k iii kaltim URL",2,0,0),
(3,"USERNAME awk nak tgk JUDULFILM tak kat cinema HASHTAG HASHTAG",2,0,0),
(12,"USERNAME USERNAME USERNAME USERNAME gw gak nyangka JUDULFILM se pemes ini jadi terharu",2,0,0),
(12,"USERNAME arti JUDULFILM apaan",2,0,0),
(12,"USERNAME aku belum bilang ya skrg aku join JUDULFILM",2,0,0),
(12,"HASHTAG HASHTAG USERNAME USERNAME 49 000 pesan 085793042909 sms wa USERNAME URL URL",2,0,0),
(12,"gatau mau ngetik apa lagi wkwkwk cuma mau mengutarakan perasaan ini saja nyay wkwk salam JUDULFILM d HASHTAG HASHTAG",2,0,0),
(12,"USERNAME kemudian rekrut mereka ke JUDULFILM",2,0,0),
(12,"USERNAME nonton JUDULFILM ae ci wkwk",2,0,0),
(12,"USERNAME JUDULFILM yha",2,0,0),
(12,"HASHTAG HASHTAG USERNAME USERNAME 49 000 pesan 085793042909 sms wa USERNAME",2,0,0),
(31,"tgk JUDULFILM ni dgn aku sekali rasa nak menari seronok pulak aku tgk rentak tari dorg",2,0,0),
(31,"plexpy homemedia daisukiosarusaUSERNAME com mama has stopped JUDULFILM",2,0,0),
(31,"JUDULFILM ngelah meme dewo URL",2,0,0),
(31,"ending tak guna knape tak sebastian ngn mia HASHTAG",2,0,0),
(31,"heyy ternyata di HASHTAG ada ngomongin tentang HASHTAG heeee",2,0,0),
(31,"nak tgk JUDULFILM jd la la tido mai",2,0,0),
(31,"mata masih melek JUDULFILM URL",2,0,0),
(31,"udah tiga kali nonton sih but still leave with a tear in my eyes and song in my heart karena JUDULFILM URL",2,0,0),
(31,"5 years later kata kata wanita halah semf k doangan JUDULFILM at wisma bakrie 1 lt2 URL",2,0,0),
(31,"ngam jugak soundtrack JUDULFILM",2,0,0),
(31,"USERNAME USERNAME hai paan nak tengok JUDULFILM lagi haha",2,0,0),
(31,"good morning all you guys amp gals out in JUDULFILM let s push it to the weekend URL",2,0,0),
(31,"karena soundtracknya JUDULFILM always do me good ku pun tak tau",2,0,0),
(31,"as for me its gotta be ryan gosling klu x takkan la sanggup tgk 3 kali JUDULFILM kt panggung URL",2,0,0),
(31,"HASHTAG saati",2,0,0),
(31,"lol moonlight kenapa disamain sama trump anies maaf ye moonlight gt gt gt gt gt gt gt gt gt gt gt gt gt gt gt gt gt gt gt gt gt gt gt gt gt JUDULFILM",2,0,0),
(31,"i nak tengok JUDULFILM pastu maybe rewatch 13rw takpun sambung tengok reply 1988",2,0,0),
(31,"belum tgk JUDULFILM lg",2,0,0),
(31,"USERNAME yg JUDULFILM nto km udh nonton",2,0,0),
(31,"JUDULFILM 2016 720p brrip 1 2gb URL URL",2,0,0),
(31,"JUDULFILM gt reqs",2,0,0),
(31,"mending pulangin aje paaaak JUDULFILM at panin bank menara imperium URL",2,0,0),
(31,"dah tonton JUDULFILM HASHTAG",2,0,0),
(31,"la JUDULFILM kalau dekat kedah depa panggil tanah sekarang sekarang sekarang",2,0,0),
(31,"USERNAME inget soal rilis HASHTAG kan",2,0,0),
(31,"jadi keinget twitnya beliau soal tanggal rilis JUDULFILM di sindang",2,0,0),
(31,"anggukan kang rian dan mata bombay ceu ema di scene terakhir fine i m fine HASHTAG JUDULFILM URL",2,0,0),
(31,"184 penghargaan dari 224 nominasi JUDULFILM URL",2,0,0),
(120,"JUDULFILM full movie seru ajaannn coy URL",2,0,0),
(120,"sebangsa monyet JUDULFILM URL",2,0,0),
(120,"engkong engkong JUDULFILM URL",2,0,0),
(120,"news HASHTAG dibuatkan serial tv URL via USERNAME URL",2,0,0),
(120,"reviewinhaiku JUDULFILM URL",2,0,0),
(120,"reviewinhaiku JUDULFILM URL",2,0,0),
(120,"reviewinhaiku JUDULFILM parislemon URL",2,0,0),
(120,"conexion JUDULFILM pacific rim king ghidorah kaiju categoria 6 HASHTAG URL",2,0,0),
(120,"URL conexion HASHTAG HASHTAG king ghidorah kaiju categoria 6 HASHTAG URL",2,0,0),
(120,"liburaaaaan JUDULFILM URL",2,0,0),
(120,"layan JUDULFILM bersama daim hoho URL",2,0,0),
(120,"JUDULFILM with iqbal URL",2,0,0),
(120,"akhirnya rehat juga JUDULFILM with rendy URL",2,0,0),
(120,"JUDULFILM kong sunset tshirt charcoal URL HASHTAG URL",2,0,0),
(120,"merasakan petualangan ala kong skull island di pulau ini URL HASHTAG URL",2,0,0),
(120,"bagadang nonton JUDULFILM HASHTAG",2,0,0),
(120,"dah tak tau nak tengok apa layan je la JUDULFILM",2,0,0),
(120,"JUDULFILM at lamteh ulee kareng URL",2,0,0),
(120,"hayu urang lalajo hela monyet JUDULFILM URL",2,0,0),
(120,"ganda ng HASHTAG",2,0,0),
(120,"ngemil sambil nonton beginian supeer sekali suamiku JUDULFILM with ryan at modernland URL",2,0,0),
(120,"hari terakhir cuti nontonnya di dvd aja JUDULFILM URL",2,0,0),
(120,"watching JUDULFILM at petak segiempatnya odhie URL",2,0,0),
(120,"JUDULFILM gempak gak ah",2,0,0),
(120,"sambil nungguin dia yg lg nonton juga d sana JUDULFILM with theresia URL",2,0,0),
(120,"k e r a ga ada JUDULFILM URL",2,0,0),
(120,"daripada JUDULFILM at dprd provinsi bangka belitung URL",2,0,0),
(120,"ada yang sudah nonton JUDULFILM seru gak",2,0,0),
(120,"segerin otak dulu laah JUDULFILM with anggara risma and fabian URL",2,0,0),
(120,"cinema for 1 HASHTAG HASHTAG HASHTAG USERNAME HASHTAG HASHTAG URL",2,0,0),
(120,"JUDULFILM 2017 supan begadang",2,0,0),
(120,"JUDULFILM kong sunset tshirt charcoal URL HASHTAG HASHTAG URL",2,0,0),
(120,"menemani di perjalanan JUDULFILM at stasiun muara enim URL",2,0,0),
(29,"kapan mau ngerjain proposal jul john wick chapter 2 URL",2,0,0),
(29,"udah mau pensiun jangan di ganggu terus john wick chapter 2 URL",2,0,0),
(29,"sudah nonton logan amp john wick chapter 2 saya belum makanya mau nonton dulu bruahahaha d",2,0,0),
(29,"john wick chapter 2 2017 balkan kino hd balkan kino hd URL",2,0,0),
(29,"USERNAME USERNAME nich jonwik tp qualitas msh cam URL",2,0,0),
(36,"nonton moammar emka s JUDULFILM 2017 URL URL",2,0,0),
(36,"judulnya JUDULFILM",2,0,0),
(36,"akhirnya kesampean nonton JUDULFILM jugak",2,0,0),
(36,"USERNAME mas fajar saya novy dari trans7 bisa kami kirim undangan utk acara usmar ismail awards 2017 utk tim JUDULFILM",2,0,0),
(36,"81 moammar emka s JUDULFILM 2017 director fajar nugros casts oka antara tiara eve baim wong ganind URL",2,0,0),
(36,"JUDULFILM HASHTAG",2,0,0),
(36,"ganindra bimo di JUDULFILM",2,0,0),
(36,"USERNAME JUDULFILM gak dibuat dvdnya mas director s cut gitu",2,0,0),
(36,"JUDULFILM mas URL",2,0,0),
(36,"JUDULFILM 2017 udah muncul di tv kabel wtf",2,0,0),
(36,"jangan bahas JUDULFILM blm nonton JUDULFILM",2,0,0),
(36,"bagaimana sisi lain kehidupan jakarta saksikan JUDULFILM hanya di URL URL",2,0,0),
(36,"HASHTAG JUDULFILM",2,0,0),
(36,"kan bego ya mau update path JUDULFILM terus gaada jadinya ga update tapi ternyata namanya the fate and furious 8 HASHTAG",2,0,0),
(36,"USERNAME USERNAME USERNAME USERNAME USERNAME wkwkwk pajero bergoyang terinspirasi JUDULFILM",2,0,0),
(36,"USERNAME pengen nonton JUDULFILM sii sebenernya tapi udah ada blom yaa di web2",2,0,0),
(36,"USERNAME JUDULFILM",2,0,0),
(36,"JUDULFILM jika ada pasien yg datang padaku dan tak punya uang aku ingin sekali bilang tak usah bayar leorio",2,0,0),
(36,"JUDULFILM udah ada aja di youtube khan maen",2,0,0),
(36,"JUDULFILM petjaaahhh",2,0,0),
(36,"USERNAME HASHTAG di youtube udah 42ribu view di bioskop brp pnonton bang",2,0,0),
(28,"oh kena cari buku ni JUDULFILM punnn URL",2,0,0),
(28,"kamala khan JUDULFILM 2016 dir theodore melfi URL",2,0,0),
(28,"patut tgok JUDULFILM tgok how coloured ppl kena oppressed walaupun they are the roots in nasa rasa nk cungkil bijik mata the whites",2,0,0),
(28,"btw aku rasa macam dekat sikit ngan JUDULFILM tu sebab guna fortran lol",2,0,0),
(28,"inspired doh tgk JUDULFILM nak join nasa la camni",2,0,0),
(28,"kelar nonton HASHTAG setelah berkali2 stuck di menit 35 akhirnyaaaah",2,0,0),
(28,"taraji or daniel HASHTAG HASHTAG URL",2,0,0),
(28,"sodhya thetrippytrip JUDULFILM vol 2 their names are ritu karidhal anuradha tk nandini URL",2,0,0),
(28,"USERNAME yang satu JUDULFILM satu lagi race",2,0,0),
(28,"smbl ngademin badan JUDULFILM at the kusumonegoro s URL",2,0,0),
(28,"USERNAME JUDULFILM kan dil bukan hidden identity",2,0,0),
(28,"tgk esok jelah JUDULFILM tu",2,0,0),
(28,"JUDULFILM genrenya apa unnyie d URL",2,0,0),
(28,"di 18 04 2017 cinerama rotterdam JUDULFILM URL HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(28,"lanjut lagi nonton ini JUDULFILM URL",2,0,0),
(28,"deaf JUDULFILM in nasa HASHTAG HASHTAG URL",2,0,0),
(28,"asilversnake JUDULFILM 2016 dir theodore melfi URL",2,0,0),
(28,"filmnya jenius JUDULFILM URL",2,0,0),
(28,"shit chada kau ang JUDULFILM",2,0,0),
(28,"USERNAME dah nonton JUDULFILM beluuum",2,0,0),
(28,"ke kopang JUDULFILM",2,0,0),
(28,"taraji p henson HASHTAG URL",2,0,0),
(1,"USERNAME USERNAME hahahha JUDULFILM dah tengok",2,0,0),
(1,"beli tiket JUDULFILM nontonnya danur HASHTAG HASHTAG HASHTAG",2,0,0),
(1,"independent cinema in pzn screening JUDULFILM 1995 URL",2,0,0),
(1,"USERNAME hahaa dh jdi JUDULFILM ka apa",2,0,0),
(1,"motoko kusanagi HASHTAG HASHTAG foto patricia bueno photography dannybocabit URL",2,0,0),
(1,"motoko kusanagi USERNAME p USERNAME HASHTAG HASHTAG HASHTAG URL",2,0,0),
(1,"nindy ny obok ibu ny ga ada kerjaan JUDULFILM URL",2,0,0),
(1,"motoko HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(1,"HASHTAG kenji kawai utai iv reawakening steve aoki remix URL HASHTAG getting feels URL",2,0,0),
(1,"USERNAME ini lagi cosplay jadi batou di JUDULFILM itu ya URL",2,0,0),
(1,"tahukah anda aku tak tengok lagi beauty amp the beast JUDULFILM power rangers dan fast amp furious 8",2,0,0),
(1,"USERNAME aku nak tengok JUDULFILM 6 40pm nak hadap jammed lagi confirm tak sempat",2,0,0),
(1,"rasa macam nak tengok JUDULFILM tapi 6 40 pm macam tak sempat je",2,0,0),
(1,"USERNAME jaja cerca JUDULFILM 1995",2,0,0),
(1,"motoko kusanagi JUDULFILM HASHTAG URL URL",2,0,0),
(1,"USERNAME mai kof ayane doa ryo hazuki shenmue kusanagi JUDULFILM pai vf kitana mk URL",2,0,0),
(1,"USERNAME smlm tgk cter JUDULFILM",2,0,0),
(1,"shiro masamune HASHTAG URL URL",2,0,0),
(1,"elenasamko as major motoko kusanagi HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(1,"JUDULFILM eh itu cyberpunk deh URL URL",2,0,0),
(1,"duda JUDULFILM 1995 pelicula otaku zone URL",2,0,0),
(1,"belum tgk JUDULFILM power rangers kong sindiket",2,0,0),
(1,"org layan too fast too furious aku bru nk layan JUDULFILM lalalala",2,0,0),
(1,"HASHTAG oil paint",2,0,0),
(1,"oh hi joshua seth HASHTAG",2,0,0),
(1,"kempunan nak tengok fast8 terpaksa tukar ticket tengok JUDULFILM",2,0,0),
(1,"ebuset beauty amp the beast dan JUDULFILM sudah nggak ada di bioskop sama sekali",2,0,0),
(1,"JUDULFILM belom tengok fast furiouse 8 pulak yang kluar melepas lagi lah nampaknya",2,0,0),
(1,"apakah akan sekeren anime jepang nya JUDULFILM URL",2,0,0),
(1,"USERNAME carikan movie nerdland JUDULFILM dgan the boss baby klau dh kluar klau ada yg jenis animation URL",2,0,0),
(1,"motoko kusanagi JUDULFILM HASHTAG URL",2,0,0),
(1,"fast furious 53 balapan antara gerobak bakso dan gerobak cilok bertenaga fusi nuklir berlatar belakang cyberpunk ala JUDULFILM",2,0,0),
(1,"USERNAME JUDULFILM ok2 je la beauty tu tak tgk lg",2,0,0),
(1,"movie marathon yeah bebeh HASHTAG HASHTAG HASHTAG mbo URL",2,0,0),
(1,"JUDULFILM lfs cinema in kuala terengganu terengganu URL",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM HASHTAG HASHTAG",2,0,0),
(27,"USERNAME JUDULFILM HASHTAG w USERNAME",2,0,0),
(27,"HASHTAG HASHTAG masih di posisi yang sama ada gac JUDULFILM USERNAME",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM USERNAME HASHTAG md USERNAME HASHTAG",2,0,0),
(27,"HASHTAG with USERNAME HASHTAG USERNAME JUDULFILM USERNAME",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM with USERNAME amp USERNAME di HASHTAG HASHTAG",2,0,0),
(27,"JUDULFILM by d cinnamons URL",2,0,0),
(27,"endah n ressa JUDULFILM upin dan ipin jin dan jun URL",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM dj 9 USERNAME streaming URL HASHTAG URL",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM HASHTAG w dj USERNAME",2,0,0),
(27,"HASHTAG JUDULFILM USERNAME on HASHTAG HASHTAG with USERNAME amp USERNAME",2,0,0),
(27,"USERNAME JUDULFILM HASHTAG HASHTAG",2,0,0),
(27,"USERNAME JUDULFILM HASHTAG bareng USERNAME amp USERNAME",2,0,0),
(27,"HASHTAG JUDULFILM by USERNAME USERNAME HASHTAG md USERNAME",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(27,"4 USERNAME JUDULFILM 5 USERNAME aku wanita HASHTAG",2,0,0),
(27,"memainkan USERNAME tanpa melodi amp HASHTAG pekan ini USERNAME JUDULFILM HASHTAG bareng USERNAME",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM USERNAME HASHTAG HASHTAG HASHTAG URL",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM HASHTAG HASHTAG URL",2,0,0),
(27,"JUDULFILM by chrisye URL",2,0,0),
(27,"URL dcinnamons JUDULFILM 72 listeners HASHTAG",2,0,0),
(27,"np chrisye JUDULFILM HASHTAG URL",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM HASHTAG with USERNAME amp USERNAME",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM USERNAME pelangi USERNAME paris HASHTAG",2,0,0),
(27,"HASHTAG HASHTAG USERNAME USERNAME JUDULFILM bersama silvano ary USERNAME ayo req HASHTAG",2,0,0),
(27,"HASHTAG kan bego ya mau update path JUDULFILM terus gaada jadinya ga update tapi ternyata namanya the fate and furious 8 HASHTAG",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM HASHTAG URL",2,0,0),
(27,"JUDULFILM by d cinnamons URL",2,0,0),
(27,"7 JUDULFILM USERNAME URL HASHTAG",2,0,0),
(27,"JUDULFILM ya nih URL",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM w USERNAME USERNAME prod USERNAME HASHTAG",2,0,0),
(27,"HASHTAG USERNAME jangan hilangkan dia USERNAME JUDULFILM streaming URL md USERNAME HASHTAG",2,0,0),
(27,"76 JUDULFILM 2017 director lucky kuswandi casts sheryl sheinafia refal hadi 2 5 5 URL",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM HASHTAG URL URL",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM HASHTAG URL",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM dj 9 USERNAME streaming URL HASHTAG URL",2,0,0),
(27,"gimana caranya kalo mau nonton JUDULFILM lagi USERNAME cuma sempet nonton sekali krn uts HASHTAG",2,0,0),
(27,"HASHTAG JUDULFILM USERNAME HASHTAG with USERNAME",2,0,0),
(27,"JUDULFILM USERNAME HASHTAG w USERNAME URL amp USERNAME",2,0,0),
(27,"playhits USERNAME JUDULFILM HASHTAG w USERNAME cc md USERNAME",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM HASHTAG streaming URL URL",2,0,0),
(27,"JUDULFILM jjs makassar meet up kumpul di bioskop sblm jam 4 yg mau ikut nobar JUDULFILM tapi bisa kumpul di mcd juga abis nobar",2,0,0),
(27,"JUDULFILM jkt JUDULFILM URL",2,0,0),
(27,"JUDULFILM gac with USERNAME URL",2,0,0),
(27,"USERNAME ciee haha JUDULFILM wkwk lu nongkrong ama gw nya kapan",2,0,0),
(27,"joox mini konser JUDULFILM HASHTAG d mall kota kasablanka URL",2,0,0),
(27,"HASHTAG edisi 16 22 april 2017 HASHTAG USERNAME JUDULFILM cc USERNAME URL",2,0,0),
(27,"posisi 05 USERNAME JUDULFILM naik 1 peringkat HASHTAG URL URL",2,0,0),
(27,"ini JUDULFILM bukan galih dan angga URL",2,0,0),
(27,"HASHTAG 09 gac JUDULFILM 10 raisa x isyana anganku anganmu 11 bcl feat dipha barus aku wanita",2,0,0),
(27,"posisi ke 3 gt gt JUDULFILM lt lt USERNAME di aksi HASHTAG w USERNAME cc md USERNAME HASHTAG",2,0,0),
(27,"HASHTAG USERNAME JUDULFILM HASHTAG w USERNAME URL",2,0,0),
(27,"USERNAME JUDULFILM HASHTAG bareng USERNAME amp USERNAME",2,0,0),
(27,"JUDULFILM USERNAME HASHTAG with USERNAME URL amp USERNAME",2,0,0),
(27,"HASHTAG gac JUDULFILM HASHTAG",2,0,0),
(27,"USERNAME enggak ah inginnya JUDULFILM p",2,0,0),
(27,"USERNAME JUDULFILM gac",2,0,0),
(27,"USERNAME USERNAME USERNAME cie bagai JUDULFILM",2,0,0),
(27,"USERNAME biar apa anjir hapal lagi JUDULFILM",2,0,0),
(11,"novel JUDULFILM gue dimanaaaaa",2,0,0),
(11,"USERNAME JUDULFILM file 1 URL file 2 lanjutannya URL",2,0,0),
(11,"e book JUDULFILM dilan 1 dilan 2 milea boy chandra 4 ebook cuma 10k minat dm tag lelang acc upfoll ig rp apl HASHTAG",2,0,0),
(11,"USERNAME ak kangen burger king kangen danur kangen JUDULFILM kangen mba asih juga",2,0,0),
(11,"USERNAME kek cowo macem JUDULFILM",2,0,0),
(11,"USERNAME apa tuh JUDULFILM lagi jangan jangan",2,0,0),
(11,"USERNAME USERNAME pengen nonton JUDULFILM",2,0,0),
(11,"USERNAME aku ada JUDULFILM nih",2,0,0),
(11,"USERNAME ada JUDULFILM gak",2,0,0),
(11,"dari JUDULFILM danur sampe fast furious keluar gak ada yang ajakin gue nonton HASHTAG",2,0,0),
(11,"e book JUDULFILM dilan 1 dilan 2 milea boy chandra 4 ebook cuma 10k minat dm tag lelang acc upfoll ig rp apl HASHTAG HASHTAG",2,0,0),
(11,"dari JUDULFILM danur sampe fast furious keluar gak ada yang ajakin gue nonton",2,0,0),
(11,"ada yang jual ebook gak sih aku pengen baca JUDULFILM",2,0,0),
(11,"aku tak pernah tau sebenarnya hatimu untuk siapa yang aku tau aku begitu menyayangimu JUDULFILM",2,0,0),
(11,"HASHTAG eriscafebriani peringkat 1 HASHTAG eriscafebriani peringkat 2 HASHTAG URL",2,0,0),
(11,"dari JUDULFILM danur sampe fast furious keluar gak ada yang ajakin gue nonton yha",2,0,0),
(11,"USERNAME USERNAME orang lain kan JUDULFILM gw dear muel",2,0,0),
(11,"e book JUDULFILM dilan 1 dilan 2 milea boy chandra 4 ebook cuma 10k minat dm tag lelang acc upfoll ig rp apl HASHTAG HASHTAG HASHTAG",2,0,0),
(11,"e book JUDULFILM dilan 1 dilan 2 milea boy chandra 4 ebook cuma 10k minat dm tag lelang acc upfoll ig rp apl URL",2,0,0),
(11,"dari JUDULFILM danur sampe fast furious keluar gak ada yang ajakin gue nonton",2,0,0),
(11,"USERNAME itu JUDULFILM woyy",2,0,0),
(11,"USERNAME USERNAME kebaca JUDULFILM",2,0,0),
(11,"USERNAME iya nnti kek JUDULFILM laku yes i am",2,0,0),
(11,"USERNAME ohh JUDULFILM sip makasih",2,0,0),
(11,"USERNAME emang pelangi ostnya JUDULFILM kak",2,0,0),
(11,"USERNAME itu ost nya JUDULFILM kan ya",2,0,0),
(11,"USERNAME pemain JUDULFILM",2,0,0),
(11,"harpot JUDULFILM anjir anjir sedap URL",2,0,0),
(11,"HASHTAG ada yang punya ebook romance selain JUDULFILM sama dilan",2,0,0),
(11,"yukkk yang belum baca ebook dilan 1990 dilan 1991 milea dan JUDULFILM beli di aku aja sinii muraaa gt lt t lelang acc",2,0,0),
(11,"ini gada yg ngajakin nonton JUDULFILM atau fast furious 8 gtu tah",2,0,0),
(11,"e book JUDULFILM dilan 1 dilan 2 milea boy chandra 4 ebook cuma 10k minat dm tag lelang acc upfoll ig rp apl",2,0,0),
(11,"USERNAME gue boro2 nonton tau JUDULFILM aja kagak",2,0,0),
(11,"apa cuma gw disini yg blm nonton dear sehun eh maksut gw JUDULFILM",2,0,0),
(11,"USERNAME abrani yaziz gt lt atau ngga pemainya JUDULFILM atau ngga kevin anggara udah abrani yaziz ajaaa",2,0,0),
(25,"ab JUDULFILM hoga URL",2,0,0),
(25,"aamir khan kiran rao sanaya malhotra fatima sana shaikh at dinner JUDULFILM reunion has been published on URL",2,0,0),
(25,"USERNAME koi office me busy hai to koi college me raat 9 k baad sb twitter pe aayen ge phir hoga JUDULFILM",2,0,0),
(25,"is performance of ritika singh in irudhi suttru saala khadoos better than fatima sana shaikh in JUDULFILM HASHTAG URL",2,0,0),
(25,"USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME URL",2,0,0),
(25,"USERNAME 2017 ane kadhu bahubali 2 all india no 1 untadhi beating aamir mve JUDULFILM",2,0,0),
(25,"ml ent aamir khan promotes JUDULFILM in china URL HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(25,"USERNAME USERNAME USERNAME aamir ki JUDULFILM or pk ne 750 crore sirf muslim viewers ki wjh se n URL",2,0,0),
(25,"coverage trail during the mcd election intakhabi akhade mai khawateen ka dilchasp JUDULFILM USERNAME HASHTAG URL",2,0,0),
(25,"mitron bahot mna liya farewell ab JUDULFILM hoga",2,0,0),
(25,"USERNAME ab JUDULFILM hoga",2,0,0),
(25,"ifa award ah JUDULFILM nominate nuvee form furaafai nuvaathee URL URL",2,0,0),
(25,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG",2,0,0),
(25,"2nd jhiri kesari indian style JUDULFILM on apr 23 URL HASHTAG HASHTAG HASHTAG",2,0,0),
(25,"USERNAME tu meri from bang bang tu hi to hai from holiday JUDULFILM from JUDULFILM",2,0,0),
(25,"aamir promotes JUDULFILM in china URL",2,0,0),
(25,"HASHTAG bollywoodbio music JUDULFILM 10tb by daler mehndi",2,0,0),
(25,"amma ki har bat k jawab dene ka naam hai pyare JUDULFILM JUDULFILM",2,0,0),
(25,"USERNAME USERNAME fir JUDULFILM hoga",2,0,0),
(25,"USERNAME in chengdu china HASHTAG URL",2,0,0),
(25,"udta punjab fan JUDULFILM sultan and highway URL",2,0,0),
(25,"USERNAME USERNAME USERNAME USERNAME waha pe gajhini tzp fanaa rang de bas URL",2,0,0),
(25,"bhaitards on tl boxofficeemperor messiah is back to save bollywood bhaitards dm leave JUDULFILM kya lagta he pk cross hogi yaa mushkil hai",2,0,0),
(25,"USERNAME USERNAME USERNAME 400 cr budget movie hai oopar se doosre industry ki hai bollywood URL",2,0,0),
(25,"HASHTAG fat to fit aamir khan body transformation JUDULFILM in cinemas dec 23 2016 URL",2,0,0),
(25,"USERNAME jolly llb 2 commando 2 kaabil raees JUDULFILM",2,0,0),
(25,"USERNAME xxx ko bhi beat karegi taiwan mein xxx did 55m nt in taipei also JUDULFILM at no 8 in annual list hist URL",2,0,0),
(25,"USERNAME vvc kalti maar lenge yaisa lag raha hai",2,0,0),
(25,"USERNAME USERNAME in hindi tubelight overall india baahubali2",2,0,0),
(25,"USERNAME 1 baahubali2 2 tubelight tzh 3 2point0 tzh tubelight",2,0,0),
(25,"USERNAME baahubali 2",2,0,0),
(25,"USERNAME JUDULFILM download in mes buat dirumah apa ya",2,0,0),
(25,"ab JUDULFILM hoga HASHTAG URL",2,0,0),
(25,"in china aamir promotes JUDULFILM URL",2,0,0),
(25,"USERNAME USERNAME haha ab JUDULFILM hoga",2,0,0),
(25,"wrestling koi khel nahi hai yeh woh JUDULFILM hai joh insaan apni zindagi mein apne aap se ladta hai fascinating tubelight poster",2,0,0),
(25,"ab JUDULFILM hoga",2,0,0),
(25,"USERNAME JUDULFILM 2017 HASHTAG URL",2,0,0),
(25,"USERNAME naina from JUDULFILM HASHTAG HASHTAG",2,0,0),
(25,"aamir promotes JUDULFILM in china URL URL",2,0,0),
(25,"pk doll HASHTAG USERNAME URL",2,0,0),
(25,"ab JUDULFILM hoga",2,0,0),
(25,"USERNAME or shrot karva lo JUDULFILM JUDULFILM type",2,0,0),
(25,"USERNAME USERNAME USERNAME tumne to JUDULFILM macha diya",2,0,0),
(25,"watching JUDULFILM URL",2,0,0),
(25,"USERNAME sultan bb pk JUDULFILM",2,0,0),
(25,"jai jai bajrang bali",2,0,0),
(25,"rip JUDULFILM URL",2,0,0),
(25,"USERNAME wo post mat kerna werna JUDULFILM hoga bitch",2,0,0),
(25,"neha kakkar naina JUDULFILM lyrics URL",2,0,0),
(25,"USERNAME all above formulas are working right now 1baahubali jangal book 2 bajrangi sultan jolly llb 3 pink udta punjab 4 neerja JUDULFILM",2,0,0),
(25,"aamir promotes JUDULFILM in china URL URL",2,0,0),
(25,"jo b jeety JUDULFILM tu hoga HASHTAG",2,0,0),
(25,"imran khan 2 bajay uth jana ns kyun imran khan JUDULFILM hoga JUDULFILM HASHTAG",2,0,0),
(25,"USERNAME USERNAME mari JUDULFILM and dhoom 3 lo kuda ledhu ga a range comedy",2,0,0),
(25,"bharat kesari JUDULFILM 2017 URL",2,0,0),
(25,"watch apn special report dilli ka JUDULFILM URL HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(25,"yoga training in chengudu city china HASHTAG HASHTAG URL",2,0,0),
(25,"USERNAME city hai chengdu",2,0,0),
(25,"USERNAME teri bath main utna hi dum hain jitna tu bola tha ki JUDULFILM will not cross 150cr in earlier tweets mental hai tu",2,0,0),
(25,"qingcheng mountain tea HASHTAG URL",2,0,0),
(25,"USERNAME chengdu matlab kya bhai",2,0,0),
(25,"chengdu HASHTAG URL URL",2,0,0),
(25,"chengdu HASHTAG URL",2,0,0),
(25,"JUDULFILM in chengdu HASHTAG URL",2,0,0),
(25,"chengdu URL",2,0,0),
(25,"sanghar aj sanghar man halqa ps81 man zimni intakhabat ka JUDULFILM shro ppp or pfl ka umeedwaron ka darmiyan kanty ka mqbla zarai rep ali",2,0,0),
(25,"USERNAME USERNAME esaretin bedeli JUDULFILM",2,0,0),
(25,"waaah sun ke acha lga ke fsc walo ka JUDULFILM he kal",2,0,0),
(25,"USERNAME jai salman khan be afraid JUDULFILM",2,0,0),
(25,"JUDULFILM",2,0,0),
(25,"USERNAME USERNAME ab JUDULFILM hoga",2,0,0),
(25,"omg yea sab geeta babita ki wajh sy ho raha p HASHTAG HASHTAG URL",2,0,0),
(25,"USERNAME USERNAME USERNAME na like JUDULFILM ka akhada",2,0,0),
(25,"USERNAME USERNAME JUDULFILM JUDULFILM JUDULFILM JUDULFILM JUDULFILM only JUDULFILM",2,0,0),
(25,"USERNAME kab bola",2,0,0),
(25,"USERNAME ab JUDULFILM hoga isko kato bal",2,0,0),
(25,"kal JUDULFILM hou ga",2,0,0),
(25,"padu yal cite JUDULFILM ni",2,0,0),
(25,"USERNAME nahe ub tw JUDULFILM hoga xd yo bro",2,0,0),
(7,"USERNAME bioskop JUDULFILM bukan di bioskop definitely maybe",2,0,0),
(35,"watching JUDULFILM with dandy fahsi at yukum jaya URL",2,0,0),
(35,"power rangers bukan gaban bukan ultraman jg bukan JUDULFILM URL",2,0,0),
(33,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"adina JUDULFILM URL",2,0,0),
(33,"JUDULFILM jo b jeety JUDULFILM tu hoga HASHTAG",2,0,0),
(33,"tak kirain si mas yang di thirteen reasons why ini JUDULFILM lerman ternyata namanya dylan minnette URL",2,0,0),
(33,"JUDULFILM",2,0,0),
(33,"JUDULFILM",2,0,0),
(33,"JUDULFILM joe taslim bilang film ini keren banget dan apik penasaran lihat lengkapnya di sini URL",1,0,0),
(33,"pada tahun 1850 sarjana asal skotlandia james richardson JUDULFILM mengusulkan nama wilayah kita dengan sebutan indonesia",2,0,0),
(33,"USERNAME USERNAME USERNAME JUDULFILM bukan logam wkwkwk",2,0,0),
(33,"JUDULFILM",2,0,0),
(33,"USERNAME jallai dire",2,0,0),
(33,"USERNAME wiahahahahahaakbajakaanz ta pp",2,0,0),
(33,"JUDULFILM HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"USERNAME JUDULFILM pun ada",2,0,0),
(33,"JUDULFILM",2,0,0),
(33,"hantu si JUDULFILM kah blakun arah fast 9 ni URL",2,0,0),
(33,"JUDULFILM",2,0,0),
(33,"JUDULFILM URL",2,0,0),
(33,"JUDULFILM URL",2,0,0),
(33,"JUDULFILM HASHTAG mbo cinemas in subang jaya selangor URL URL",2,0,0),
(33,"JUDULFILM",2,0,0),
(33,"bruhhhh JUDULFILM",2,0,0),
(33,"JUDULFILM",2,0,0),
(33,"JUDULFILM mbo cinemas in subang jaya selangor URL",2,0,0),
(33,"USERNAME bagarai",2,0,0),
(33,"JUDULFILM",2,0,0),
(33,"kapan mau ngerjain proposal jul john wick chapter 2 URL URL",2,0,0),
(33,"JUDULFILM imax novo cinema in qatar w USERNAME URL URL",2,0,0),
(33,"JUDULFILM mbo cinemas in subang jaya selangor URL URL",2,0,0),
(33,"JUDULFILM eh itu cyberpunk deh URL",2,0,0),
(33,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"JUDULFILM URL",2,0,0),
(33,"USERNAME watch JUDULFILM or kong",2,0,0),
(33,"han ado JUDULFILM pun ado menarikkkkkk URL",2,0,0),
(33,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"kapil vs sunil fight JUDULFILM URL via USERNAME HASHTAG",2,0,0),
(33,"JUDULFILM lerman",2,0,0),
(33,"selesai ibadah sholat jum at ngopi dulu omong klobot karo konco2ne guyonan lan ndelok pilem anyaarr JUDULFILM",2,0,0),
(33,"caman JUDULFILM URL",2,0,0),
(33,"JUDULFILM wade lerman january 19 1992 URL",2,0,0),
(33,"JUDULFILM 2017 URL HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"USERNAME ketoke JUDULFILM isih anyar anyaran ga sih itungane wkwk",2,0,0),
(33,"okay malam ni mimpi JUDULFILM",2,0,0),
(33,"qi jun dah URL",2,0,0),
(33,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"USERNAME USERNAME JUDULFILM",2,0,0),
(33,"JUDULFILM 2017 URL",2,0,0),
(33,"req 100 HASHTAG ut usa 05 18 2017 paypal URL URL",2,0,0),
(33,"lil mama bad",2,0,0),
(33,"karena soundtracknya JUDULFILM always do me good ku pun tak tau HASHTAG",2,0,0),
(33,"kasian sih film JUDULFILM rilis pas para film film besar rilis juga untung masih ada satu bioskop di sini yg nayangin HASHTAG",1,0,0),
(33,"JUDULFILM HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"jadi pengen bacain surat yassin dan tahlil sampe 40 harinya smoga arwahnya JUDULFILM diterima disisi nya pic URL",2,0,0),
(33,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"12 12 JUDULFILM",2,0,0),
(33,"USERNAME USERNAME ntah special appearance kot JUDULFILM buat hal hahah",2,0,0),
(33,"JUDULFILM bebito henderson desire gm URL",2,0,0),
(33,"kayaknya dr semua tiket yg tercetak tulisan judulnya JUDULFILM semua padahal judul aslinya the URL URL",2,0,0),
(33,"empat seketul JUDULFILM mark george johannes",2,0,0),
(33,"JUDULFILM golden screen cinemas gsc USERNAME in petaling jaya selangor URL",2,0,0),
(33,"USERNAME yo un JUDULFILM huntzberger jaja",2,0,0),
(33,"JUDULFILM lerman URL",2,0,0),
(33,"JUDULFILM kong lego batman URL",2,0,0),
(33,"liane wes do nonton ff8 kene lg meh nonton JUDULFILM mbi resident evil kui wae sih cam",2,0,0),
(33,"JUDULFILM imax novo cinema in qatar w USERNAME URL",2,0,0),
(33,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"chafta training program JUDULFILM URL",2,0,0),
(33,"poor JUDULFILM URL",2,0,0),
(33,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"kendrick lamar dna URL via USERNAME",2,0,0),
(33,"HASHTAG JUDULFILM HASHTAG",2,0,0),
(33,"JUDULFILM URL HASHTAG",2,0,0),
(33,"JUDULFILM john wick chapter 2 2017 balkan kino hd balkan kino hd URL",2,0,0),
(33,"USERNAME USERNAME JUDULFILM",2,0,0),
(33,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"JUDULFILM selain mutant juga seorang transporter ya jago ngeles pas nyetir HASHTAG HASHTAG HASHTAG",2,0,0),
(33,"USERNAME JUDULFILM HASHTAG",2,0,0),
(33,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(48,"JUDULFILM ku URL",2,0,0),
(48,"pulau padar di pagi hari HASHTAG HASHTAG HASHTAG URL",2,0,0),
(48,"btw JUDULFILM diterjemahkan menjadi parts of hearts sebentar",2,0,0),
(48,"HASHTAG HASHTAG JUDULFILM URL",2,0,0),
(48,"saat HASHTAG HASHTAG HASHTAG USERNAME USERNAME USERNAME USERNAME URL",2,0,0),
(48,"HASHTAG nivea sun supports indonesian movie JUDULFILM URL URL",2,0,0),
(48,"view from room labuan bajo JUDULFILM HASHTAG HASHTAG HASHTAG URL",2,0,0),
(48,"11 03 am read a movie titled JUDULFILM as lebaran haji HASHTAG",2,0,0),
(48,"USERNAME nightbusfilm amp JUDULFILM apa sudah tayang",2,0,0),
(48,"nonton JUDULFILM 2017 URL",2,0,0),
(48,"nonton bareng JUDULFILM URL",2,0,0),
(48,"USERNAME JUDULFILM HASHTAG ikutan jg yuk USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME",2,0,0),
(13,"USERNAME aku kan JUDULFILM",2,0,0),
(13,"JUDULFILM dah nak beraksi jaga jaga guys USERNAME USERNAME USERNAME",2,0,0),
(13,"USERNAME eh ni prinsip JUDULFILM ni",2,0,0),
(13,"ultraman hingga JUDULFILM tolak pabrik semen rembang HASHTAG URL",2,0,0),
(13,"ultraman hingga JUDULFILM tolak pabrik semen rembang HASHTAG URL URL",2,0,0),
(13,"ultraman hingga JUDULFILM tolak pabrik semen rembang HASHTAG URL HASHTAG",2,0,0),
(13,"gagara hp dipinjam kemanakan playlist youtube berubah jaadi kamen rider JUDULFILM dll",2,0,0),
(13,"gonzalo oliver URL",2,0,0),
(13,"USERNAME bila masa anak kita ada darah JUDULFILM HASHTAG",2,0,0),
(13,"asal bju gx kali ni cam JUDULFILM",2,0,0),
(13,"berubah jadi JUDULFILM URL",2,0,0),
(13,"HASHTAG JUDULFILM rita repulsa 12 figure 2017 elizabeth banks green mmpr bandai URL",2,0,0),
(13,"USERNAME USERNAME USERNAME USERNAME ni JUDULFILM ninja nampak mata",2,0,0),
(13,"star news dari song joong ki hingga park bo young dan ryu jun yeol topik casting virtual JUDULFILM URL",2,0,0),
(13,"mari menyanyikan go go JUDULFILM bersama di HASHTAG URL HASHTAG",2,0,0),
(13,"USERNAME emang lo kata JUDULFILM bisa dirubah2",2,0,0),
(13,"hai gugun JUDULFILM loh",2,0,0),
(13,"USERNAME JUDULFILM dije",2,0,0),
(13,"wahh naruto dan JUDULFILM doyan sate juga tohh URL",2,0,0),
(13,"akhirnya keturutan jadi anggota JUDULFILM HASHTAG HASHTAG URL",2,0,0),
(13,"USERNAME itu semua binatang jadi JUDULFILM aci lah furry ww",2,0,0),
(13,"hola rangerfans seiya URL",2,0,0),
(13,"USERNAME USERNAME aloh jom tgk spiderman tp JUDULFILM pun okay",2,0,0),
(13,"JUDULFILM aka inhumans",2,0,0),
(13,"memang memori masa anak2 sampe sekarang tetep idolanya JUDULFILM tapi yang versi original yak",2,0,0),
(13,"malam ini memfollow instagram a k a ig para pemeran mighty morphin JUDULFILM ad jason kimberly sama tommy hahaha",2,0,0),
(13,"USERNAME diriku nanya joy bukan nyuruh kan td ava u JUDULFILM",2,0,0),
(13,"USERNAME ts JUDULFILM biar dikata apa",2,0,0),
(13,"USERNAME power game itu mainannya JUDULFILM a mbak 3",2,0,0),
(13,"indolanang rangga dika USERNAME dika by skiinmode USERNAME HASHTAG HASHTAG HASHTAG URL",2,0,0),
(13,"USERNAME USERNAME kamu JUDULFILM pink",2,0,0),
(13,"ini scene pas dia pose mau berubah jadi JUDULFILM or whatever superhero out there URL",2,0,0),
(13,"aku maunya JUDULFILM pink URL",2,0,0),
(13,"JUDULFILM ungu tembak phew phew phew URL",2,0,0),
(13,"JUDULFILM or kong",2,0,0),
(13,"USERNAME saya mah taunya JUDULFILM nun v",2,0,0),
(13,"USERNAME berubah jadi apa jangan bilang JUDULFILM",2,0,0),
(13,"beauty and the beast tak tgk JUDULFILM tak tgk fast and furious 8 tak tgk just semua tak tgk",2,0,0),
(13,"wew udah keluar diinternet nonton aaah JUDULFILM URL",2,0,0),
(13,"USERNAME USERNAME mcm JUDULFILM hahah",2,0,0),
(13,"USERNAME go go go JUDULFILM ta yaang",2,0,0),
(13,"USERNAME dah laa jad dah laa cuba laa tweet pasal ultraman ke JUDULFILM ke",2,0,0),
(13,"benjy ni bnyk kali da kene tahan sbb dadah JUDULFILM betol URL",2,0,0),
(13,"USERNAME USERNAME hahaahaa gmbar JUDULFILM laa",2,0,0),
(13,"ultraman hingga JUDULFILM tolak pabrik semen rembang HASHTAG URL URL URL",2,0,0),
(13,"USERNAME jam JUDULFILM ka wak",2,0,0),
(13,"USERNAME JUDULFILM aj gk ajak cukstaw",2,0,0),
(39,"USERNAME ko ad JUDULFILM personality eh bhye ko ni",2,0,0),
(39,"JUDULFILM blu ray dvd digital hd HASHTAG",2,0,0),
(39,"ordered a banana JUDULFILM and its JUDULFILMting my throat maneh nak mampuih",2,0,0),
(39,"klu lah bleh jdi cm amoeba mmg dh JUDULFILM kepada 5",2,0,0),
(39,"ni lah pelakon JUDULFILM tu URL",2,0,0),
(39,"USERNAME has akali dal JUDULFILM between senior badal amp junior badal",2,0,0),
(39,"banana JUDULFILM",2,0,0),
(39,"berak di celana sepelit JUDULFILM URL",2,0,0),
(39,"USERNAME USERNAME kalau was2 JUDULFILM ngan aku ah pablu",2,0,0),
(39,"USERNAME poco poco ajah kan gak pake JUDULFILM",2,0,0),
(39,"URL beautiful sakura aragaki pussy JUDULFILM wide open URL",2,0,0),
(39,"gai tendo JUDULFILM me open",2,0,0),
(39,"JUDULFILM perez",2,0,0),
(39,"halal peri peri chicken mini JUDULFILM stick more info URL",2,0,0),
(39,"USERNAME sajat hahahhah wehhhh dia JUDULFILM personality ka tiap kali pkul 1 ja pakai cam pompuan haaaa ayokkk",2,0,0),
(39,"gegara mangkok kmrn JUDULFILM 1 sekarang gegara gelang JUDULFILM 1 lg ayo oriflame keluarkan lagi",2,0,0),
(39,"euro 17 is settttttt prague JUDULFILM ibiza milan krakow berlin malta its littttttt",2,0,0),
(39,"USERNAME betul ke kau tertido ke kau tak sedar yg personality kau dah JUDULFILM",2,0,0),
(39,"sambung lagi besok JUDULFILM URL",2,0,0),
(39,"semalam tertido sambil tengok JUDULFILM nk smbung japgi",2,0,0),
(39,"1 logan 2 lego batman 3 JUDULFILM URL",2,0,0),
(39,"logan lego batman JUDULFILM URL",2,0,0),
(39,"banana JUDULFILM URL",2,0,0),
(39,"banana JUDULFILM",2,0,0),
(39,"banana JUDULFILM",2,0,0),
(39,"JUDULFILM 5on psg 2bar gn",2,0,0),
(39,"USERNAME asasi d hashof JUDULFILM khalas",2,0,0),
(39,"USERNAME apakah di lg k10 2017 yg ber os android nougat bisa JUDULFILM screen multi window",2,0,0),
(39,"banana JUDULFILM was bomb URL",2,0,0),
(39,"opet sam puka URL",2,0,0),
(39,"USERNAME JUDULFILM logan",2,0,0),
(39,"USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME banana JUDULFILM URL",2,0,0),
(39,"hyundai 1 ton 3 star JUDULFILM ac HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(39,"JUDULFILM personality tu mcm mna",2,0,0),
(39,"HASHTAG HASHTAG HASHTAG HASHTAG izhevsk udmurtiya URL",2,0,0),
(39,"banana JUDULFILM",2,0,0),
(39,"matane murup gak merem merem nyumet iki ae kah JUDULFILM URL",2,0,0),
(39,"banana JUDULFILM USERNAME URL",2,0,0),
(39,"USERNAME weiii aku tak nak jd mcm citer JUDULFILM tu",2,0,0),
(39,"USERNAME dia yang JUDULFILM personality bukan aku",2,0,0),
(39,"lrt that sakura JUDULFILM wow",2,0,0),
(39,"smart tv led 70 samsung 4k ultra hd 70ku6000 conversor digital ar condicionado JUDULFILM samsung URL",2,0,0),
(39,"USERNAME jangan kan JUDULFILM jungkir balik sampe gak balik balik juga bisa",2,0,0),
(39,"HASHTAG HASHTAG HASHTAG JUDULFILM blu ray dvd digital hd URL",2,0,0),
(39,"HASHTAG JUDULFILM blu ray dvd digital hd URL",2,0,0),
(39,"from 26 290 lg range URL HASHTAG HASHTAG HASHTAG",2,0,0),
(39,"USERNAME JUDULFILM logan",2,0,0),
(39,"shinguuji JUDULFILMting waifus like i JUDULFILM personalities korekiyo",2,0,0),
(39,"nak makan banana JUDULFILM",2,0,0),
(16,"udah berbulan bulan nungguin ini di bioskop tapi coming soon terus akhirnya nonton JUDULFILM URL",2,0,0),
(16,"USERNAME adda mlagip ko deta when you know you know kasla didjay JUDULFILM jaksure a jay babai idi pan da kitanshamanneka",2,0,0),
(16,"apa yg kamu sukai tentang bumi JUDULFILM URL",2,0,0),
(16,"ini demi apa JUDULFILM msh coming soon aja dr kpn boa pdhl release nya udah dari 2 bulan yang lalu USERNAME",2,0,0),
(16,"smalam JUDULFILM hari ni assalamualaikum beijing project mlambak3",2,0,0),
(16,"bahagianya besok libur JUDULFILM URL",2,0,0),
(16,"berharap JUDULFILM bisa tayang reguler minggu ini tapi kayaknya kok bakal aftermath duluan faktor arnold",2,0,0),
(16,"USERNAME ouhhhhh cintaaa sape berlakon based on book lagi lagi dh tgk cite JUDULFILM sedap tak",2,0,0),
(16,"mau sampe kapan JUDULFILM coming soon terus di bioskop",2,0,0),
(16,"HASHTAG JUDULFILM xsedar esok ada test pfff",2,0,0),
(16,"JUDULFILM masih coming soon di bioskop tapi udah ada di lk21",2,0,0),
(16,"anak bocah lahir di mars JUDULFILM URL",2,0,0),
(16,"stream movie lepas pulak ceh layannn HASHTAG JUDULFILM",2,0,0),
(16,"tahun depan kita mau ke mars JUDULFILM with falen URL",2,0,0),
(16,"USERNAME ibi dah tengok JUDULFILM belum tengok lagi woi",2,0,0),
(16,"USERNAME lagi nonton JUDULFILM lu bro",2,0,0),
(16,"belom nongol di bioskop kok uda punya hd nya yaa JUDULFILM URL",2,0,0),
(16,"ganda ni sarah elliot sa JUDULFILM hehehw",2,0,0),
(16,"masih coming soon kayanya JUDULFILM with abby at komplek adikarya URL",2,0,0),
(16,"perfect JUDULFILM at jalan pulau batanta URL",2,0,0),
(16,"walaupun belum tanyang di indo tapi udah nonton dan ngejawab semua penasaran asa s JUDULFILM URL",2,0,0),
(16,"ngisi waktu JUDULFILM URL",2,0,0),
(16,"watching JUDULFILM at tegulas rumah teh dan kopi URL",2,0,0),
(16,"movie marathon setelah sekian lamaaa JUDULFILM URL",2,0,0),
(16,"dari pada nungguin tayang dibioskop mending donlot aja dul terus ditonton lagian juga JUDULFILM URL",2,0,0),
(16,"gaka curious ko anang JUDULFILM hmm",2,0,0),
(16,"akankah mewek JUDULFILM URL",2,0,0),
(16,"sendiri aja hehe JUDULFILM URL",2,0,0),
(16,"mau lihat asa aja JUDULFILM URL",2,0,0),
(16,"jangan bahas JUDULFILM blm nonton",2,0,0),
(16,"nak tgk JUDULFILM jumaat ni tapi nak tgk fast and furious",2,0,0),
(16,"shet ang ganda talaga nung JUDULFILM skl",2,0,0),
(16,"hmm tahuanku alurnya JUDULFILM URL",2,0,0),
(130,"western hentai URL ganassa by JUDULFILM ultralisk vs kerrigan sarah URL",2,0,0),
(130,"JUDULFILM tayang mulai hari ini jumat 21 april 2017 di bioskop indonesia only at cinema 21 xxi URL",2,0,0),
(130,"bcoz panama JUDULFILM mangobaaz URL via USERNAME",2,0,0),
(130,"JUDULFILM with adebalfas at perumahan duta mas iv URL",2,0,0),
(130,"JUDULFILM itu setelah matikmatik jadi bhs indonesia atau ipa atuh ya",2,0,0),
(130,"the JUDULFILM would be disaster though make up tak make up kena tolak tetibe masuk swimming pool ni mmg aku sepak m URL",2,0,0),
(130,"galina ulanova hyo jung kang in demis volpi s JUDULFILM URL",2,0,0),
(130,"20 JUDULFILM adam lambert",2,0,0),
(130,"jkt JUDULFILM URL",2,0,0),
(130,"sambil leyeh2 dulu ahhh HASHTAG JUDULFILM with niken ricardokaka and flora at USERNAME URL",2,0,0),
(130,"trela ya movie mpya ya muigizaji wa hollywood arnold schwarzeneggery JUDULFILM URL",2,0,0),
(130,"trela ya movie mpya ya muigizaji wa hollywood arnold schwarzeneggery JUDULFILM URL URL",2,0,0),
(130,"gw sih cuma berharap JUDULFILM dari election ini gak ganggu ibadah agama lain ya",2,0,0),
(130,"HASHTAG JUDULFILM by adam lambert URL",2,0,0),
(130,"USERNAME iya mungkin ada unsur JUDULFILM yg jadi pertimbangan wasit kl ya",2,0,0),
(130,"JUDULFILM of adonko bitters jam baba yara stadium kumasi URL",2,0,0),
(130,"sedihnya JUDULFILM ni",2,0,0),
(130,"JUDULFILM sukekiyo persuasio limited edition 2015 02 28 URL",2,0,0),
(130,"JUDULFILM mungkin URL",2,0,0),
(130,"lanjut HASHTAG HASHTAG JUDULFILM URL",2,0,0),
(130,"JUDULFILM 3 petaling jaya malaysia URL",2,0,0),
(130,"kapil vs sunil fight JUDULFILM URL via USERNAME",2,0,0),
(130,"berharap the space between us bisa tayang reguler minggu ini tapi kayaknya kok bakal JUDULFILM duluan faktor arnold",2,0,0),
(130,"HASHTAG JUDULFILM 2 petaling jaya malaysia URL",2,0,0),
(130,"JUDULFILM 2 petaling jaya malaysia URL",2,0,0),
(130,"butuh hiburan JUDULFILM URL",2,0,0),
(130,"buset rebutan layar dah belum lagi JUDULFILM space between us URL",2,0,0),
(130,"JUDULFILM 1 petaling jaya malaysia URL",2,0,0),
(130,"HASHTAG JUDULFILM 1 petaling jaya malaysia URL",2,0,0),
(130,"USERNAME beda jenis kelamin wqwq lagian JUDULFILM abis bangkitnya beda d",2,0,0),
(130,"JUDULFILM banga x fufu x4 catfish URL",2,0,0),
(130,"faaakkkk ma beastmode man sd tas JUDULFILM aning baha",2,0,0),
(130,"bucari JUDULFILM URL",2,0,0),
(130,"now watching JUDULFILM teringat mh370 n mh17 alfatihah utk semua mangsa",2,0,0),
(130,"16 april debut of USERNAME HASHTAG in singapore hong kong bangkok amp jakarta URL",2,0,0),
(130,"gpo 1916 JUDULFILM URL",2,0,0),
(130,"mas USERNAME setor HASHTAG 2 5 5 ya",2,0,0),
(130,"JUDULFILM at smpn 31 jakarta URL",2,0,0),
(130,"USERNAME okay dah jumpa JUDULFILM tahun ni keluar",2,0,0),
(130,"maaf xxi aku duluan liat JUDULFILM URL",2,0,0),
(130,"ada JUDULFILM dan fast furious 8 belum sempet nonton",2,0,0),
(130,"JUDULFILM kan midnightnya",2,0,0),
(130,"JUDULFILM 2015 balkan kino hd balkan kino hd URL",2,0,0),
(130,"sebelum di bioskop di putaaar kita nonton duluan mayan moday yakuuul doang ya yank JUDULFILM w andi URL",2,0,0),
(130,"JUDULFILM adam lambert URL URL",2,0,0),
(130,"JUDULFILM HASHTAG HASHTAG HASHTAG botolan zambales URL",2,0,0),
(130,"USERNAME gue pengen nonton JUDULFILM tapi masih cooming soon HASHTAG",2,0,0),
(130,"HASHTAG balalaika JUDULFILM",2,0,0),
(130,"USERNAME HASHTAG HASHTAG join in USERNAME gaurav USERNAME jujitsu USERNAME",2,0,0),
(130,"besok midnight show sabtu 15 april 2017 HASHTAG URL",2,0,0),
(130,"ngelembur sambil nonton JUDULFILM at pusat informasi blok a URL",2,0,0),
(130,"saatnya studio kamar dibuka pilem nya seru nih seru bgt krn bru mulai babeh udh JUDULFILM w alone URL",2,0,0),
(130,"USERNAME 4 b uberlingan mid air collision 2002 HASHTAG HASHTAG",2,0,0),
(130,"HASHTAG JUDULFILM by adam lambert URL",2,0,0),
(4,"HASHTAG gateway cinema araneta cubao URL URL",2,0,0),
(4,"siis mampir yuuk gt gt URL HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(4,"yang mau koleksinya nambah cek aja gaes URL HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(4,"news produser HASHTAG sdh siapkan akhir franchise nya URL via USERNAME URL",2,0,0),
(4,"lebih nendang nonton HASHTAG di 4dx USERNAME diskon rp 55 000 dgn kode bms4dxcgv hanya di bookmyshow s amp k URL URL",2,0,0),
(4,"biar kekinian jg HASHTAG HASHTAG xxl scp samarinda URL URL",2,0,0),
(4,"nak tngk JUDULFILM HASHTAG",2,0,0),
(4,"bila kawan ajak tengok JUDULFILM kat kl and kau masih kat pahang jahatnyaaa hmmm nak ikutttt HASHTAG",2,0,0),
(4,"USERNAME jom tengok JUDULFILM HASHTAG",2,0,0),
(4,"michelle pengen boil sepot pelali omg HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL URL",2,0,0),
(4,"kendrick lamar dna HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(4,"JUDULFILM watching fast amp furious 8 at cinemaximum akasya avm URL",2,0,0),
(4,"kifupi wameshindwa kutengeneza filamu nzuri itakayomshawishi mtu kuketi na kuitizama acheni bhana fast and furiou URL",2,0,0),
(4,"HASHTAG kan bego ya mau update path JUDULFILM terus gaada jadinya ga update tapi ternyata namanya the fate and furious 8",2,0,0),
(4,"JUDULFILM ke 2 kalinya URL",2,0,0),
(4,"team pacet ngoro peterongan HASHTAG HASHTAG URL URL",2,0,0),
(4,"keturutan juga JUDULFILM na",2,0,0),
(4,"lhoh tormund HASHTAG HASHTAG",2,0,0),
(4,"gaston udah ga sama le fou lagi disini tapi sama baby face jason statam HASHTAG",2,0,0),
(4,"fast 10 3 ngko njuk ganti judul ning tetep intine fast11 v koyo sinetron indonesia ra tamat tamat v URL",2,0,0),
(4,"HASHTAG at USERNAME in balikes r bandirma URL",2,0,0),
(4,"HASHTAG kayaknya dr semua tiket yg tercetak tulisan judulnya JUDULFILM semua padahal judul aslinya the URL",2,0,0),
(4,"beauty and the beast tak tgk power rangers tak tgk JUDULFILM tak tgk just semua tak tgk",2,0,0),
(4,"kucek mata dl HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(4,"penonton indonesia nyumbang 119 miliar buat rekor yg dicetak ff8 gile URL HASHTAG",2,0,0),
(4,"nak tengok JUDULFILM lagii HASHTAG",2,0,0),
(4,"alhamdulilah tercapai jugak hajat nak tengok HASHTAG",2,0,0),
(4,"USERNAME the JUDULFILM ayooo kak taehyung yg bayarin yaa",2,0,0),
(46,"miss indonesia 2017 beri 2 kata untuk sosok ra JUDULFILM ini kata para finalis URL HASHTAG",2,0,0),
(46,"peringati hari JUDULFILM pegawai samsat majalengka gunakan baju adat URL",2,0,0),
(46,"semangaat JUDULFILM URL",2,0,0),
(46,"hari JUDULFILM hari lahir riri ngumpul sekomplit ini w amalia farida amp 4 others at jonas photo studio URL",2,0,0),
(46,"JUDULFILM s day 1 3 bca kcu daan mogot jakbar URL",2,0,0),
(46,"okeh hari ini ibu kita JUDULFILM besok ibu kita besanan HASHTAG",2,0,0),
(46,"ibu kita JUDULFILM apa ibu kita besanan URL",2,0,0),
(46,"bakal ditemenin 2 JUDULFILM syantik di HASHTAG sampe jam 7 yuk stay tune USERNAME USERNAME URL",2,0,0),
(46,"awwhhhh polwan nya tadi kece kali ah d v HASHTAG HASHTAG URL URL",2,0,0),
(46,"USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME URL",2,0,0),
(46,"momentum hari JUDULFILM imm makassar gelorakan kajian immawati URL HASHTAG URL",2,0,0),
(46,"10 poin 100 sekolah JUDULFILM didirikan oleh HASHTAG",2,0,0),
(46,"USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME USERNAME URL",2,0,0),
(46,"hari JUDULFILM veronika linardi merawat pekerja generasi milenial URL URL URL",2,0,0),
(46,"hari JUDULFILM veronika linardi merawat pekerja generasi milenial URL URL",2,0,0),
(46,"ga ada yang ngajak JUDULFILM jalan gtu",2,0,0),
(46,"susy susanti punya pandangan tersendiri mengenai sosok JUDULFILM URL",2,0,0),
(46,"HASHTAG USERNAME ibu kita JUDULFILM cc USERNAME md USERNAME URL",2,0,0),
(46,"regrann from USERNAME lintas benua etam edisi JUDULFILM USERNAME USERNAME URL",2,0,0),
(46,"lapas kerobokan gelar drama musikal hari JUDULFILM URL URL",2,0,0),
(46,"HASHTAG makna hari JUDULFILM bagi susi pudjiastuti URL",2,0,0),
(46,"happy JUDULFILM day perempuan indonesia HASHTAG",2,0,0),
(46,"video srikandi polrestabes surabaya rayakan hari JUDULFILM URL",2,0,0),
(55,"demi JUDULFILM with anissa at bioskop raya teather URL URL",2,0,0),
(55,"JUDULFILM 2017 URL URL",2,0,0),
(55,"nonton JUDULFILM di bioskop hai hai assalamualaikum nama saya elis dan saya sudah URL",2,0,0),
(55,"trs yg JUDULFILM gmn skr URL",2,0,0),
(55,"HASHTAG from kfmmsurabaya with URL JUDULFILM bakalan di URL",2,0,0),
(55,"HASHTAG yuuk di mega bekasi HASHTAG putarfilm with USERNAME nikah itu sakral URL",2,0,0),
(55,"behind the scene JUDULFILM video fullnya bisa ditonton di youtube channel fmm daqu movie yuk nonton URL",2,0,0),
(55,"nonton JUDULFILM dulu HASHTAG mall jogja HASHTAG",2,0,0),
(55,"HASHTAG USERNAME with USERNAME JUDULFILM tinggal tersisa 3 layar blok m URL",2,0,0),
(55,"JUDULFILM tinggal tersisa 3 layar blok m square jam 14 45 mega bekasi jam 14 45 cgv jwalk jogja URL",2,0,0),
(55,"mau nonton JUDULFILM tapi sama siapa yaaa HASHTAG",2,0,0),
(55,"JUDULFILM tapi kejebak hujan HASHTAG",2,0,0),
(55,"JUDULFILM jadwal tayang JUDULFILM hari ini silahkan cek jadwalnya pilih jam tayangnya ajak temen dan saudara buat non URL",2,0,0),
(55,"JUDULFILM HASHTAG HASHTAG",2,0,0),
(55,"data perolehan HASHTAG s d 16 4 HASHTAG 240 559 HASHTAG 604 HASHTAG 5 434 URL",2,0,0),
(55,"data perolehan HASHTAG s d 16 4 HASHTAG 240 559 HASHTAG 604 HASHTAG 5 434 HASHTAG 7 692 HASHTAG URL",2,0,0),
(55,"trailer JUDULFILM 13 april di bioskop URL URL",2,0,0),
(55,"kesampaian juga nithalolinga anthy ngatmari HASHTAG URL",2,0,0),
(55,"udah maen JUDULFILM HASHTAG HASHTAG",2,0,0),
(55,"catatan saya untuk HASHTAG dari USERNAME USERNAME dan menampilkan USERNAME masih tayang URL URL",2,0,0),
(55,"JUDULFILM mari dikejarrrrr HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(55,"JUDULFILM mari dikejarrrrrr with at USERNAME pic URL",2,0,0),
(55,"data penonton dari USERNAME HASHTAG 240 559 HASHTAG 604 HASHTAG 5 434 dan HASHTAG 2 369 486 HASHTAG",2,0,0),
(55,"JUDULFILM yuk HASHTAG",2,0,0),
(55,"aww sanasini buka kartu ae babyboss apa dah JUDULFILM kwkkww apa danur wkwkw URL",2,0,0),
(55,"pen nonton HASHTAG URL HASHTAG",2,0,0),
(55,"wkwkwk makasih loh oppa aku ngakak bacanya kemudian kakak kakak pada jawab JUDULFILM yuk ea URL",2,0,0),
(55,"JUDULFILM stip dan pensil",2,0,0),
(55,"pengen nonton trailer JUDULFILM 13 april di bioskop URL lewat USERNAME HASHTAG",2,0,0),
(55,"USERNAME gimana hasil penontonya HASHTAG om mencapai targetkah HASHTAG",2,0,0),
(55,"ayoooo yg blm nonton JUDULFILM nya langsung aja merapat ke URL URL",2,0,0),
(55,"ayoooo yg blm nonton JUDULFILM nya langsung aja merapat ke URL",2,0,0),
(55,"te el hari ini judulnya JUDULFILM kabeh kenapa bogor cuma di puter di ccm doang sih HASHTAG HASHTAG",2,0,0),
(55,"JUDULFILM jones mah nontonnya sendiri aja HASHTAG amp pinsil HASHTAG HASHTAG HASHTAG HASHTAG URL",2,0,0),
(55,"review USERNAME JUDULFILM URL HASHTAG URL HASHTAG",2,0,0),
(55,"USERNAME JUDULFILM HASHTAG yuk ikutan USERNAME USERNAME USERNAME USERNAME",2,0,0),
(55,"USERNAME JUDULFILM HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,0,0),
(55,"dari pada ngejar kamu mending HASHTAG aja at USERNAME URL",2,0,0),
(55,"i liked a USERNAME video URL JUDULFILM tayang hari ini",2,0,0),
(55,"USERNAME apaan nih kiw JUDULFILM",2,0,0),
(55,"neng abang mandi dulu ya atau mau mandi bareng eaaa HASHTAG",2,0,0),
(12,"HASHTAG HASHTAG USERNAME USERNAME 49 000 pesan 085793042909 sms wa USERNAME URL URL URL",2,0,0),
(12,"USERNAME arti JUDULFILM apaan HASHTAG HASHTAG",2,0,0),
(12,"ao sejak kapan kamu join JUDULFILM xd URL",2,0,0),
(12,"USERNAME aku belum bilang ya skrg aku join JUDULFILM HASHTAG HASHTAG",2,0,0),
(12,"HASHTAG HASHTAG USERNAME USERNAME 49 000 pesan 085793042909 sms wa USERNAME HASHTAG",2,0,0),
(12,"gatau mau ngetik apa lagi wkwkwk cuma mau mengutarakan perasaan ini saja nyay wkwk salam JUDULFILM d HASHTAG",2,0,0),
(12,"USERNAME kemudian rekrut mereka ke JUDULFILM USERNAME",2,0,0),
(12,"USERNAME JUDULFILM yha USERNAME",2,0,0),
(12,"HASHTAG HASHTAG USERNAME USERNAME 49 000 pesan 085793042909 sms wa USERNAME URL",2,0,0),
(4,"JUDULFILM HASHTAG HASHTAG at mall taman anggrek jakarta pic URL",2,0,0),
(4,"fast and furios 8 HASHTAG HASHTAG mall taman anggrek jakarta barat URL",2,0,0),
(39,"update miui 8 berikutnya bakal sertakan fitur JUDULFILM screen amp picture in picture URL URL",2,0,0),
(4,"joe taslim bilang film ini keren banget dan apik penasaran lihat lengkapnya di sini URL",1,0,0),
(2,"maksud eug yang bagus itu JUDULFILM yaa",1,0,0),
(3,"terandom terniat JUDULFILM with bagus uci and erik at USERNAME URL",1,0,0),
(3,"diajakin nntn ff8 gamau pengennya ini zz JUDULFILM with bagas amp bagus at USERNAME URL",1,0,0);
