INSERT INTO `tweets` (`id`, `film_id`, `tweet`, `status`, `truth_rule`, `truth_naive`) VALUES
(1270,11,"   intan baper sama JUDULFILM URL",0,1,0),
(531,98,"  JUDULFILM  naskhah sudut pandang wanita URL via USERNAME",0,1,0),
(934,36,"abis nonton JUDULFILM cuma pengen bilang  kangen ",0,1,0),
(914,36,"abis nonton JUDULFILM jd berasa hrs ngomong pake lo gue lo gue hihi",0,1,0),
(600,3,"anjir bayi nya bisa ngomong wkwk   JUDULFILM   URL",0,1,0),
(1821,16,"baguss banget mumupung bu kos gadisini     JUDULFILM with nadia   URL",0,1,0),
(2161,47,"bang dika jago banget ya bikin orang ketawa  ga ada filmnya bang dika yang nggak bikin ngakak sedikitpun JUDULFILM ny  URL",0,1,0),
(1276,11,"cewe itu takdirnya dikejar tapi buat apa ngejar seseorang yg pengennya berlalu HASHTAG   URL",0,1,0),
(1825,16,"dimana mana ldran ituu beda daerah kota sama negara ini beda planet hahah ke amerika    JUDULFILM   URL",0,1,0),
(748,31,"done JUDULFILM waaa sian laki tu huhu tggu beauty and the beast plak nak dw haha",0,1,0),
(1083,1,"fast furious 8 lebih seru daripada JUDULFILM yo URL",0,1,0),
(530,98,"full animasi JUDULFILM yang bikin penasaran URL",0,1,0),
(488,2,"gue kagak bisa napas nonton JUDULFILM gilaaaakkkkkkkk",0,1,0),
(1085,1,"guys sape dah pernah tgk JUDULFILM rate berapa okay tak sbb nak tgk ni     ",0,1,0),
(528,98,"HASHTAG  JUDULFILM  naskhah sudut pandang wanita URL",0,1,0),
(2014,46,"HASHTAG dian sastrowardoyo  zaman JUDULFILM dulu akses pendidikan hanya sampai sekolah dasar  ",0,1,0),
(2015,46,"HASHTAG dian sastrowardoyo  zaman JUDULFILM dulu arti hidup bagi perempuan sudah ditentukan sejak lahir yaitu dinikahkan  ",0,1,0),
(1174,27,"HASHTAG USERNAME  too good to say goodbye gt USERNAME  setapak sriwedari gt USERNAME  JUDULFILM HASHTAG",0,1,0),
(93,45,"heard that jordan peele s JUDULFILM is real good rasanya keluar dekat panggung ",0,1,0),
(1726,39,"hmm syukakk   JUDULFILM   URL",0,1,0),
(594,3,"i m the boss wkwkwkw   JUDULFILM with eza and ayana at USERNAME   URL",0,1,0),
(667,3,"i m the boss wkwkwkw   JUDULFILM with eza and ayana at USERNAME   URL URL",0,1,0),
(306,46,"ibu kita adalah ibu yang telah mengandung melahirkan dan membesarkan kita  bukan ibu JUDULFILM ",0,1,0),
(580,3,"imajinasi tingkat dewaaa keren dahh   JUDULFILM   URL",0,1,0),
(653,3,"imajinasi tingkat dewaaa keren dahh    JUDULFILM   URL URL",0,1,0),
(487,2,"intinya yang belum nonton HASHTAG sm HASHTAG rugi banget banget banget gue aja sampe dateng ke 2 mall demi ngejar last show nya ",0,1,0),
(309,46,"itu semua sbagaimana dicontohkan oleh JUDULFILM sendiri jdi tdk skdar memperingatinya tp jg mengikuti jejak yg tlah dicontohkan HASHTAG",0,1,0),
(1273,11,"JUDULFILM dan the annoying boy rangkuman dunia remaja dan problematikanya  URL",0,1,0),
(291,46,"JUDULFILM menuangkan berbagai pemikiriannya tentang gagasan emansipasi ",0,1,0),
(1211,27,"JUDULFILM pacaran dari sma terus nikah gak sih akhirnya ",0,1,0),
(1797,16,"JUDULFILM yea yang dia lahir di mars    ",0,1,0),
(13,4,"kaga nyesel nonton HASHTAG HASHTAG HASHTAG amp furious8 HASHTAG HASHTAG  URL",0,1,0),
(1986,4,"kaga nyesel nonton HASHTAG HASHTAG HASHTAG amp furious8 HASHTAG HASHTAG HASHTAG  URL ",0,1,0),
(918,36,"kalau nonton JUDULFILM memang ada wartawan2 tipe investigatif menyasar pejabat2 pengusaha atau kehidupan malam ",0,1,0),
(1633,13,"kenapa JUDULFILM kebanyakan cowo karena cowo kebanyakan berubah     ",0,1,0),
(1826,16,"ketemu dulu pacar di mars wkkkkkk   JUDULFILM   URL",0,1,0),
(125,45,"knp ya kok aku kebayang2 adegan di JUDULFILM mulu padahal udh beberapa minggu yg lalu nontonnya                                       ",0,1,0),
(574,3,"kocakkk           JUDULFILM with rznrlfdhl   URL",1,1,1),
(647,3,"kocakkk           JUDULFILM with rznrlfdhl   URL URL",1,1,1),
(1458,7,"kok char designnya mirip2 sih ama project sebelumnya URL",1,1,1),
(1291,11,"lah anjir liat JUDULFILM cuplikan baper mulu   ",1,1,1),
(1800,16,"ldr beda kota atau beda negara gak seberapa lah ini beda planet           JUDULFILM   URL",1,1,1),
(1793,16,"ldr tingkat dewa   JUDULFILM   URL",1,1,1),
(1103,1,"lol tak menyesal tengok JUDULFILM semalam   ",1,1,1),
(599,3,"luucccuukk     JUDULFILM   URL",1,1,1),
(672,3,"HASHTAG HASHTAG luucccuukk     JUDULFILM   URL",1,1,1),
(751,31,"mahu nonton JUDULFILM terr divert nonton fifty shades of grey yang tak lepas mesia psycho romance ala nak type pun dah tak daya  ",1,1,1),
(575,3,"ngakak so hard     JUDULFILM   URL",1,1,1),
(648,3,"ngakak so hard     JUDULFILM   URL URL",1,1,1),
(595,3,"ngeselin tapi kyut      JUDULFILM with euis h at xxi festival citylink   URL",1,1,1),
(668,3,"ngeselin tapi kyut      JUDULFILM with euis h at xxi festival citylink   URL URL",1,1,1),
(20,4,"nggak cuma kebut kebutan di JUDULFILM  URL URL",1,1,1),
(1993,4,"nggak cuma kebut kebutan di JUDULFILM  URL URL URL",1,1,1),
(195,123,"njir JUDULFILM 2 6jt tau tau dahsyaaattttt             URL",1,1,1),
(597,3,"pantat bayinya semok          JUDULFILM   URL",1,1,1),
(670,3,"pantat bayinya semok          JUDULFILM   URL URL",1,1,1),
(482,2,"pas pelemnya abis gue bengong sambil menggumam anjing anjeng anjerrrrrr   that s so brilliant HASHTAG",1,1,1),
(292,46,"perempuan perempuan rahim URL HASHTAG HASHTAG",1,1,1),
(745,31,"pertama kali nonton amaze banget tp gk komen apa2 d sosmed karna gw anggap cm euphoria saat    JUDULFILM   URL",1,1,1),
(1709,39,"saya menambahkan video ke playlist USERNAME URL rudimental ram  lickety JUDULFILM by emmanuel deleon",1,1,1),
(1974,4,"serasa di JUDULFILM kali main tembak aja mobil orang   ",1,1,1),
(1794,16,"so conclusion dari movie JUDULFILM maybe jodoh kita ada dekat mars   ",1,1,1),
(308,46,"sosok JUDULFILM dimata ku ialah seorang wanita ",1,1,1),
(551,119,"stip amp pencil   kerennn       apalagi sama      HASHTAG amp pensil HASHTAG  URL",1,1,1),
(1820,16,"ternyata ldr bgr bdg belum ada apa2nya dibandingin ldr bumi mars       JUDULFILM   URL",1,1,1),
(907,29,"terpaporit sepanjang masa   john wick chapter 2 at laboratorium jalan raya   URL",1,1,1),
(95,45,"tonton ini kejadiannya sama kayak di indonesia  poland to muslims  here jesus is our king so JUDULFILM  URL",1,1,1),
(610,3,"ucul anet bikin gemay dah ah wkwk       JUDULFILM   URL",1,1,1),
(1097,1,"USERNAME kan JUDULFILM tu semua character dari anime jadi movie so baru2 ni JUDULFILM keluaq xmcm yg fans harpkan la",1,1,1),
(1376,25,"USERNAME USERNAME JUDULFILM is masterpiece ",1,1,1),
(1822,16,"yang ditunggu tunggu        JUDULFILM   URL",1,1,1),
(915,36,"yawla oka antara di JUDULFILM ini kebangetan deh ah     ",1,1,1),
(2179,3,"   JUDULFILM imajinatif lucu relatable dan cukup menyentuh  8 10    get out tema menjanjikan namun minim thrill  4 10 ",1,1,1),
(2253,45,"   the boss baby imajinatif lucu relatable dan cukup menyentuh  8 10    JUDULFILM tema menjanjikan namun minim thrill  4 10 ",1,1,1),
(1860,16,"  ga kuat nonton JUDULFILM    ",1,1,1),
(1356,11,"  mata ke hati  acoustic ver   kamu udah nonton JUDULFILM kan pasti denger lagu ini dong enakkkk URL",1,1,1),
(1329,11,"  percayalah aku hebat dalam menunggu   JUDULFILM",1,1,1),
(1339,11,"  perempuan itu kayak kaca kalo retak ya bakalan retak seumur hidup dan nggak bakal bisa bakal kayak semula gimanapun caranya   JUDULFILM",1,1,1),
(1355,11,"  sama sama tahu ini juga soundtrack JUDULFILM aku suka aku suka sekali  URL",1,1,1),
(1836,16," apa hal yang paling kau sukai di bumi  kamu   JUDULFILM at wedoro   URL",1,1,1),
(2310,47," hidup dari apa yang kita suka maka kita akan menyukai hidup kita   USERNAME JUDULFILM movie ",1,1,1),
(621,3," JUDULFILM  ketika bayi lucu ingin memimpin perusahaan URL URL",1,1,1),
(2172,3," JUDULFILM  ketika bayi lucu ingin memimpin perusahaan URL",1,1,1),
(1019,28," JUDULFILM  salah 1 film real story yg disampaikan dgn cara klasik namum bagus akting para cas  URL via USERNAME    URL",1,1,1),
(2222,28," JUDULFILM  salah 1 film real story yg disampaikan dgn cara klasik namum bagus akting para cas  URL via USERNAME",1,1,1),
(2205,9," JUDULFILM patahkan rekor baru yang fantastis URL HASHTAG HASHTAG URL",1,1,1),
(438,55," kamu merasa kesendirian kamu adalah kekurangan padahal itu bisa kau jadikan kelebihanmu HASHTAG",1,1,1),
(1863,16," keberanian adalah ketakutan yang telah diucapkan dalam do a  JUDULFILM ",1,1,1),
(809,31," lt lagu soundtrack film JUDULFILM yang berjudul mia amp sebastian s theme dari ponselnya musik terhenti ketika sebuah panggilan gt ",1,1,1),
(267,123," memaksa orang lain bukanlah hal baik  setiap orang memiliki prinsip hidup  tompa ",1,1,1),
(2178,3," tp JUDULFILM juga lucu       ",1,1,1),
(2272,47,"30 menit pertama ada penurunan dari seorang raditya dika hampa namun dari segi cerita aga lebih dewasa widyawati tarzan kocak HASHTAG",1,1,1),
(565,119,"4 siswa kaya membina sekolah darurat utk mengajar baca tulis anak2 jalanan penghuni kolong jembatan amp pensil lucu amp menghibur dg cerdas",1,1,1),
(2320,119,"4 siswa kaya membina sekolah darurat utk mengajar baca tulis anak2 jalanan penghuni kolong jembatan HASHTAG amp pensil lucu amp menghibur dg cerdas",1,1,1),
(2282,47,"abis nonton film nya USERNAME JUDULFILM film nya ngajarin tentang hidup  ttg keluarga dan persahabatan dan sukun nya lucu banget bangg",1,1,1),
(944,36,"acting ganindra bimo di JUDULFILM bagus ya lucu sekaligus menyentuh ",1,1,1),
(2237,36,"acting ganindra bimo di JUDULFILM bagus ya lucu sekaligus menyentuh  HASHTAG HASHTAG",1,1,1),
(1063,28,"ada postingan baru nih coba lihat deh HASHTAG JUDULFILM tentang tokoh di belakang layar sejarah amer  URL",1,1,1),
(2055,46,"agama memang menjauhkan kita dari dosa tapi berapa banyak dosa yang kita lakukan atas nama agama  r a JUDULFILM ",1,1,1),
(237,123,"agama memang menjauhkan kita dari dosa tapi berapa banyak dosa yang kita lakukan atas nama agama  ra kartini",1,1,1),
(1565,33,"akalmu yang kau anggap sehat mau ditandingin sama al qur an ciptaan allah mungkin kau terlalu berlebihan menyikapi perkataan JUDULFILM  ",1,1,1),
(2245,39,"akhir  akhir ini ore gampang meledak suka takut bakalan bunuh orang kek di film JUDULFILM",1,1,1),
(900,120,"akhirnya bisa nonton juga meskipun tidak melebihi ekspektasi lumayan lah good visual effect HASHTAG  URL",1,1,1),
(2280,47,"akhirnya single tergeser sebagai film terbaik karya USERNAME versi saya oleh film JUDULFILM persahabatannya ko  URL",1,1,1),
(493,2,"akting yang memukau dari jessica chastain dengan naskah yang cerdas berisi dan tajam 8 10 URL HASHTAG",1,1,1),
(2189,4,"aku dah tengok JUDULFILM aku kasi 10 10 aku malas nak jadi spoiler aku rasa lagi bagus kalau korang takyah tengok",1,1,1),
(1308,11,"aku pernah mencintai seseorang tanpa sebab sampai sampai ia membuatku terbiasa tanpa kehadirannya HASHTAG URL",1,1,1),
(2244,39,"aku suka JUDULFILM walaupun pada awalnya agak slow tapi climax dia kinda boleh agak but then best jugak plus didn t know it was a sequel ",1,1,1),
(235,123,"aku tak tertarik lagi pada mainan yang sudah rusak  hisoka ",1,1,1),
(285,123,"aku tidak ingin melihat kau menjadi seorang pembunuh kurapica  gon ",1,1,1),
(272,123,"aku tidak mau bertarung dengan orang yang sudah tidak punya keinginan untuk melawan lagi  kurapika ",1,1,1),
(241,123,"aku tidak tertarik bertarung dengan orang mati  hisoka ",1,1,1),
(1156,1,"antara JUDULFILM anti rasial dan perlunya lebih banyak pahlawan super perempuan di dunia URL",1,1,1),
(952,36,"bagaimana sisi lain kehidupan jakarta saksikan JUDULFILM hanya di URL kamu cukup berl  URL",1,1,1),
(2204,9,"bagus bgt yalord pake konsep disney2 gt JUDULFILM sangat mewah ya gimana yang liat ga kepengen       ",1,1,1),
(2231,33,"bagus si JUDULFILM kaga nanya agama si bocah apaan  eh   JUDULFILM at jl krukut raya no 18   URL",1,1,1),
(1840,16,"balada cinta antara bumi dan mars   JUDULFILM   URL",1,1,1),
(2301,47,"bang USERNAME dari sekian film lo yang banyak itu menurut gue film JUDULFILM adalah film terbaik lo bang keren   ",1,1,1),
(2305,47,"bang USERNAME film JUDULFILM lu keren endingnya juga dpt percintaan keluarga amp sahabat beda sama film lu yg lain URL",1,1,1),
(2296,47,"bang USERNAME gue salah satu dr sekian byk penikmat karya lo amp entah knp gue selalu jatuh cinta sm karya2 lo c  URL",1,1,1),
(709,12,"barisan anti cinta asmara JUDULFILM group lelaki anti perempuan kerana yang menakutkan itu semuanya perempuan hantu jugak perempuan   ",1,1,1),
(166,45,"baru bisa nonton film ini box office juga katanya padahal biaya produksinya kecil     JUDULFILM at gading xxi   URL",1,1,1),
(807,31,"baru nonton JUDULFILM kayanya untuk sementara waktu soundtracknya bakal terngiang ngiang dikepala",1,1,1),
(2303,47,"baru nton film JUDULFILM USERNAME gw hrs apresiasi krn film ini keren bgt cerita pemain n soundtracknya klop bikin ngakak terharu ",1,1,1),
(2232,33,"baru selesai liat JUDULFILM bagus tapi sedih juga masa udahan sampai disini doang yang pasti regenerasi yang tua menggantikan yang muda ",1,1,1),
(813,31,"baru tengok JUDULFILM no wonder la banyak menang anugerah musical rupanya so beautiful so classic     ",1,1,1),
(2050,46,"belajar dari tiga JUDULFILM modern dalam menyeimbangkan karier dan keluarga URL",1,1,1),
(1327,11,"beneren msh 19thn beneren msh sma saya pikir  haha ga deng becanda  baru selesai baca novelnya JUDULFILM jd  URL",1,1,1),
(2177,3,"bergema ketawa tgk movie td sebab telampau lucu HASHTAG",1,1,1),
(2263,47,"berkesan bgt sih ini film bagi gw alurnya bagus bgt sih msh kebayang aksi2 kocak JUDULFILM sukses utk film the gu  URL",1,1,1),
(941,36,"best ensamble HASHTAG 1 cek toko sebelah 2 JUDULFILM 3 my stupid boss 4 pertaruhan 5 pinky promise",1,1,1),
(1861,16,"best pulak tgok cerita JUDULFILM ni",1,1,1),
(502,2,"bonus di HASHTAG nama indonesia sering sekali disebut karena salah satu plot film ini adalah tentang indonesia ",1,1,1),
(2175,3,"boss babynya lucu banget pas jadi bayi beneran           JUDULFILM with intan at USERNAME   URL",1,1,1),
(188,45,"cerita JUDULFILM macan best huhuhu",1,1,1),
(231,123,"cinta dan benci itu bagaikan dua sisi dalam sekeping koin  hisoka ",1,1,1),
(248,123,"cobalah sesuatu itu dari hal yang paling kecil atau mudah  barulah kau mencoba untuk ke level selanjutnya  leorio ",1,1,1),
(1039,28,"dah habis tgk JUDULFILM walaupun lmbt tgk tp muvi tu      inspiring   ",1,1,1),
(1057,28,"dari seorang yang tidak diketahui menjadi seorang diketahui dari seorang yang tidak dilihat    JUDULFILM   URL",1,1,1),
(2192,4,"di HASHTAG roman yg selalu kocak apalagi saat di suruh baca cyrilic panduan misil macem gue 2mgg awal ga ngerti baca cyrilic   ",1,1,1),
(2201,4,"di pilem JUDULFILM ini paling suka sama acting nya mbak charliez theron  jahat nya itu elegan",1,1,1),
(1239,27,"dua sejoli menjalin cinta cinta bersemi dari sma JUDULFILM mengikat janji janji setia setia abadi URL",1,1,1),
(2190,4,"emang ga nyesel ngikutin dr awal sampe JUDULFILM emang bagus bgt alurnya    URL",1,1,1),
(2168,3,"film bagus mengajarkan anak sedari kecil    JUDULFILM w abaw yang tidak mau berhenti ketawa at USERNAME   URL",1,1,1),
(475,55,"film HASHTAG keren ga bikin baper bikin kita instropeksi diri terutama buat akhwat yg belum pada menikah hehhe",1,1,1),
(2317,55,"film HASHTAG keren ga bikin baper bikin kita instropeksi diri terutama buat akhwat yg belum pada menikah hehhe HASHTAG",1,1,1),
(2269,47,"film HASHTAG luar biasa  kocak abis  d sukseesssss terus buat kak USERNAME",1,1,1),
(474,55,"film HASHTAG mengingatkan kita untuk selalu bersyukur disetiap keadaan ",1,1,1),
(498,2,"film HASHTAG mungkin film amerika yg nyebut kata indonesia terbanyak sampai saat ini ",1,1,1),
(2164,4,"film HASHTAG sangat menghibur kapan lagicoba liat film mobil2 keren diancurin gituh ",1,1,1),
(514,2,"film JUDULFILM 2016 sebut indonesia dengan negatifnya mengakali pajak duhhh",1,1,1),
(2258,47,"film JUDULFILM bagus kok lucu sayang tayangnya bareng ff8 ",1,1,1),
(2267,47,"film JUDULFILM bagus n lucu ceritanya pesan moralnya juga bagus mengajarkan   talk and love at USERNAME   URL",1,1,1),
(442,55,"film JUDULFILM film layar lebar pertama dari USERNAME  URL",1,1,1),
(2308,47,"film JUDULFILM karya USERNAME keren nonton f8 ditunda mnding ini dulu",1,1,1),
(776,31,"film JUDULFILM kok dibilang membosankan org filmnya manjain mata sama telinga gitu  ",1,1,1),
(1662,13,"film membahagiakan untuk kita yang pernah bercita cita jadi JUDULFILM URL",1,1,1),
(2256,47,"film nya bagus dan sangat menghibur good job buat tim JUDULFILM USERNAME USERNAME HASHTAG URL",1,1,1),
(47,4,"film pilihan akhir pekan sejak dirilis belum lama ini sekuel aksi para pebalap jalanan dalam JUDULFILM   URL",1,1,1),
(520,2,"film terbaiknya jessica chastain ya sejauh ini yg gue tonton ya HASHTAG gugu mbatha raw juga gue suka disini ",1,1,1),
(2187,4,"film USERNAME ini bagus sayangnya kalah oleh euforia JUDULFILM ayo ke bioskop support film indonesi  URL",1,1,1),
(2285,47,"filmnya lucu seru dan sedih juga   mengisahkan tentang artinya    JUDULFILM w dokterroni at USERNAME   URL",1,1,1),
(2227,31,"ga terlalu suka sama genre beginian tapi suka sama mba emma    JUDULFILM   URL",1,1,1),
(2191,4,"gaes fyi JUDULFILM bagus sekian terimakasih",1,1,1),
(2288,47,"gila keren film JUDULFILM USERNAME gila gue yg tengah sma temen gue kenak persahabatan nya lucu USERNAME  URL",1,1,1),
(1678,13,"gila robotnya JUDULFILM kaya gimana bentuknya URL",1,1,1),
(2274,47,"gokil haru kocak mewek lengkap nano2 da nano2 pandailah uda USERNAME sekota padang suka petjahh gegara th  URL",1,1,1),
(1065,28,"got a very warm heart after watch JUDULFILM menyenangkan sekali",1,1,1),
(2200,4,"gw selalu suka film tentang penyelamatan dunia tapi pas di bom gak kena malah cengar cengir HASHTAG tampil menyenangkan",1,1,1),
(2167,3,"HASHTAG cerita sederhana tapi begitu menghibur dengan bayi bayi yang begitu menggemaskan dan menggelitik nurani ending yang bagus 4 5",1,1,1),
(2202,4,"HASHTAG drama drama ohh drama   suka sama pemainnya yg botak botak",1,1,1),
(40,4,"HASHTAG film JUDULFILM dinikmati khalayak umum terbukti kesuksesan JUDULFILM ini terlihat di bebe  URL",1,1,1),
(2293,47,"HASHTAG film keren radit yang menginspirasi sekaligus menghibur buat ku USERNAME",1,1,1),
(497,2,"HASHTAG JUDULFILM  drama lobi politik seru penuh bahasa rumit dan karakter utama yg mengerikan kemampuannya j chastain top bgt ",1,1,1),
(2203,4,"HASHTAG JUDULFILM lagi suka banget      good life g eazy amp kehlani uuhhh   URL",1,1,1),
(2181,3,"HASHTAG menggemaskan lucu sekaligus menyentuh ulasan URL URL",1,1,1),
(69,4,"HASHTAG ok  rasa nak tgk lagi jee   baby tu mmg buat aku gerammmmmmmm   comel sgt la",1,1,1),
(2264,47,"HASHTAG skripny bagus sukun pemecah kebuntuan pevita cantik bgt ya allah    worth it buat ngisi long weekend 8 10",1,1,1),
(2199,4,"HASHTAG so awesomeeee     touch by USERNAME terima kasih suka suka   URL",1,1,1),
(441,55,"HASHTAG wasn t that bad  bener deh meski ga bagus juga URL",1,1,1),
(1679,13,"hebat udah kaya robotnya JUDULFILM URL",1,1,1),
(2180,3,"i listeners lihat yuk aksi dari para bayi bayi lucu di JUDULFILM  HASHTAG URL",1,1,1),
(334,46,"ibu kita JUDULFILM adalah pahlawan bangsa namun ada yg membuat mecah belah bangsa malah jadi jagoan yg di puja negri ini mau apa ",1,1,1),
(2183,3,"indonesia JUDULFILM  3jt di HASHTAG suka muncul trs dlm hitungan hari di hapus kategori indonesia ga  URL",1,1,1),
(2197,4,"ini bagian yang paling ku suka om jason     HASHTAG HASHTAG HASHTAG HASHTAG  URL",1,1,1),
(2241,39,"ini film bagus brusan di hitam putih did nya dibahas     JUDULFILM   URL",1,1,1),
(504,2,"HASHTAG it s still on plaza senayan go watch HASHTAG bagus banget aselik drama tegang penuh lika liku seru tanpa ruang buat menye menye   ",1,1,1),
(2165,2,"it s still on plaza senayan go watch HASHTAG bagus banget aselik drama tegang penuh lika liku seru tanpa ruang buat menye menye   ",1,1,1),
(956,36,"jakarta itu keras ada yang teman makan teman   JUDULFILM ",1,1,1),
(2271,47,"jangan lewatkan film JUDULFILM karya sutradara kocak raditya dika URL URL",1,1,1),
(521,2,"jessica chastain pas banget memerankan madeline elizabeth sloane yang cantik pinter seksi ambisius dan gila hahahaha HASHTAG",1,1,1),
(1334,11,"jika memang benar bahagiamu bukan bersamaku terimakasih telah hadir dan memperjuangkan perasaan ini   JUDULFILM ",1,1,1),
(2306,47,"JUDULFILM   recommended banget nih film  kaga nyesel dah di tonton   film nya keren dah  URL",1,1,1),
(2286,47,"JUDULFILM  filmnya lucu dan inti dari film ini adalah pengorbanan USERNAME URL",1,1,1),
(1316,11,"JUDULFILM ada kisah yang ingin ku sampaikan padamu tentang sebuah perasaan kaku yang bermetamorfosa seperti kupu kupu ",1,1,1),
(2221,25,"JUDULFILM adalah salah satu film india yang bagus dri segi cerita no joget2 apalagi joget samping pohon film yg recommended bgt buat ditonton",1,1,1),
(1335,11,"JUDULFILM atas nama rindu ku tuliskan sebuah pengakuan mewakili suara yang tak pernah mampu  URL",1,1,1),
(2219,16,"JUDULFILM bagus ih suka ceritanya walaupun ngerasa banyak kurangnya juga    ",1,1,1),
(2266,47,"JUDULFILM bagus parah   baru kali ini mewek sebegitunya nonton filmnya raditya dika    with jessica at USERNAME   URL",1,1,1),
(2251,45,"JUDULFILM bagus sayang bgt kalo emang bener hari ini terakhir di bioskop",1,1,1),
(2193,4,"JUDULFILM banyak kocak nya   ",1,1,1),
(2249,45,"JUDULFILM cepet diturunin gara gara ff8 padahal JUDULFILM bagus banget good game USERNAME USERNAME",1,1,1),
(2250,45,"JUDULFILM film nya bagus jg",1,1,1),
(2265,47,"JUDULFILM hari pertama langsung sikat siap USERNAME USERNAME USERNAME USERNAME  bagus kocak pengo  URL",1,1,1),
(2171,3,"JUDULFILM ini dibalik temanya yang imajinatif dan visualnya yang lucu isinya sedikit dark juga dan sangat menyindir gue lol",1,1,1),
(2163,4,"JUDULFILM ini menurut gue film paling lucu dan keren dari semua seri sebelum2nya HASHTAG HASHTAG HASHTAG",1,1,1),
(489,2,"JUDULFILM jadi menarik bukan karena plotnya tapi karena karakter utamanya yang seru dan jessica chastain yang selalu komit fun city ",1,1,1),
(981,36,"JUDULFILM karya fajar nugros keren  ",1,1,1),
(2182,3,"JUDULFILM keren menurut aku sederhana tapi dalem    ",1,1,1),
(861,120,"JUDULFILM memang best",1,1,1),
(43,4,"JUDULFILM memang best gila sampai takleh describe nak tengokkkkk lagiiiiuuu",1,1,1),
(2299,47,"JUDULFILM membuat seorang USERNAME naik level script nya keren banget terus jokes jokesnya lebih ngena dari biasa recommended bgt dah",1,1,1),
(1228,27,"JUDULFILM mengikat janji  janji setia  setia abadi  URL",1,1,1),
(960,36,"JUDULFILM nya mas fajar nugros ini keren banget sih pemain pemainnya oke banget mainnya terutama baim wong dan bimo ",1,1,1),
(2238,36,"JUDULFILM nya mas fajar nugros ini keren banget sih pemain pemainnya oke banget mainnya terutama baim wong dan bimo  HASHTAG",1,1,1),
(1064,28,"JUDULFILM tentang tokoh di belakang layar sejarah amerika URL URL",1,1,1),
(2198,4,"JUDULFILM terbaik aku suka dengar gelak kau dari tepi tulang rusuk rasa serasi semacam hahahaha",1,1,1),
(1051,28,"JUDULFILM untuk melawan rasis ya harus pintar URL",1,1,1),
(2297,47,"JUDULFILM USERNAME terbaaeeekk  ceritanya lengkap asmara keluarga dan yg pasti persahabatan gila banget dah  URL",1,1,1),
(1229,27,"JUDULFILM versinya gac ini better daripada seberapa pantas versi mereka ya menurut gue enakan JUDULFILM kemana    ",1,1,1),
(2314,47,"juga gambar HASHTAG itu sangat mewah tetapi tertangkap dengan sederhana sekaligus memperkuat rasa manis filmnya suka sekali ",1,1,1),
(176,45,"kalimat yang paling sering digunakan dalam film hollywood adalah let s JUDULFILM of here  HASHTAG",1,1,1),
(962,36,"kalo agensi konsep model model JUDULFILM pake jablay mafia dan everything edgy moderen pada minat ga ya",1,1,1),
(2242,39,"kalo boleh aku kasih rating sih antara 1 10 rating untuk film JUDULFILM ini 9 hehe karena keren bgt dan terbawa suasana tegangnya     ",1,1,1),
(1328,11,"kamu tau hal yang tersulit itu bukan mengucapkan selamat tinggal tapi membiasakan diri tanpamu  JUDULFILM",1,1,1),
(571,119,"karena mengabdi bagi sesama itu baik HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",1,1,1),
(506,2,"karena perannya yang buagus minta ampun mb jessica chastain dapet nominasi golden globes tapi gak masuk nom oscars   HASHTAG",1,1,1),
(261,123,"kekalahan tanpa penyesalan   leorio ",1,1,1),
(2277,47,"kemaren pokok nya kocak banget dah tuh film USERNAME seru film HASHTAG nya URL",1,1,1),
(2214,13,"kenapa JUDULFILM kebanyakan cowok  karna cowok emang suka gitu suka berubah ubah ",1,1,1),
(2215,13,"kenapa JUDULFILM kebanyakan cowok karena cowok emang suka gitu suka berubah ubah HASHTAG",1,1,1),
(2217,13,"kenapa JUDULFILM kebanyakan cowok karna cowok emang suka gitu suka berubah ubah",1,1,1),
(2216,13,"kenapa JUDULFILM kebanyakan cowok karna cowok emang suka gitu suka berubah ubah ",1,1,1),
(2294,47,"keren bngt kak USERNAME film nya pecah bngt juga sedih bngt pas perpisahannya uuu   intinya the best bngt deh  URL",1,1,1),
(1330,11,"kirana paling suka baca novel sambil denger lagu dia paling suka novel JUDULFILM raja dan ratu dilan ",1,1,1),
(2212,11,"kirana paling suka baca novel sambil denger lagu dia paling suka novel JUDULFILM raja dan ratu dilan  URL URL",1,1,1),
(278,123,"kita adalah teman meski kita jauh jika kamu butuh pertolongan aku akan datang  gon ",1,1,1),
(376,46,"kita mengenal ibu JUDULFILM sebagai sosok pahlawan yang memiliki cita cita untuk memajukan kaum perempuan yakni  URL",1,1,1),
(2273,47,"kocak abis     selamat meninggal cabe2an yg cantik mari kita makan nasi goreng ketek     JUDULFILM   URL",1,1,1),
(631,3,"kocak asli     JUDULFILM   URL",1,1,1),
(2169,3,"kocak asli     JUDULFILM   URL URL",1,1,1),
(879,120,"kong yang sangat baik hati unch      JUDULFILM   URL",1,1,1),
(2312,47,"kq jadi suka y m film HASHTAG   ",1,1,1),
(806,31,"lagu sama suaranya john legend di JUDULFILM yang judulnya start a fire asik banget didenger ditelinga",1,1,1),
(2287,47,"lama ga nonton film akhirnya kemarin nonton JUDULFILM sumpah filmnya keren dan lucu HASHTAG USERNAME  URL",1,1,1),
(1551,33,"laura ni dah kena tikam pun selamba badak dia cabut gitu je haihh JUDULFILM ni anak hang ka",1,1,1),
(2257,47,"lebih bagus film JUDULFILM raditya dika dibanding film ini tapi lebih cakep indah permatasari ketimbang pevita pear  URL",1,1,1),
(2309,47,"lebih nyantol ke pesan moral cinta amp kebahagiaan dibndingkn mslah pekerjaan dalam HASHTAG  tapi ttp suka semuanya rencana bakal nonton lg",1,1,1),
(869,120,"loki jadi jagoan   JUDULFILM   URL",1,1,1),
(1587,48,"lola amaria ungkap problem perempuan dalam JUDULFILM  beritagarid URL",1,1,1),
(2174,3,"lucu anak kecilnya       JUDULFILM   URL",1,1,1),
(710,12,"lucu bgt pingin bawa pulang  USERNAME pidi baiq buka bukaan soal film JUDULFILM URL via USERNAME",1,1,1),
(2213,12,"HASHTAG HASHTAG lucu bgt pingin bawa pulang  USERNAME pidi baiq buka bukaan soal film JUDULFILM URL via USERNAME",1,1,1),
(2290,47,"lucu bnget klo liat sukun ggp  hha d USERNAME USERNAME HASHTAG URL",1,1,1),
(2289,47,"lucu juga JUDULFILM",1,1,1),
(2173,3,"lucu kayanya nih     JUDULFILM with elsa azriel and azka at USERNAME   URL",1,1,1),
(2284,47,"lucu persahabatan mengharukan di film ada dan semoga film JUDULFILM penontonnya makin banyak dan film ini lucu dan k  URL",1,1,1),
(1766,39,"masih terkesima sm aktingnya james mcavoy di film JUDULFILM        ",1,1,1),
(1869,16,"masih untung jarak bias jakarta korea nah JUDULFILM earth mars yailah udah beda planet  ",1,1,1),
(863,120,"mbak titi baru selesai nonton film JUDULFILM  bagus film nya  besok terakhir nonton bos baby ",1,1,1),
(2321,120,"mbak titi baru selesai nonton film JUDULFILM  bagus film nya  besok terakhir nonton bos baby  HASHTAG HASHTAG",1,1,1),
(268,123,"memiliki pengetahuan yang luas dan sehat jiwa dan raga pantang menyerah itu lah kualitas kebanggaan seseorang  kurapika ",1,1,1),
(449,55,"mengganggu orang pacaran HASHTAG URL",1,1,1),
(1062,28,"mengharukan JUDULFILM ungkap prestasi wanita minoritas amerika film JUDULFILM memang URL HASHTAG HASHTAG",1,1,1),
(638,3,"menghibur diri         JUDULFILM at USERNAME   URL",1,1,1),
(2292,47,"meski berantakan di babak terakhirnya HASHTAG ini film raditya dika pertama yang sangat gw nikmati dewasa sangat manis dan ya lucu ",1,1,1),
(2259,47,"minggu ini nonton  HASHTAG 6 5 10 bagus tp sering technical flaws hu HASHTAG 3 10 radityadika aku kecewa HASHTAG 8 10 verrry satisfied ",1,1,1),
(2279,47,"momen paling kocak pas nonton JUDULFILM adalah ketika satu studio ga ada yang tau gultik apa sabar yaa sabar yg bukan org jkt USERNAME",1,1,1),
(158,45,"movie JUDULFILM tadi best tapi psycho gila   ",1,1,1),
(1549,33,"mukanya gerak geriknya cara berpakaiannya mirip JUDULFILM lerman di the perks of being a wallflower   ",1,1,1),
(230,123,"musuh yang paling berbahaya adalah penakut dan bimbang  teman yg setia hanyalah keberanian dan keyakinan yang teguh  hisoka ",1,1,1),
(1043,28,"ngepens dengan taraji henson sejak meranin cookie di serial empire makin ngepens setelah liat aktingnya di JUDULFILM ",1,1,1),
(2295,47,"nnton kmrin film USERNAME HASHTAG sumpah keren banget bagian keluarga sama persahabatan nya ngena banget be  URL",1,1,1),
(2300,47,"nonton film indonesia tapi waktu tak berasa keren film JUDULFILM nya USERNAME",1,1,1),
(246,123,"nonton JUDULFILM seremnya sukses tpi nutupin mukanya ga peke sendal jg kalee       URL",1,1,1),
(457,55,"nyok nonton film HASHTAG by USERNAME  komplit dah jalan ceritanya koplak tp gk lebay  mksi bunda USERNAME yg udah info in   ",1,1,1),
(472,55,"okaay pokoknya jangan lupa nonton HASHTAG dan dukung terus HASHTAG",1,1,1),
(2225,31,"okeh sudah donlot JUDULFILM dilihat dari percuplikannya bagus   ",1,1,1),
(265,123,"orang yang tidak berani mengambil resiko dalam berjudi tidak akan bisa menang  tompa ",1,1,1),
(490,2,"pantesan si alitta ampe bisa ga tidur     JUDULFILM with alitta and retno   URL",1,1,1),
(280,123,"penyesalan akan datang diakhir cerita khidupan kita  gon ",1,1,1),
(2069,46,"perjuangan JUDULFILM perlu dilanjutkan URL",1,1,1),
(290,123,"perlu pengorbanan untuk mendapatkan tujuan  gon ",1,1,1),
(59,4,"pesan dari film JUDULFILM  seorang ayah tidak hanya menyayangi dan melindungi anak laki lakinya tetapi keluarga besarnya juga ",1,1,1),
(539,98,"pesan moralnya  kalau kita baik maka kebaikan juga yg akan datang     JUDULFILM   URL",1,1,1),
(1320,11,"pokoknya suka banget n ngefans JUDULFILM best film ever     ",1,1,1),
(2211,11,"pokoknya suka banget n ngefans JUDULFILM best film ever     URL",1,1,1),
(311,46,"polwan di bali rayakan hari JUDULFILM dengan bagi bagi bunga URL",1,1,1),
(2275,47,"pulang nntn HASHTAG serasa masih kerasa sama suasana d film ituuu kocak bang radit  dtunggu karya2 selanjutnya  URL",1,1,1),
(428,55,"quote favorit di JUDULFILM   jangan terlalu mencintai dunia karena allah dan rasul nya  URL",1,1,1),
(317,46,"ra JUDULFILM berjuang dan bergerak sebab murni keresahannya terhadap ketidakadilan hak perempuan saat itu HASHTAG HASHTAG",1,1,1),
(314,46,"ra JUDULFILM berjuang menyuarakan kegelisahannya dengan cara halus dan lugas HASHTAG HASHTAG",1,1,1),
(453,55,"rekomendasi selanjutnya adalah produksi dalam negeri insan muda yang berjudul JUDULFILM    URL",1,1,1),
(522,2,"resek ya gue kayak mendahului takdir filmnya HASHTAG pakek segala bilang udah tau filmnya bakal bagus hhhhhhh ",1,1,1),
(2176,3,"review film JUDULFILM kombinasi lucu dan mengharukan URL via USERNAME",1,1,1),
(2188,4,"review saya untuk HASHTAG yang dipenuhi dengan kegilaan awal baru yang bagus setelah perpisahan let s go URL",1,1,1),
(555,119,"rt USERNAME filmny koh USERNAME emang slalu menghibur     HASHTAG amp pensil",1,1,1),
(2226,31,"ryan reynolds di JUDULFILM keren anjir drpd di deadpool",1,1,1),
(2229,31,"sampah betul JUDULFILM macamanalah orang ramai boleh suka cerita ni ",1,1,1),
(2311,47,"saya suka video USERNAME URL film JUDULFILM  curahan hati raditya dika",1,1,1),
(245,123,"saya suka video USERNAME URL JUDULFILM versus insidious",1,1,1),
(2247,39,"sebelumnya suka bgt sm karakter don corleone di film godfather tp akting james mcavoy di film JUDULFILM ngeri 1 orang mainin banyak karakter   ",1,1,1),
(270,123,"sebuah kerja sama yang canggung hanya akan menjerat kita aku lebih memilih bekerja sendiri  kurapika  chapter 95 ",1,1,1),
(781,31,"sedih bodo ending JUDULFILM meluat",1,1,1),
(2162,1,"sedikit curhat tentang film yg gw tonton hari ini JUDULFILM bagus maaak i agree that japan had the best story line sihhh ",1,1,1),
(1141,1,"selain fate of the furious movie apa lagi yang best ada JUDULFILM dah keluar ke   ",1,1,1),
(2291,47,"selain lucu film ini memberikan inspirasi bagi saya thanks USERNAME HASHTAG URL",1,1,1),
(273,123,"semakin besar resiko yang kau ambil semakin besar kekuatan yang kau dapat  kurapika ",1,1,1),
(1017,28,"semalam tgk JUDULFILM terbayangkan mesti susah hidup dkt amerika time dibahagi ikut warna kulit kesian padahal colored people pandai ",1,1,1),
(2278,47,"semalam udah nonton HASHTAG kocak filmnya",1,1,1),
(2054,46,"senyummu yang JUDULFILM mbak mun menyihir gelap mimpiku menjadi cahaya senyata cinta HASHTAG USERNAME",1,1,1),
(366,46,"seorang perempuan kita harus memperjuangan martabat perempuan seperti apa yg dilakukan ibu JUDULFILM   ",1,1,1),
(2195,4,"seru lucu roman pierce terutama  tidak terduga alurnya rating 9 10 lah HASHTAG",1,1,1),
(1859,16,"seru nihhh       JUDULFILM at perumahan dasana indah   URL",1,1,1),
(556,119,"seru nonton film HASHTAG dan pensil terbaru USERNAME  d kocak abis pokoknya  d HASHTAG URL",1,1,1),
(2319,119,"seru nonton film HASHTAG dan pensil terbaru USERNAME  d kocak abis pokoknya  d",1,1,1),
(357,46,"setelah mendengarkan lagu ibu kita HASHTAG omed komentar pada gurunya bu guru saya baru tahu kalau nama ibu JUDULFILM sebenarnya itu harum ",1,1,1),
(2313,47,"soal percintaannya saya pribadi lebih suka single dibanding JUDULFILM tapi soal persahabatannya JUDULFILM juara sangat menghibur ",1,1,1),
(2315,47,"sore tadi nonton HASHTAG seneng liat om radit kembali bikin cerita yg dekat sama kehidupan sehari hari tapi ngena maksimal suka banget   ",1,1,1),
(76,4,"spoiler berat  bryan muncul lagi di film ke 8 ini  tapi ga pake cgi hmmm HASHTAG",1,1,1),
(2206,9,"suka banget sama lagu lagu di JUDULFILM      ",1,1,1),
(2318,55,"suka liat film film pendeknya di youtube eh tadi ketemu pas habis nonton JUDULFILM   URL",1,1,1),
(2240,38,"suka pun diam nak confess tak berani kalau apa apa pun diam semua diam sakit diam terasa hati diam JUDULFILM is the best way maybe  ",1,1,1),
(2302,47,"sumpah ini film kk yg paling seru dan gokil   pokok nya harus ada JUDULFILM yg ke 2   harus lebih gokil  URL",1,1,1),
(1874,16,"tak gugur air mata tapi sedih je JUDULFILM URL",1,1,1),
(2230,31,"tak suka ending JUDULFILM sebab mia end up dgn lelaki lain but still it was a good movie",1,1,1),
(957,36,"tapi jangan kaya JUDULFILM juga r rated mau beli tiket nunjukin ktp etapi sensorannya banyak bener yaa relep",1,1,1),
(562,119,"tatjanasaphira 19 sejak debutnya HASHTAG 2013 makin berkilau dlm 7 flm unjuk akting sbg bubu siswi cantik manis telmi di HASHTAG amp pensil",1,1,1),
(87,4,"terbukti bahwa keluarga adalah no 1 HASHTAG",1,1,1),
(1139,1,"the boss baby 100 kali ganda lbh best drpd JUDULFILM   ",1,1,1),
(501,2,"this thread setuju merinding pas akhir2 film gak nyangka akan kek gitu HASHTAG URL",1,1,1),
(330,46,"tri astuti srikandi desa representasi sosok JUDULFILM masa kini URL",1,1,1),
(1038,28,"udah 2 film yang ditonton semua tentang rasis JUDULFILM di kantor nasa dan loving tentang perkawinan terlarang antar ras di virginia ",1,1,1),
(279,123,"untuk mengenal seseorang mulailah dengan mencari apa yg membuatnya marah  gon   bibi mito ",1,1,1),
(277,123,"untuk menjadi keluarga itu tidak perlu persyaratan  maka untuk menjadi sahabat pun tak perlu persyaratan   gon ",1,1,1),
(283,123,"untuk menjadi teman tidak ada istilah pantas atau tidak  gon ",1,1,1),
(473,55,"untuk perempuan yg belum menikah ini saatnya menggali hobby dan passion kita lebih dalam HASHTAG",1,1,1),
(282,123,"untuk uang kita tidak perlu khawatir untuk sementara waktu  gon ",1,1,1),
(1254,27,"USERNAME cerita cinta kasih JUDULFILM iki lee",1,1,1),
(2228,31,"USERNAME cheezy sangat weh JUDULFILM ni aku bab cheezy ni suka kat burger je tak suka kat filem  ",1,1,1),
(2234,33,"USERNAME dan lagi  gue nunggu bloopers gags nya JUDULFILM pasti lucu lucu    ",1,1,1),
(2281,47,"USERNAME dengan manis bisa membuat film HASHTAG mencampur emosi antara lucu sedih dan jatuh cinta ",1,1,1),
(1259,27,"USERNAME doa sejoli menjalin cinta cinta bersemi dari sma JUDULFILM mengikat janji janji setia setia abad  URL",1,1,1),
(2233,33,"USERNAME doctor srrange iya  kocak banget        semoga JUDULFILM ada soalnya x men pun ada bloopersnya juga       ",1,1,1),
(2170,3,"USERNAME dua duanya JUDULFILM itu gemesin banget kocak juga",1,1,1),
(1257,27,"USERNAME dua sejoli menjalin cinta cinta bersemi dari sma JUDULFILM mengikat janjii janji setia setia abadii ",1,1,1),
(2255,47,"USERNAME film JUDULFILM gw rating bagus bang USERNAME bnr2 seperti realita sehari hari dan makna pengorbanan  URL",1,1,1),
(2276,47,"USERNAME film JUDULFILM jg lucu sedih mengharukan komplit tapi disaat sedih malah dijejelin yang lucu kocak filmnya ",1,1,1),
(2270,47,"USERNAME film JUDULFILM lucu abis si sukun anjir kocak yg bikin ngakak pas bilang cabe2an cantik    thx udh dat  URL",1,1,1),
(2186,4,"USERNAME HASHTAG dong ceritanya bagus beda sama fast amp furious 1 7 HASHTAG",1,1,1),
(1680,13,"USERNAME huhu apakan daya hati tak leh paksa   gila tak takut JUDULFILM hahaha",1,1,1),
(1263,27,"USERNAME JUDULFILM  mengikat janjee  janji setia  setia abadi   ",1,1,1),
(1028,28,"USERNAME JUDULFILM dah nonton lum bagus tuh tp drama kaya true story gt",1,1,1),
(2223,28,"USERNAME JUDULFILM dah nonton lum bagus tuh tp drama kaya true story gt HASHTAG HASHTAG",1,1,1),
(2235,33,"USERNAME JUDULFILM gatau suka bgt sama film itu  ",1,1,1),
(2236,33,"USERNAME JUDULFILM imut suka yang aura dom nya kuat kaya yifan heh",1,1,1),
(2184,3,"USERNAME JUDULFILM ini film animasi genrenya komedi n family gitu  ell suka animasi ngga ",1,1,1),
(2304,47,"USERNAME JUDULFILM keren film nyaaaa pas terakhir nya terharu bikin nangis   mantappp film nya  gaksiasianonton URL",1,1,1),
(2307,47,"USERNAME keren bang film nya bnyk belajar dr karyamu yg ini persahabatan keluarga amp kekasih hati semua adl c  URL",1,1,1),
(1772,39,"USERNAME keren ga harus bisa JUDULFILM",1,1,1),
(2298,47,"USERNAME kyaknya loe bakalan jd salah satu legend perfilman komedi indonesia bang  filmnya gapernah mengecewak  URL",1,1,1),
(171,45,"USERNAME lucu ada yg pake poster china JUDULFILM  lupa yaa kl penduduk china tuh mayoritas didunia wk wk wk HASHTAG HASHTAG",1,1,1),
(2252,45,"USERNAME lucu ada yg pake poster china JUDULFILM  lupa yaa kl penduduk china tuh mayoritas didunia wk wk wk",1,1,1),
(1048,28,"USERNAME ohh klau movie an kau tgk la JUDULFILM best",1,1,1),
(185,45,"USERNAME oke kartini masuk list no 1 haha JUDULFILM udah dong emang keren itu xd",1,1,1),
(2254,45,"USERNAME oke kartini masuk list no 1 haha JUDULFILM udah dong emang keren itu xd HASHTAG",1,1,1),
(2243,39,"USERNAME om uda ntn film JUDULFILM 2017  ternyata ad hub dgn film unbreakable superhero unrated yg om share kmrn keren ",1,1,1),
(1322,11,"USERNAME strikes again  setelah talak 3 dan JUDULFILM kartini kembali tampil baik dalam bertutur ajak2 nulis dong mas hehe",1,1,1),
(1862,16,"USERNAME tapi paling gantengnya di JUDULFILM ",1,1,1),
(1035,28,"USERNAME tp serious HASHTAG best even slow sikit psl 3 female negro engineers kat nasa",1,1,1),
(496,2,"USERNAME USERNAME jauh lebih dikit dan JUDULFILM pun ada dialog pembenaran letak indonesia",1,1,1),
(2262,47,"USERNAME USERNAME JUDULFILM bagus tadi siang baru nonton ",1,1,1),
(773,31,"USERNAME USERNAME JUDULFILM tak seswai utk org jawa sbb xde hepi ending ur name aku dh tgok best dowh",1,1,1),
(353,46,"USERNAME USERNAME nah ini baru the real spirit of JUDULFILM salut mba USERNAME baru mba yg ngomon  URL",1,1,1),
(2248,45,"USERNAME USERNAME pehlah besok ketemu nobar JUDULFILM kek gek aku kasih asupan film bagus biar energi negatifnyo pulih ",1,1,1),
(2268,47,"USERNAME USERNAME pilihan bagus selamat menonton    nanti jumat HASHTAG",1,1,1),
(2166,3,"USERNAME USERNAME USERNAME HASHTAG JUDULFILM ceritanya bagus baby nya lucu sekaligus ngeselin   ",1,1,1),
(2260,47,"USERNAME USERNAME USERNAME office comedy persahabatan keluarga percintaan fokusnya hilang karen  URL",1,1,1),
(2261,47,"USERNAME USERNAME USERNAME tadi liat raihan penonton JUDULFILM ternyata lumayan juga bagus deh sepertinya  URL",1,1,1),
(1444,25,"USERNAME USERNAME utk bapak yg tadi bapak yg di film JUDULFILM amp bapak2 lain yg punya anak perempuan   URL",1,1,1),
(2220,25,"USERNAME wah iyaaa barusan liat thriler nya JUDULFILM bagus kyknya yaa ",1,1,1),
(2239,37,"USERNAME wah JUDULFILM nya bagus  ",1,1,1),
(951,36,"USERNAME walah baiklh mas semoga diganti yang lebih canggih banyak pertanyaan ttg JUDULFILM soale hahaha",1,1,1),
(1667,13,"wanita itu hebat yg nggak hebat JUDULFILM warna pink ",1,1,1),
(814,31,"ya moonlight menang dari JUDULFILM karena emang lebih bagus ah ga asik lo   URL",1,1,1),
(2224,31,"ya moonlight menang dari JUDULFILM karena emang lebih bagus ah ga asik lo   URL URL",1,1,1),
(2194,4,"yang butuh tontonan kocak dan seru bisa HASHTAG walaupun ada beberapa plot hole masih acceptable lah  ",1,1,1),
(2209,9,"yang demen drama musikal sih pasti suka pangerannya cuco ema watson suaranya kece    JUDULFILM   URL",1,1,1),
(2246,39,"yang suka unbreakable pasti suka ini     JUDULFILM   URL",1,1,1),
(517,2,"yg cakep dr HASHTAG selain JUDULFILMnya ya cara membangun konflik dan emosi penonton mau spoiler tp tar gue disambit netizen hhhhh ",1,1,1),
(2283,47,"yg mencuri justru widyawati sbg ibu kesepian HASHTAG sedangkan radityadika justru masi blm lepas dari tokoh jomblo mencoba lucu",1,1,1),
(2525,31,"  HASHTAG                     sinematographynya emang beneran keren abisssss       JUDULFILM at green palace apartment   URL",0,1,0),
(1876,16," abis nonton film JUDULFILM malah baper ",0,1,0),
(1250,27," dua sejoli mencari cinta  JUDULFILM  USERNAME USERNAME USERNAME   URL",0,1,0),
(2755,120," HASHTAG medeni yo njijik i yo lucu critane URL",0,1,0),
(818,31," JUDULFILM  baru sempat nonton dan dari awal beneran bikin senyam senyum  plot nya yg diawal ngetw  URL via USERNAME",0,1,0),
(2457,4," JUDULFILM aja ya   boleh deh aktornya botak semua kaya kamu  ya allah hahha  lucu kek upin ipin   iya untung sayang       ",0,1,0),
(2582,45," JUDULFILM bagus bgt woi   trs sebel ada jumpscare gt apa gw nya jg yg kagetan y  ",0,1,0),
(2424,4," JUDULFILM bukan sekadar menghancurkan mobil mobil keren URL URL",0,1,0),
(2537,33," USERNAME   ide bagus   aku mendengar gelakan kekeh JUDULFILM setelahnya seperti penyakit menular aku pun ikut terkekeh cont ",0,1,0),
(1050,28," USERNAME  4 URL 5 JUDULFILM  banyak sih tapi lagi suka banget sama ituu 16 very interesting ngobrol yu ",0,1,0),
(2758,28," USERNAME  4 URL 5 JUDULFILM  banyak sih tapi lagi suka banget sama ituu 16 very interesting ngobrol yu  HASHTAG",0,1,0),
(2603,47," USERNAME kepikiran film JUDULFILM lg pengambilan scene senjanya sih bagus bgt i adore that so much  ",0,1,0),
(2748,47," USERNAME USERNAME entah kenapa gue selalu suka kalo soraya produksi film dan di film JUDULFILM si  URL",0,1,0),
(2563,39,"1 orang memiliki 24 kepribadian james mcavoy bagus meranin karakternya    JUDULFILM   URL",0,1,0),
(2455,4,"10 pelesetan  ok oce  ala netizen ini kocak dan kreatif abis URL telegram  rfbet99  URL",0,1,0),
(2554,38,"12 dead JUDULFILM ini nyeritain tentang pulau kosong gitu keren banget deh sumpah gue suka cara nyiksanya tuh ora  URL",0,1,0),
(2759,33,"738 hm banyak sih film yg gue suka tp sementara ini lg suka JUDULFILM",0,1,0),
(2431,3,"aaahh lucu bangett jadi pengen punya     JUDULFILM at USERNAME   URL",0,1,0),
(2661,47,"abis nonton HASHTAG punya USERNAME lucu banget     tapi baper parah yg sukun pulang huhuhu syadddd sedii ",0,1,0),
(1855,16,"abis nonton JUDULFILM bagus y ternyata yaampun ketinggalan ak tu  HASHTAG",0,1,0),
(2500,16,"abis nonton JUDULFILM bagus y ternyata yaampun ketinggalan ak tu ",0,1,0),
(778,31,"abis nonton JUDULFILM jadi berbunga bunga dan kebayang wajah mia mudah mudahan istriku ga baca ini ",0,1,0),
(2440,3,"abis nonton JUDULFILM kebawa mimpi punya anak bayik gendut suka ngatur ngatur tapi lucuk    the big fat bossy baby hmmm seems familiar",0,1,0),
(2640,47,"abis nonton JUDULFILM USERNAME kocak abis btw koreksi dikit di kuningan jabar itu belum ada mall loh adanya toserba kecil d",0,1,0),
(2711,47,"abis un nonton JUDULFILM sama keluargaa dannn film lo asli buat ngakakk terharu pokonyaa keren bang      USERNAME URL",0,1,0),
(2613,47,"ada 2 film bagus ya bln ini JUDULFILM sama ff8 ",0,1,0),
(2507,25,"ada yg udh nonton JUDULFILM ga sih ya ampun bagus banget asli     ",0,1,0),
(2412,4,"after office refresh nonton film yg keren pake bgt       HASHTAG HASHTAG    kuningan city URL",0,1,0),
(2584,45,"ah menyenangkan selalu menyenangkan tiap sehabis nonton film bagus  go JUDULFILM to see JUDULFILM before it gets out from the cinemas ",0,1,0),
(2650,47,"akhirnya nonton JUDULFILM juga sama USERNAME JUDULFILM lucu kak USERNAME paling lucu ya sukun cabe cabean cantik wkwkwk",0,1,0),
(2638,47,"akhirx bs nonton film bang USERNAME smangat bang buat bikin film selnjtx   filmx sedih amp kocak sdih ketika slh sat  URL",0,1,0),
(986,36,"akting USERNAME keren sih HASHTAG JUDULFILM",0,1,0),
(2636,47,"akting widyawati keren banget  pukai kocak  indra jegel justru malah biasa aja HASHTAG",0,1,0),
(884,120,"aku baru berpeluang tengok JUDULFILM ni soalan aku  kenapa manusia datang pulau tu pastu terus campak bom ",0,1,0),
(1124,1,"aku baru tahu cerita JUDULFILM tu dprd anime    ",0,1,0),
(911,29,"aku letak fast 8 ni sebelah dengan john wick chapter 2 utk movie terbaik tahun ni setakat ni ",0,1,0),
(1857,16,"aku menginginkan bumi namun bumi tak menginginkan aku           JUDULFILM   URL",0,1,0),
(797,31,"aku suka gila vision chazelle dalam JUDULFILM bila dia shoot every muzikal dalam one take power ",0,1,0),
(2526,31,"aku suka gila vision chazelle dalam JUDULFILM bila dia shoot every muzikal dalam one take power  HASHTAG",0,1,0),
(2750,55,"alhamdulillah akhirnya bisa nonton HASHTAG juga      satu kata buat film nya  keren      URL",0,1,0),
(2400,4,"amazing   keren banget   nunggu ff9 HASHTAG",0,1,0),
(2390,4,"anjass keren  HASHTAG",0,1,0),
(805,31,"apala nonton JUDULFILM sendirinya jadi baper habis itu           ",0,1,0),
(2580,45,"apalagi film film gak biasa yg reviewnya lumayan bagus banget JUDULFILM udah banyak reviewnya ",0,1,0),
(2573,39,"asli keren abis     JUDULFILM   URL",0,1,0),
(2642,47,"asli parah kocak abis satu ruangan dibikin ngakak bareng sama tingkah mereka JUDULFILM   URL",0,1,0),
(2405,4,"asli sih keren mampus JUDULFILM nya",0,1,0),
(476,55,"assalamualaikum  hi twips buat yang mau nonton recommended bgt nih film HASHTAG jgn lupa nonton ya dan dukung sll HASHTAG ",0,1,0),
(2726,47,"awlnya mau nntn fast8 tp g dpt tiket jd nya nntn JUDULFILM lhamalah suka sm film ini sedih gr2 sukun bilang selamat meninggal jakarta  d",0,1,0),
(252,123,"bagaimanapun kita harus mensyukuri ini karena kita sudah bekerja keras untuk mendapatkan ini  leorio  chapter 80 ",0,1,0),
(2623,47,"bagus banget film JUDULFILM skrg tau apa arti pertemanan tonton tuh biar tau arti teman itu   at USERNAME   URL",0,1,0),
(2442,4,"bagus sih HASHTAG makin gokil aja cara ngancurin mobilnya tapi entah favoritku masih HASHTAG",0,1,0),
(859,120,"bagus ternyata     JUDULFILM   URL URL",0,1,0),
(2751,120,"bagus ternyata     JUDULFILM   URL",0,1,0),
(2646,47,"bang film JUDULFILM nya lucu banget bang pas maen petasan trus yang bikin sedih dimenit menit akhir nice film baruny  URL",0,1,0),
(2715,47,"bang keren banget film JUDULFILM nya  mumpung lagi libur  thx bang keren filmnya USERNAME",0,1,0),
(2745,47,"bang USERNAME  film the guya  film kedua yang gua suka setelah single HASHTAG URL",0,1,0),
(2739,47,"bang USERNAME anjjiirrrrrrrr kereeeennn abissss gilaaaa sukaaaa gueeeee film HASHTAG nya pettttcaaaahhh suka  URL",0,1,0),
(2634,47,"bang USERNAME film JUDULFILM keren dan kocak abis             URL",0,1,0),
(2620,47,"bang USERNAME kemaren aku ntn berempat sm sahabat gila bagus banget JUDULFILM nya romanceny dpt sampe bikin nangis friendshipnya beh",0,1,0),
(2615,47,"bang USERNAME kenapa film HASHTAG banyak sedihnyaaa   tapi bagus banyak ngasih pelajaran difilmya         URL",0,1,0),
(2418,4,"banyak kejutan  keren keren keren rekomendasi bat dah HASHTAG",0,1,0),
(1957,130,"baru aja kelar nonton JUDULFILM dan banyak banget pelajaran berharga tentang hidup yang gue dapat ",0,1,0),
(1867,16,"baru aja nton film JUDULFILM  nonton nya sambil termehek mehek kzl",0,1,0),
(2528,31,"baru beres nonton JUDULFILM suka pake bangettttt   ahhhh coba bisa nonton di bioskop",0,1,0),
(1040,28,"baru mood nonton the edge of seventeen stelah sblmnya nnton sejenis JUDULFILM dan kamedy kamedy an tok not bad      ",0,1,0),
(68,4,"baru nonton JUDULFILM  bahkan dalam film fiksi pun yang jahat akhirnya kalah amp hancur jangan lelah menebar kebaikan ",0,1,0),
(970,36,"baru nonton JUDULFILM epic bgt adegan elu bangg wgwg USERNAME",0,1,0),
(810,31,"baru nonton JUDULFILM sempet nyinyir dulu tapi ini film beneran manis banget ",0,1,0),
(2725,47,"baru pertama kali nonton bioskop dan film yang kami pilih adalah JUDULFILM suka banget filmnya love it  lt 3 URL",0,1,0),
(2456,4,"bayi di JUDULFILM lucu sekali ya         ",0,1,0),
(634,3,"bayinya imut         jadi kapan kita punya bayi    JUDULFILM w maissie melda  amp jennipher at USERNAME   URL",0,1,0),
(2606,47,"belakangan film film indonesia emang lumayan bagus sih dari winter in tokyo cts trus JUDULFILM juga keren parah",0,1,0),
(867,120,"better ini sih dibanding film tentang king kong sblmnya   JUDULFILM   URL",0,1,0),
(2406,4,"btw tingkyu om blo udah diajakin nonton film keren ini   HASHTAG",0,1,0),
(2618,47,"bulan april ini filmnya bagus bagus semua JUDULFILM kartini surau dan silek harua nonton semuaaaa",0,1,0),
(2428,3,"bulan april kok pada byk film yg bagus yaa  fast amp furious 8 stip amp pensil JUDULFILM smurf ku ingin nonton iniii       ",0,1,0),
(2398,4,"by the way film JUDULFILM keren banget sumpah  yang belum nonton buruan deh recomended banget dan ga akan nyesel pokonya   ",0,1,0),
(2717,47,"ceritanya oke lah tapi yang bikin film JUDULFILM menarik buat saya adalah persahabatan alfi rene aryo amp sukun acting cast nya keren ",0,1,0),
(1346,11,"cewek tuh takdirnya dikejar bukan mengejar jadi jangan terlalu mengejar seseorang yg inginnya berlalu HASHTAG URL",0,1,0),
(478,55,"cinta itu cahaya sanubari kurniaan tuhan fitrah insani dan di mana terciptalah cintadi situ rindu bermula HASHTAG",0,1,0),
(1021,28,"cuma dalam film JUDULFILM tu dia highlight lebih kepada peranan wanita berkulit hitam dalam perkomputeran nasa ",0,1,0),
(2513,31,"cupu baru nonton  tapi diluar ini film musikal yang keren ceritanya ternyata bagus banget    JUDULFILM   URL",0,1,0),
(2571,39,"dan akhirnya baru sempet nonton ini sampai habis   selain james mcavoy keren banget actingnya     JUDULFILM   URL",0,1,0),
(2704,47,"dan pelawak senior tarzan ini emang legend karakternya keren apalagi saat bareng USERNAME USERNAME USERNAME HASHTAG",0,1,0),
(2480,11,"danur luar biasa tadinya saya mikir JUDULFILM akan jd movie of the year krn novelnya USERNAME keren   URL",0,1,0),
(2602,47,"dapat darimana sosok HASHTAG itu bang USERNAME konyol tp overall HASHTAG tontonan wajib bagus filmnya plus sountracknya keren juga  ",0,1,0),
(2631,47,"dari awal sampe akhir kagum banget sama film JUDULFILM raditya dkk kocak banget USERNAME USERNAME HASHTAG URL",0,1,0),
(2599,47,"dari semua film USERNAME cuma film JUDULFILM ini yg bagus single bagus tp rada kentang ceritanya",0,1,0),
(2478,11,"dear minoc lebih bagus daripada JUDULFILM ",0,1,0),
(641,3,"dengerin apa kata si cebol    HASHTAG URL",0,1,0),
(2437,3,"di bioskop ada film keluarga yang lucu dan unik yang sedang tayang di bioskop nih pop ice lovers nama filmnya adal  URL",0,1,0),
(63,4,"di JUDULFILM  bahkan dalam film fiksi pun yang jahat akhirnya kalah amp hancur  dulu kalah di pilbup  URL",0,1,0),
(2395,4,"di JUDULFILM semua yg dlunya jahat jd baik adegan jashon nyelamatin bayinya toreto itu udh paling keren   ",0,1,0),
(81,4,"diajakin nonton JUDULFILM dua kali aja aku masih mau gila keren abis ",0,1,0),
(2384,4,"diajakin nonton JUDULFILM dua kali aja aku masih mau gila keren abis HASHTAG baper deh",0,1,0),
(2747,47,"dikaa film JUDULFILM lu kereeeennnn gue suka filmya emosionalnya terasa deh apalagi saat lu sama pevita wkwk USERNAME menang banyak lu",0,1,0),
(2068,46,"dlm buku JUDULFILM pendidikan utk perempuan adalah kunci kemajuan HASHTAG pidato USERNAME",0,1,0),
(2574,39,"eh eh eh  JUDULFILM ini keren ternyata ",0,1,0),
(2744,47,"entah dr dulu suka bgt sm filmfilm mu bang USERNAME tp yg JUDULFILM ini paling aku suka pesennya ngena bgt nangis ketawa jd satu  ",0,1,0),
(2404,4,"f amp f 8 emng lucu dan keren haha pas bgt lah wanita jalangnya mati pengganggu bgt  HASHTAG HASHTAG",0,1,0),
(2386,4,"f8 keren habisssss   recommended daaaa temen temen yuu sama2 nonton lagi p URL",0,1,0),
(2402,4,"f8 sumpah keren HASHTAG HASHTAG",0,1,0),
(1756,39,"fak ar citer JUDULFILM gila gak sial otak tngk cite mcm ni URL",0,1,0),
(2732,47,"ff8 kedua kalinya suka banget abis ini lanjut JUDULFILM   ",0,1,0),
(2621,47,"fillmnya bagus banget bang USERNAME recommended HASHTAG URL",0,1,0),
(2760,38,"film JUDULFILM bagus ",0,1,0),
(2605,47,"film JUDULFILM bagus bgt drama lucu nya dapet bgt       bang USERNAME ga pernah bikin kecewa penontonnya       URL",0,1,0),
(2562,39,"film JUDULFILM bagus URL",0,1,0),
(2653,47,"film JUDULFILM keren bgt lucu sama menginspirasi recommend bgt buat yg lagi stress sama pusing gara2 sekolah   URL",0,1,0),
(2654,47,"film JUDULFILM keren parah lucu bgt sama menginspirasi cocok bgt yg lagi pusing sama stress recommend bgt deh     URL",0,1,0),
(2589,45,"film JUDULFILM lucu loh  hahaha  ketawa sambil tutup mata",0,1,0),
(2617,47,"film JUDULFILM pesan moralnya bagus coy",0,1,0),
(2394,4,"film keren JUDULFILM USERNAME  japanan gempol pasuruan URL",0,1,0),
(2539,33,"film marvel paling bagus JUDULFILM yang lainnya biasa aja ",0,1,0),
(2627,47,"film nya kak radit sumpah bagus banget bikin ngakak melulu dan bikin baper pas banget nonton film JUDULFILM habis ut  URL",0,1,0),
(507,2,"film pertama nih rekomendasi kita ada  fast and furious 8  JUDULFILM   HASHTAG",0,1,0),
(2624,47,"filmnya bagus bnget  jd ikutan sedih jg pas sukun balik k thailand  USERNAME USERNAME HASHTAG URL",0,1,0),
(2399,4,"filmnya keren sumpah     HASHTAG ada HASHTAG URL",0,1,0),
(2637,47,"filmnya kocak parah dan menyentuh banget bawaanya pingin nonton film JUDULFILM terus wkwkwk  sukses untuk bang ra  URL",0,1,0),
(2652,47,"finally nntn JUDULFILM amp parah sesuai ekspektasi dari lucu sampe bikin nangis pliss ada JUDULFILM 2     worth to wat  URL",0,1,0),
(2737,47,"ga tau kenapa suka aja sama filmnya mas dhika dan pst nonton  agak2 nyrempet hidup gw di masa lalu    JUDULFILM   URL",0,1,0),
(2546,33,"gatau kenapa suka bet wolfrine   JUDULFILM   URL",0,1,0),
(1838,16,"gatau knp tbtb jd suka film yg planet2 ya     JUDULFILM   URL",0,1,0),
(804,31,"gentle reminder that JUDULFILM can fucking choke uwuwuwuwu",0,1,0),
(2724,47,"gila filmnya petjah bang keren abis JUDULFILM      barusan liat trailernya di youtube trailernya aja ketjeh apalagi filmnya USERNAME",0,1,0),
(2396,4,"gila keren abis  apapun film lo juaranya HASHTAG  URL",0,1,0),
(2635,47,"gila petjah abis bang filmnya kocak abis pemeran si sukun   cinta perjuangan persahabatannya ngena bgt   thanks ba  URL",0,1,0),
(1054,28,"gilaaaakkk pinter banget njir fisika matematika ne tjooooyyyyy         JUDULFILM   URL",0,1,0),
(2736,47,"gratisnyatuh disini     HASHTAG USERNAME suka euy filmna URL",0,1,0),
(2735,47,"gw udah nonton nih film JUDULFILM bang USERNAME suka banget d URL",0,1,0),
(523,2,"habis gimana emang HASHTAG sebagus itu sih padahal gue udah mewanti wanti supaya ngga terlalu kaget krn ceritanya pasti bagus ya ",0,1,0),
(2734,47,"habis nonton film bang USERNAME JUDULFILM  saya n adik suka banget salut bang URL",0,1,0),
(2632,47,"habis nonton HASHTAG seruu banget kocak abiss  langsung dh di download kak USERNAME y ",0,1,0),
(955,36,"habis nonton JUDULFILM   ceritanya epik banget   peran dari garindra bimo sama agus kuncoro tai banget  ",0,1,0),
(1133,1,"hadirnya versi live anime futuristik URL URL",0,1,0),
(2496,13,"hai kamu jangan suka berubah ya ingat yang suka berubah itu JUDULFILM bukan kamu ",0,1,0),
(2710,47,"hai USERNAME film HASHTAG nya keren banget sumpah bang gua nonton sampe mewek apalagi ketawanya gak bisa diben  URL",0,1,0),
(2410,4,"hai vindiesel       biz lht film JUDULFILM keren bangetzzz film y  baru kali ini lht  URL",0,1,0),
(2438,3,"hari ini nonton JUDULFILM for me ratingnya sekitar 7 10  animasinya lumayan imajinasinya keren messagenya lumayan lucunya kurang ",0,1,0),
(2722,47,"hari pertama film JUDULFILM di cinema citraxxi semarang keren bang  URL",0,1,0),
(439,55,"harus bisa move on  gak mungkin begini terus  dia telah bahagia disana dengan seorang pangeran  HASHTAG HASHTAG HASHTAG",0,1,0),
(2572,39,"harusnya g nunda ntn JUDULFILM  keren bgt  disaat smua heboh sama hero n villains  ni movie ksh plot beda        ",0,1,0),
(2448,4,"HASHTAG bagus gaaaa    ",0,1,0),
(89,4,"HASHTAG bagus kok    bodo amat ama orang2 ngomong apaan  ",0,1,0),
(2443,4,"HASHTAG bagus kok    bodo amat ama orang2 ngomong apaan   HASHTAG HASHTAG",0,1,0),
(2522,31,"HASHTAG film keren tapi lagu2 nya lebih keren sebuah penyegaran di tengah serbuan film2 superhero    URL",0,1,0),
(1323,11,"HASHTAG film yg bikin baper banget       URL",0,1,0),
(2460,4,"HASHTAG hallo brian kamu lucu sekalee            HASHTAG HASHTAG  cgv cinemas jwalk URL",0,1,0),
(2433,3,"HASHTAG ini bener2 ungkapan hati seorang anak tunggal yg tiba2 punya adek  lucu bangeet HASHTAG",0,1,0),
(2656,47,"HASHTAG jadi demam diantara gw amp tmen2 yg nnton bareng lucu terharu ketawa sama nangis jadi satu film yg luarb  URL",0,1,0),
(2523,31,"hazard kayaknya cocok nih buat jadi lawan main emma stone di JUDULFILM jilid 2 aktingnya keren ",0,1,0),
(1970,130,"holyshit cerita JUDULFILM ni serius buat aku terkesan in a sad way cerita yang simple tapi heavy gila lesson dia based on a true story ",0,1,0),
(1848,16,"ik aku baru tgk movie nih JUDULFILM just wow jaa sweet love movie   pengorbanan sorg bapak tok anak dia  URL",0,1,0),
(772,31,"ingin terus bermimpi terus mengejar mimpi eh endingnya kayak JUDULFILM padahal ya lagi sayang sayangnya ",0,1,0),
(615,3,"ini 6 pelajaran karier dari film JUDULFILM yang akan buat kamu lebih dewasa USERNAME URL",0,1,0),
(2651,47,"ini film lucu banget     JUDULFILM   URL",0,1,0),
(2467,9,"ini lebih bagus dari JUDULFILM sih   cinderella   URL",0,1,0),
(2432,3,"ini lucu kek kamu       JUDULFILM at jl azizi raya   URL",0,1,0),
(895,120,"inii asliii keren bangett       JUDULFILM at bondes 37 a   URL",0,1,0),
(2604,47,"itu film kan bagus kyknya gue pengen nonton JUDULFILM URL",0,1,0),
(2420,4,"jadi orang pertama nonton di hari pertama launching film ini rasanya beda banget gila keren bingit enggak nyesel  URL",0,1,0),
(979,36,"jakarta itu keras pras kamu pernah denger temen makan temen kan  awing JUDULFILM ",0,1,0),
(985,36,"jam segini masih terjaga JUDULFILM sungguh membuatku penasaran hingga tak ingat bulan telah bangkit",0,1,0),
(1837,16,"jd suka film planet gini ya     JUDULFILM   URL",0,1,0),
(2505,16,"jd suka film planet gini ya     JUDULFILM   URL URL",0,1,0),
(1251,27,"juara ke 18 HASHTAG USERNAME  JUDULFILM HASHTAG  streaming URL",0,1,0),
(2548,36,"JUDULFILM 2016 ini keren banget akting ginandra bimo outstanding baru kali ini liat dia acting dan ternyata memuaskan ",0,1,0),
(1866,16,"JUDULFILM aku kira cerita humanxalien",0,1,0),
(2540,33,"JUDULFILM bagus amat yah ya ampun",0,1,0),
(2607,47,"JUDULFILM bagus banget persahabatan cinta kasih dan humornya dapat banget    keren laah layak tonton banget nih  URL",0,1,0),
(2583,45,"JUDULFILM bagus banget sayang sebentar lagi turun layar tadi aja yang nonton cuman 4 orang ",0,1,0),
(1033,28,"JUDULFILM bagus banget yailah",0,1,0),
(2509,28,"JUDULFILM bagus banget yailah HASHTAG HASHTAG",0,1,0),
(2587,45,"JUDULFILM bagus beneran mending kejar itu dulu baru fast furious 8 ",0,1,0),
(1046,28,"JUDULFILM bagus bgt  ",0,1,0),
(2510,28,"JUDULFILM bagus bgt   HASHTAG",0,1,0),
(2446,4,"JUDULFILM bagus bgt gara2 ada abang jason statham jd tamu hiks so hot so hot",0,1,0),
(2610,47,"JUDULFILM bagus ih  ",0,1,0),
(1834,16,"JUDULFILM bagus juga filmnya lumayan lah",0,1,0),
(2499,16,"JUDULFILM bagus juga filmnya lumayan lah HASHTAG",0,1,0),
(2566,39,"JUDULFILM bagus kaga URL",0,1,0),
(2517,31,"JUDULFILM bagus lagu lagunya aja ",0,1,0),
(2601,47,"JUDULFILM bagus mba pengen nonton   URL",0,1,0),
(2576,43,"JUDULFILM bagus tuh kayaknya ya     ",0,1,0),
(2561,39,"JUDULFILM bagus URL",0,1,0),
(2449,4,"JUDULFILM bener2 bagus nonton itu berkali kali juga mau gue   ",0,1,0),
(2407,4,"JUDULFILM bukan sekadar menghancurkan mobil mobil keren URL",0,1,0),
(2718,47,"JUDULFILM bukan the gays keren sih apalagi pas ngorbanin perasaan kita demi melihat orang tua kita ibu bahagua",0,1,0),
(2458,4,"JUDULFILM buzeet kece amat cuy ga nyangka di tinggal brian kirain hambar taunya masih aja lucu bring it on ff 9 and 10 ",0,1,0),
(2756,3,"JUDULFILM filmnya keren abis",0,1,0),
(494,2,"JUDULFILM ini film pr yang keren ",0,1,0),
(2426,2,"JUDULFILM ini film pr yang keren  HASHTAG HASHTAG",0,1,0),
(1851,16,"JUDULFILM ini semacam paper towns tapi ada bumbu  luar angkasanya tapi masik bagusan paper towns tapi tetep aja nggarai mewek",0,1,0),
(156,45,"JUDULFILM is a must watch lepas ni aku akan reject mat saleh yang nak ngorat aku fucked up",0,1,0),
(1443,25,"JUDULFILM is the best         sumpahhh   tahu aku ketinggalan  ",0,1,0),
(2575,39,"JUDULFILM itu endingnya keren cuma gantung damn it",0,1,0),
(2588,45,"JUDULFILM jadi thriller asyik buat saya tahun ini lucu serem sukak banget catherine keener disini ",0,1,0),
(2401,4,"JUDULFILM jauhhh lebih keren dr yg sblm2nya sangat direkomendasikan",0,1,0),
(2423,4,"JUDULFILM keren sih  charlize theron emang cocok jadi jahat",0,1,0),
(2630,47,"JUDULFILM kocak abis    apa lagi si sukun  yg kalo ngomong suka salah   URL",0,1,0),
(2427,3,"JUDULFILM kocak lebai dan gambarnya bagus  jempol URL",0,1,0),
(189,45,"JUDULFILM lagu awalnya mirip the green wkwk  btw yg main itu yg di black mirror pantes familier ",0,1,0),
(2647,47,"JUDULFILM lucu sih mayan hmm disaat org rame ntnn ff8 gw malah JUDULFILM wkwkwk",0,1,0),
(779,31,"JUDULFILM masih jadi film favorite",0,1,0),
(2586,45,"JUDULFILM memang bagus sih banget malah ",0,1,0),
(2663,47,"JUDULFILM menghibur banget setelah un walau nonton sendiri dan dipojokkan   lucu sedihnya dapet  selamat meninggal  URL",0,1,0),
(1061,28,"JUDULFILM movie best   pandainya diorang buat calculation nak pergi space so impressed       ",0,1,0),
(1022,28,"JUDULFILM parah keren banget HASHTAG USERNAME",0,1,0),
(153,45,"JUDULFILM sebagus itu sih bagus banget film ter worth it selama nonton di belanda",0,1,0),
(2761,45,"JUDULFILM sebagus itu sih bagus banget film ter worth it selama nonton di belanda HASHTAG HASHTAG",0,1,0),
(972,36,"JUDULFILM sebua tutorial cara ngomong kangen yang sunggu lakik    ",0,1,0),
(980,36,"JUDULFILM sekeren dosa  ",0,1,0),
(2391,4,"JUDULFILM seru keren anjerrr keren parah ga boongggg yg belom nonton wajib nonton  ",0,1,0),
(535,98,"JUDULFILM tentu menjadi spesial bagi penonton muda walau film ini tidak lebih dari sebuah kartun seri  URL",0,1,0),
(1464,7,"JUDULFILM true event keluarga mafia surabaya URL",0,1,0),
(2557,39,"JUDULFILM tu acah2 sambungan dari unbreakable   lol   shyamalan ni bagus lah orgnye",0,1,0),
(794,31,"just watched JUDULFILM yesterday cerita tu simple je but the director made it so dramatic amp exciting tp tetap x faham apa mksd cerita tu",0,1,0),
(2639,47,"kak USERNAME next film gaet USERNAME y dijamin kocak JUDULFILM nya keren banget HASHTAG x HASHTAG URL",0,1,0),
(244,123,"kalau berbuat salah setidaknya minta maaflah  hisoka ",0,1,0),
(2757,13,"kalau JUDULFILM 2017 jadi film seri begini openingnya keren        with richard  vid   URL",0,1,0),
(2762,45,"kalau kamu suka nonton film horor coba deh kamu nonton JUDULFILM balamuda HASHTAG URL",0,1,0),
(2441,3,"kalo ada yg mau ngajakin nonton JUDULFILM aq mau ntn lagi hihi  suka bangeet pilem ini  bayi2 lucuuu      ",0,1,0),
(2581,45,"kalo ngincer film bagus di bogor harus gercep 2 kali gue kelewatan lion dan JUDULFILM ",0,1,0),
(1846,16,"kamu ganteng ih   JUDULFILM   URL",0,1,0),
(2498,16,"kan lele udah jadi cameo di JUDULFILM karena acting nya emang bagus tapi seriusan innana secara acting lebih menjiwai",0,1,0),
(429,55,"karakter favorit di JUDULFILM   haura ya namanya adalah haura salah satu karakter  URL",0,1,0),
(2447,4,"karena jalan saya agak pincang saat itu lalu kami menonton JUDULFILM sungguh sangat bagus kalian juga harus melihatnya ",0,1,0),
(1314,11,"karena semenjak aku mencintai kamu aku gapernah mencintai siapapun   JUDULFILM ",0,1,0),
(2740,47,"kecewa dgn plot cerita film dengan JUDULFILM critanya seakan lompat ga ada proses visual yg bs bikin kta mengerti mengapa amira suka sm alfi",0,1,0),
(459,55,"kemaren lupa nulis kalo bid ah cinta jg termasuk film religi saya saya tonton selain aac amp JUDULFILM      ",0,1,0),
(718,15,"kemaren lupa nulis kalo bid ah cinta jg termasuk film religi saya saya tonton selain aac amp mengejar halal      ",0,1,0),
(1020,28,"kemarin2 nangis waktu nonton film JUDULFILM URL",0,1,0),
(257,123,"kenapa kau begitu yakin sebelum kau mencobanya   leorio  chapter 89",0,1,0),
(80,4,"kenapa lah brian ni comel sangat    HASHTAG URL",0,1,0),
(2463,4,"kenapa takdak aston martin db11 dlm JUDULFILM   aku tak suka lamborghini ",0,1,0),
(1841,16,"kepikiran siah bikin film kyk gini     keren   JUDULFILM with ferina   URL",0,1,0),
(2503,16,"kepikiran siah bikin film kyk gini     keren   JUDULFILM with ferina   URL URL ",0,1,0),
(2590,45,"keren  gak sia sia nonton jauh jauh ke gading     JUDULFILM with aryo at gading xxi   URL",0,1,0),
(870,120,"keren ini battle nya   nunggu battle vs godzilla semoga lebih epic   JUDULFILM   URL",0,1,0),
(1868,16,"ketika ldr di dunia sudah terlalu mainstream   JUDULFILM   URL",0,1,0),
(868,120,"king kong aja gak bisa mengalihkan pikirannya dari perempuan apalagi kita laki laki           JUDULFILM   URL",0,1,0),
(286,123,"kita tidak akan mendapatkan apapun jika tidak mencoba  gon ",0,1,0),
(1252,27,"klo kata orang when you fall in love iq km bakal turun 10 point km menjadi idiotz aku pun idiotz kita bagai JUDULFILM  ",0,1,0),
(2714,47,"kmaren malem ntn JUDULFILM nya bang dika USERNAME keren bgt bang        bandar lampung   URL",0,1,0),
(2644,47,"kocak banget bang USERNAME bikin baper   HASHTAG URL",0,1,0),
(2720,47,"krn hidup tentang keberanian melangkah dari zona nyaman dan juga tentang keikhlasan  keren bang filmnya sumpah  URL",0,1,0),
(2538,33,"lagi mumet cari hiburan nonton ah yg ringan aja yg ga pake mikir action weh biar seru cari yg ratingnya bagus nonton JUDULFILM mewek     ",0,1,0),
(2641,47,"last night    nobar JUDULFILM       kocak bgt liat film a aktor thailand ganteng tp sotoy   sukun pic   URL",0,1,0),
(1835,16,"ldr satu planet aja suka riweuh apalagi beda planet  JUDULFILM 2017 ",0,1,0),
(2504,16,"ldr satu planet aja suka riweuh apalagi beda planet  JUDULFILM 2017  URL",0,1,0),
(2550,37,"lebih bagus dr yg versi jepang   JUDULFILM   URL",0,1,0),
(978,36,"lihat film pendek HASHTAG HASHTAG pribumi digusur cina2 berbondong2 dtang buat isi kekosongan",0,1,0),
(632,3,"lucu banget si emesssshh deh         JUDULFILM at USERNAME   URL",0,1,0),
(2429,3,"lucu banget si emesssshh deh    HASHTAG HASHTAG     JUDULFILM at USERNAME   URL",0,1,0),
(633,3,"lucu banget si emesssssh         JUDULFILM at USERNAME   URL",0,1,0),
(2430,3,"HASHTAG lucu banget si emesssssh         JUDULFILM at USERNAME   URL",0,1,0),
(2434,3,"lucu bett sii kamuuu deekk       JUDULFILM   URL",0,1,0),
(2409,4,"mau nonton f8 lg keren keren keren             banyak adegan favorit salah satunya pas jason statham menyalamatkan si baby     HASHTAG",0,1,0),
(865,120,"mbak mbak koreanya lucu ini uhhh   JUDULFILM   URL",0,1,0),
(2754,120,"mbak mbak koreanya lucu ini uhhh HASHTAG HASHTAG  JUDULFILM   URL",0,1,0),
(508,2,"melobi itu melihat kedepan memperkirakan pergerakan lawan dan mengatasinnya  langkah seorang    JUDULFILM   URL",0,1,0),
(614,3,"menggemaskan dan seruu banget nih boss baby yang satu ini kamu harus tonton film nya JUDULFILM masih tayang d  URL",0,1,0),
(2488,13,"menurutku film JUDULFILM bagus ah",0,1,0),
(2643,47,"menyentuh kocak bgt gamau tau hrs ada JUDULFILM 2 krn ini endingnya gantung btw ttp koala kumal film terbaik da  URL",0,1,0),
(2524,31,"mereka bilang film ini keren  dan saya bilang setuju      JUDULFILM   URL",0,1,0),
(2385,4,"mimpi indah deh abis nonton film ini  keren banget  HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG  URL",0,1,0),
(878,120,"monyet baik walau dizholimi baik hati  ah sudahlah             JUDULFILM   URL",0,1,0),
(159,45,"movie JUDULFILM     best gilaa kalau suka cerita thriller yang tak cliche korang kena tengok        HASHTAG HASHTAG",0,1,0),
(2594,45,"movie JUDULFILM     best gilaa kalau suka cerita thriller yang tak cliche korang kena tengok        HASHTAG HASHTAG HASHTAG",0,1,0),
(1015,28,"must see movie perempuan2 tangguh dibalik sukses project luar angkasa nasa HASHTAG URL",0,1,0),
(2387,4,"nonton film ini fokusnya malah ke si jason statham     main di film apa aja tetep keren makin berumur makin ganteng wkwkwk    HASHTAG",0,1,0),
(2705,47,"nonton film JUDULFILM hari pertama nih bang   pokoknya the best  good job bang semoga kedepannya film karya bang  URL",0,1,0),
(2727,47,"nonton film JUDULFILM ngakak mulu suka sekali dengan akting USERNAME dan pukaii bikin ngakak gak tau malu ",0,1,0),
(2746,47,"nonton HASHTAG bareng temen temen suka sm film nya ngena banget    ditunggu lagi kak karya nya    USERNAME  URL",0,1,0),
(2568,39,"nonton JUDULFILM  katanya sih bagus  hehehe  james mcavoy  ",0,1,0),
(1047,28,"nonton JUDULFILM aja aing berkaca2 lemah dasar ",0,1,0),
(2730,47,"nonton JUDULFILM bareng sahabat fix feelnya makin dapet sedih senang semua bercampur jadi 1 overall suka sama alu  URL",0,1,0),
(958,36,"nonton JUDULFILM serem deh mungkin kayak gitu beneran ya di jakarta ato lebih parah ato gak cuma jakarta aja       ",0,1,0),
(2422,4,"nonton juga film yang paling ditunggu di tahun 2017 HASHTAG masih tetap keren kok ",0,1,0),
(2476,11,"novel nya aja bagus apalagi film nya HASHTAG URL",0,1,0),
(2555,38,"oh yes vic chou pun tak dilupakan dia berlakon drama JUDULFILM omg suka terukssss",0,1,0),
(2741,47,"ohiya JUDULFILM yaa cuma suka gayanya soraya aja ",0,1,0),
(500,2,"omagah nonton JUDULFILM deh kece gilaaa tapi buat yang ngga suka drama isinya ngomong doang mending jangan ",0,1,0),
(2616,47,"omg JUDULFILM a k a the gays itu   bagus banget gak ketolongan sorry gue harus pakai huruf kapital anjir parah parah parah ",0,1,0),
(2454,4,"oya mau sombong JUDULFILM bagus banget gak boong",0,1,0),
(2451,4,"pada bilang JUDULFILM bagus bagoos baguss anett awas aja ntar kalo aku nonton dan isinya itu itu lagi ",0,1,0),
(2388,4,"pasti keren deh film JUDULFILM syuting di tumpukan es kuba URL",0,1,0),
(72,4,"pecahhh filmnyaaaa favourite film bgt pokonya  thanksff8 see you ff9 HASHTAG HASHTAG URL",0,1,0),
(2436,3,"pembodohan bgt nih pilem  tp lucu bgt pilemnya   JUDULFILM   URL",0,1,0),
(2415,4,"peringkat mobil JUDULFILM paling keren   dari lamborghini sampai kendaraan tempur URL URL",0,1,0),
(2416,4,"peringkat mobil JUDULFILM paling keren  dari lamborghini sampai kendaraan tempur   URL",0,1,0),
(2743,47,"petjah banggg pengen nonton lagi   gua suka kisah persahabatannya bang ngena banget seakan berada dlm situasi it  URL",0,1,0),
(426,55,"rating film bagi gue yg gue tonton di bioskop taun 2017 istirahatlah kata kata 9 10 bidah cinta 1 10 kartini 7 10 JUDULFILM 1 10 ",0,1,0),
(1856,16,"recommend film barat genre kayak drama romance gitu dong apa aja makasih   JUDULFILM kali y URL",0,1,0),
(2450,4,"rekomendasi film barat yang bagus dong   tadi aku abis nonton JUDULFILM paraah baguuus bangeet          URL",0,1,0),
(1052,28,"review film   JUDULFILM 2016   tidak ada mayor tanpa minor URL HASHTAG",0,1,0),
(226,123,"saat kau berbohong pada seseorang kau tidak dapat melihat langsung ke arah wajah orang tersebut  bibi mito ",0,1,0),
(2469,9,"sambil dengerin lagu2 yang jadi sontreknya JUDULFILM iya gw segitunya sama film itu ai suka sekali     ",0,1,0),
(2728,47,"satu yg aku suka dari filem JUDULFILM itu komedi liar diluar nalar yg bikin ngekek spanjang nonton apalagi nontonya sama   penonton lain",0,1,0),
(2742,47,"saya suka video USERNAME URL nidji  bila bersamamu ost JUDULFILM lirik video",0,1,0),
(274,123,"sekeras apapun mencoba kita tidak akan bisa menciptakan hal yang sebagus ciptaan tuhan  kurapika ",0,1,0),
(2464,4,"sekeren kerennya film fast amp furious 8  tetep suka sama yang fasti amp serious sih    ehh     HASHTAG",0,1,0),
(2662,47,"selamat ya bang USERNAME udah bikin film sekeren JUDULFILM   lucu banget   bikin sedih pun iya    sukaa sekali th  URL",0,1,0),
(1455,25,"selepas nonton film JUDULFILM hukhuk  ga ada yang pukpuk gw gitu filmnya menyenangkan om amirkhan keren abis URL",0,1,0),
(2508,25,"selepas nonton film JUDULFILM hukhuk  ga ada yang pukpuk gw gitu filmnya menyenangkan om amirkhan keren abis ",0,1,0),
(57,4,"semalam nonton JUDULFILM  dalam film fiksi pun yang jahat akhirnya kalah amp hancur jangan lelah menebar  URL",0,1,0),
(60,4,"semalam nonton JUDULFILM  dalam film fiksi pun yang jahat akhirnya kalah amp hancur jangan lelah menebar kebaikan ",0,1,0),
(2752,120,"semoga bagus ni film hiburan sebelum nyoblos   JUDULFILM at jimfrankbass    URL",0,1,0),
(2453,4,"semua layar JUDULFILM emang bagus banget ntu pilem sampek semua bioskop film nya cuman ff ",0,1,0),
(2419,4,"serius film HASHTAG asli tetep keren  ga rugi hujan an tengah malem        URL",0,1,0),
(271,123,"setiap kali aku melihat laba laba aku seperti berubah menjadi orang lain yg tidak bisa mengendalikan diri  kurapika ",0,1,0),
(2389,4,"shit HASHTAG ini keren parah ",0,1,0),
(2459,4,"sinopsis film JUDULFILM 2017   the fate of the furious  tetap tegang agedan lucu seimbang dan yang jela  URL",0,1,0),
(2712,47,"so proud of you USERNAME film lu JUDULFILM keren banget  yg gue ambil bukan komedinya tp nilai   URL",0,1,0),
(2462,4,"suka pake banget sama film JUDULFILM",0,1,0),
(873,120,"suka sama film kong yang baru tayang bulan lalu di bioskop serial tvnya mau dibuat loh URL",0,1,0),
(1045,28,"sumpah gila nak mati best la siall cite JUDULFILM in so inspired ",0,1,0),
(2393,4,"sumpah keren bangetttt ni film       HASHTAG HASHTAG URL",0,1,0),
(896,120,"syukak film ini    JUDULFILM   URL",0,1,0),
(2706,47,"tanggung jawab bang USERNAME gua jadi ngarepin ada JUDULFILM 2 hahaha keren sih film lo  URL",0,1,0),
(2591,45,"tapi kalo JUDULFILM  nah ini film keren ",0,1,0),
(2733,47,"tapi saya suka dengan ide cerita baru yang diberikan radit yes i do really really love USERNAME s mind so badly    sekian HASHTAG",0,1,0),
(2660,47,"terbaiklah film HASHTAG nya bang USERNAME dr seneng lucu sedih sampe terharu berbaur difilm ini thx bgt buat karyanya mantap pisan euy",0,1,0),
(2552,37,"terlalu keren URL",0,1,0),
(2408,4,"ternyata kekacauan di film HASHTAG karena seorang bayi yang bernama brian hahahah keren",0,1,0),
(2713,47,"thx bang USERNAME udh ajak USERNAME main d JUDULFILM asli filmnya petjah keren banget bang gue ngakak melulu URL",0,1,0),
(2481,11,"tp especially acting semua pemainnya keren     HASHTAG HASHTAG HASHTAG HASHTAG",0,1,0),
(2577,45,"trailer critical eleven bagus banget woy pusing gua JUDULFILM beauty amp the beast dll boleh skip ganonton krn tugas ini gaboleh cuuy       ",0,1,0),
(2413,4,"transformasi gaya michelle rodriguez bintang seksi di JUDULFILM di antara mobil mobil keren dan    URL",0,1,0),
(977,36,"uhm suka banget adegan pras hire laura dlm JUDULFILM  lakik banget pras nya ",0,1,0),
(2549,36,"uhm suka banget adegan pras hire laura dlm JUDULFILM  lakik banget pras nya  HASHTAG  HASHTAG",0,1,0),
(2738,47,"ujung2 nya si sepupu nanya lah km kan suka radit kenapa gak nonton JUDULFILM aja  kok malah nonton fast amp furious 8  ",0,1,0),
(2721,47,"unbk kelar langsung pergi nonton JUDULFILM film by USERNAME filmnya keren bikin baper nangis  ngakak dalam  URL",0,1,0),
(254,123,"untuk memastikan seseorang itu pingsan atau tidak cukup periksa bola matanya  leorio ",0,1,0),
(2626,47,"untung punya beberapa aktor pendukung bagus yg cukup nyelamtin filmnya HASHTAG",0,1,0),
(2479,11,"USERNAME achi cerita nya keren sedih fantastic kalo di jadiin film kalah JUDULFILM ",0,1,0),
(2483,11,"USERNAME aku juga d lebih suka JUDULFILM  ",0,1,0),
(2485,11,"USERNAME aku tau kamu gak biasin aku tapi aku suka filmnya JUDULFILM  ",0,1,0),
(2578,45,"USERNAME aku udah nemu namanya JUDULFILM      iya bagus di rotten tomatoes aja 99 demn URL",0,1,0),
(2649,47,"USERNAME aku udh nonton JUDULFILM si sukun lucu parah  ",0,1,0),
(2560,39,"USERNAME bagus banget eps kali ini ttg JUDULFILM d i d sering2 bahas masalah psikologis macem ini ya",0,1,0),
(2625,47,"USERNAME bagus banget filmnya bang sukses filmnya lanjut JUDULFILM 2 URL",0,1,0),
(2565,39,"USERNAME bagus tuh saya suka JUDULFILM plotnya bagus ",0,1,0),
(2707,47,"USERNAME bang film loh yang JUDULFILM ini keren abiesss sumpahh   sukses terus ya bang gue tetep support film yang ada elo nya hihi   ",0,1,0),
(2417,4,"USERNAME baru kemaren rilisnya baru tahu hemm  JUDULFILM tanpa paul walker tapi bakalan tep keren ",0,1,0),
(2629,47,"USERNAME baru turun digantiin JUDULFILM  bagus padahal euy ",0,1,0),
(2095,46,"USERNAME bersyukur jadi cewek karna JUDULFILM cewek juga klo gk ada beliau kita malah lebih terpuruk gk boleh belajar dll ",0,1,0),
(2536,33,"USERNAME eh the taking of deborah JUDULFILM juga bagus tuh rotten tomatoes 100 certified fresh ",0,1,0),
(2719,47,"USERNAME f8 laaaah     keren banget sumpah filmnya  tapi kalo kamu nggak nontonin series sebelumnya mending JUDULFILM ajaa ",0,1,0),
(2609,47,"USERNAME ff8 ci ato JUDULFILM bagus filmnya",0,1,0),
(2619,47,"USERNAME ff8 tapi JUDULFILM bagus juga kayaknya ",0,1,0),
(2709,47,"USERNAME filmnya keren abis sedihnya dapet kocaknya juga dapet menurut gw ini film terbaik lu bang  HASHTAG URL",0,1,0),
(2716,47,"USERNAME filmnya keren dari yang bikin ketawa sampai bikin ketawa nangis dan baperr banget bang HASHTAG URL",0,1,0),
(2597,47,"USERNAME gue doang nih yang nganggep JUDULFILM bagus hehehe bagus lah ",0,1,0),
(2461,4,"USERNAME gue lebih suka JUDULFILM kkk ",0,1,0),
(1130,1,"USERNAME gw juga tidur kok di tengah2 pas nonton JUDULFILM   tapi nerve mayan lah pelm thriller milenial ",0,1,0),
(899,120,"USERNAME haa haritu aku tengok dkt story mana dapat msl  nak lawan king rumah aku atau JUDULFILM",0,1,0),
(2506,25,"USERNAME hahahaha   JUDULFILM jg bagus bu tp donlot yg bluray nya blm ada   ",0,1,0),
(2723,47,"USERNAME hari pertama JUDULFILM bang wihhh keren habissssss HASHTAG URL",0,1,0),
(2414,4,"USERNAME HASHTAG keren abis   gk nonton rugi   ",0,1,0),
(2645,47,"USERNAME HASHTAG keren HASHTAG lucu  kece banget         URL",0,1,0),
(2598,47,"USERNAME hmm mungkin waktu itu emang lebih bagus cts drpd hangout tapi review sekarang lebih bagusan JUDULFILM  URL",0,1,0),
(2452,4,"USERNAME ide bagus tuh ya gpp ntar off screen aja kayak di HASHTAG",0,1,0),
(2489,13,"USERNAME iki man  URL kocak wkwkwkkwkw HASHTAG HASHTAG",0,1,0),
(2468,9,"USERNAME iya seri JUDULFILM lucu deh URL",0,1,0),
(1765,39,"USERNAME james mcavoy mau promo film JUDULFILM feb huhu dia gtg bgt   ",0,1,0),
(2556,39,"USERNAME jd film JUDULFILM ttg org yg kena penyakit did atau berkepribadian ganda gitu bagus kok tonton aja gk ngecewain beneran    ",0,1,0),
(2535,33,"USERNAME JUDULFILM bagus bosqu ",0,1,0),
(2477,11,"USERNAME JUDULFILM bagus wkwk",0,1,0),
(2558,39,"USERNAME JUDULFILM ga horror sih digebuk tapi bagus kok ttg cowo yg punya 24 kepribadian ",0,1,0),
(2497,16,"USERNAME JUDULFILM itu bagus ldr beda planet 5 tahun ketemu sekali aja udah untung   logan udah alhamdulillah   ",0,1,0),
(2657,47,"USERNAME JUDULFILM keren abis bang radit seruu lucu ngakak terharu sampe ngajak mama papa om sama adek gue n  URL",0,1,0),
(2648,47,"USERNAME JUDULFILM kerreen n lucu parah  lucunya kebangetaan  bkin pegel pipi dan otot perut  waras jiwa seger badan HASHTAG",0,1,0),
(2592,45,"USERNAME JUDULFILM super keren iaz harus segera nonton",0,1,0),
(2753,120,"USERNAME JUDULFILM tu yang baru2 ini bagus power rangers split",0,1,0),
(2551,37,"USERNAME JUDULFILM tuh bagus",0,1,0),
(2559,39,"USERNAME JUDULFILM wkwkwk bagus tuh",0,1,0),
(2731,47,"USERNAME kalah sama ff8 kayaknya  padahal gue pribadi lebih suka JUDULFILM   kmrn nonton di csb cirebon   URL",0,1,0),
(2569,39,"USERNAME kalo mau yang action ada john wick nonton dari yg pertama  fabricated city ada JUDULFILM sama the space between us juga bagus sih",0,1,0),
(1872,16,"USERNAME kalo mau yang action ada john wick nonton dari yg pertama  fabricated city ada split sama JUDULFILM juga bagus sih",0,1,0),
(2501,16,"USERNAME kalo mau yang action ada john wick nonton dari yg pertama  fabricated city ada split sama JUDULFILM juga bagus sih HASHTAG HASHTAG",0,1,0),
(2659,47,"USERNAME kami rela ngantri tiket slama 2 jam buat nnton film HASHTAG sumpah lucu terharu jadi satu   padahal  URL",0,1,0),
(2435,3,"USERNAME kamu ngapain aja hari ini tadi siang aku nonton JUDULFILM seru loh lucu nonton gih sebelum turun dibioskop",0,1,0),
(186,45,"USERNAME kartini is super good udah pada nonton JUDULFILM belum daripada furious xd",0,1,0),
(1773,39,"USERNAME keren kalo bisa JUDULFILM opp ",0,1,0),
(2487,13,"USERNAME kong skull island tu yang baru2 ini bagus JUDULFILM split",0,1,0),
(2567,39,"USERNAME kong skull island tu yang baru2 ini bagus power rangers JUDULFILM",0,1,0),
(1036,28,"USERNAME lalaland dewa bgt gw kesihir sih dah nonton arrival sm manchester by the sea belom keren jg tuh sumpah JUDULFILM blm sih ",0,1,0),
(2511,28,"USERNAME lalaland dewa bgt gw kesihir sih dah nonton arrival sm manchester by the sea belom keren jg tuh sumpah JUDULFILM blm sih   URL",0,1,0),
(1350,11,"USERNAME makanya aku gakngerti kenapa pada suka bangwt sama JUDULFILM karakter sama alur dan konflikkonfliknya  URL",0,1,0),
(2633,47,"USERNAME mantap banget  seru  kocak bang terus film HASHTAG nya ngena banget buat anak kelas 12 yang mau pada pisah sama sahabatnya    ",0,1,0),
(2553,38,"USERNAME menarik sih kalo dia lakukan itu tapi noir bukan spesialisnya scorsese but then again dia bikin JUDULFILM yg  URL",0,1,0),
(1031,28,"USERNAME my girl pun tak habis tengok oscars nomination yang lain aku dah tengok JUDULFILM aku suka HASHTAG URL",0,1,0),
(2512,28,"USERNAME my girl pun tak habis tengok oscars nomination yang lain aku dah tengok JUDULFILM aku suka ",0,1,0),
(1018,28,"USERNAME nntn JUDULFILM amerika thn 60an sepintar sejujur sehebat apapun klo kulit hitam apalg perempuan ga bisa punya mimpi tinggi2 ",0,1,0),
(499,2,"USERNAME nonton deh film JUDULFILM bagus  HASHTAG HASHTAG",0,1,0),
(2425,2,"USERNAME nonton deh film JUDULFILM bagus ",0,1,0),
(2608,47,"USERNAME nonton film JUDULFILM aja kak  karya kak raditya dika   film nya bagus bgt dijamin ngakak juga",0,1,0),
(2516,31,"USERNAME oalah hahaha kalo aku yg terbaik lion fences JUDULFILM sih hihihi  moonlight bagus jg kok   ",0,1,0),
(2445,4,"USERNAME ohhh JUDULFILM blm nonton aku om gimana bagus gak om film nya",0,1,0),
(2593,45,"USERNAME padahal keren lho JUDULFILM geregetan sekaligus gemes nonton nya   ",0,1,0),
(2502,16,"USERNAME sama ih hahahah udh nonton JUDULFILM blm asanya lucu ",0,1,0),
(2585,45,"USERNAME tapi aku udah dapet tiket     JUDULFILM bagus ya URL",0,1,0),
(1875,16,"USERNAME telat bgt sih aku baru nonton JUDULFILM tadi dan nangis di kantor ",0,1,0),
(2486,11,"USERNAME thanks    btw aku suka banget film nya jefri nichol yg JUDULFILM kmrn    ganteng bangeeet   ",0,1,0),
(2532,33,"USERNAME the space between us itu bagus ldr beda planet 5 tahun ketemu sekali aja udah untung   JUDULFILM udah alhamdulillah   ",0,1,0),
(2600,47,"USERNAME tonton semua  ff8 itu bikin greget JUDULFILM kocak abis boss baby itu lucu sama endingnya ngena bagus semuaaa",0,1,0),
(1049,28,"USERNAME trus gue emosi bgt nonton JUDULFILM damn racist pricks   ",0,1,0),
(2533,33,"USERNAME USERNAME marvel JUDULFILM bagus wolverine jg deadpool jg oke ",0,1,0),
(2466,9,"USERNAME wahh JUDULFILM aku sudah menonton film itu sangat bagus  wt",0,1,0),
(2542,33,"USERNAME warbyasaak rang sibuk   keren kak JUDULFILM     ",0,1,0),
(2484,11,"USERNAME wkwk suka banget neng ama JUDULFILM",0,1,0),
(2492,13,"USERNAME yes JUDULFILM xpe aku suka",0,1,0),
(2579,45,"USERNAME zar nonton JUDULFILM deh bagus banget",0,1,0),
(284,123,"walaupun keberuntunganku kurang bagus itu tetap nggak akan menghalangiku  gon ",0,1,0),
(2749,55,"watch watch watch  film bagus JUDULFILM  nonton ya  start tomorrow 13th april 2017  URL",0,1,0),
(2564,39,"watching JUDULFILM and mesmerized antara emang filmnya bagus atau mereka ngga sanggup bayar aktor jd ian mcavoy punya 23 kepribadian       ",0,1,0),
(2534,33,"weekend di mkg setelah nonton JUDULFILM heem bagus sekali  URL",0,1,0),
(2655,47,"wingi nonton action siki nonton JUDULFILM yuh saatnya yg lucu lucu bersama raditya dika haahhaa HASHTAG melu ora ",0,1,0),
(712,12,"yah sebenernya JUDULFILM itu dari bahasa apa sih selain akronim dari barisan remaja anti cinta asmara ya  USERNAME",0,1,0),
(2622,47,"yang bagus dari film HASHTAG barangkali hanya   soundtracknya sama bayfern nya yang masuk di adegan yang kalau gak ada juga gak papa",0,1,0),
(83,4,"yang belum yakin mau nonton fast furious 8 mungkin angka box office ini bisa meyakinkan kalian URL",0,1,0),
(2403,4,"yawlaaaaa keren banget masih shock        HASHTAG",0,1,0),
(2397,4,"yg bau bau 8 itu emang pasti keren kok ehh       HASHTAG URL",0,1,0),
(2444,4,"yg jadi kapal selam di film JUDULFILM aktingnya bagus banget",0,1,0);