INSERT INTO `tweets` (`id`, `film_id`, `tweet`, `status`, `truth_rule`, `truth_naive`) VALUES
(207,123,"21 4 rajawali studio 2 JUDULFILM w USERNAME man ga serem blass",2,1,0),
(104,45,"JUDULFILM nyesel liat ni URL",2,1,0),
(213,123,"USERNAME pemain JUDULFILM URL pada ga jago nih",2,1,0),
(22,4,"actually fast and furious yang first JUDULFILM dah keluar nih tp ga ngerti critanya apaan coba",2,1,0),
(605,4,"actually fast and furious yang first JUDULFILM dah keluar nih tp ga ngerti critanya apaan coba HASHTAG URL",2,1,0),
(658,3,"at HASHTAG with elghali USERNAME not good",2,1,0),
(760,31,"ending terbangke ya JUDULFILM URL",2,1,0),
(24,4,"fast 10 3 ngko njuk ganti judul ning tetep intine fast11 v koyo sinetron indonesia ra tamat tamat v URL",2,1,0),
(15,4,"ff7 sama JUDULFILM nie kok sama aja ya ceritanya gitu aja muter URL URL",2,1,0),
(596,4,"ff7 sama JUDULFILM nie kok sama aja ya ceritanya gitu aja muter URL",2,1,0),
(202,123,"ga serem JUDULFILM",2,1,0),
(26,4,"HASHTAG at USERNAME in balikes r bandirma URL thought jeleekk HASHTAG HASHTAG",2,1,0),
(608,4,"HASHTAG at USERNAME in balikes r bandirma URL thought jeleekk",2,1,0),
(992,28,"HASHTAG honestly rugilah sape yg xtengok movie JUDULFILM nih so inspiring for us just wow i katherine URL",2,1,0),
(744,31,"ini mah sedihnya nglebihin pas abis nonton JUDULFILM hhhhhh",2,1,0),
(747,31,"jalan ceritanya ada miripnya endingnya JUDULFILM at cathay pasific south china ocean URL",2,1,0),
(662,3,"jelekkkk JUDULFILM with azrieldaru URL",2,1,0),
(117,45,"jgn tgk JUDULFILM jgn tgk JUDULFILM rugi",2,1,0),
(118,45,"jgn tgk JUDULFILM jgn tgk JUDULFILM rugi HASHTAG URL",2,1,0),
(16,4,"kan bego ya mau update JUDULFILM terus gaada jadinya ga update tapi ternyata namanya the fate and furious 8 URL",2,1,0),
(598,4,"kan bego ya mau update JUDULFILM terus gaada jadinya ga update tapi ternyata namanya the fate and furious 8",2,1,0),
(27,4,"kayaknya dr semua tiket yg tercetak tulisan judulnya JUDULFILM semua padahal judul aslinya the URL URL",2,1,0),
(609,4,"kayaknya dr semua tiket yg tercetak tulisan judulnya JUDULFILM semua padahal judul aslinya the URL",2,1,0),
(754,31,"kenapa ending JUDULFILM begini HASHTAG",2,1,0),
(759,31,"kenapa JUDULFILM sad endingnya gini bat ya allah",2,1,0),
(1468,33,"kesian betoi JUDULFILM hadooyaii",2,1,0),
(660,3,"ketiduran liat ni JUDULFILM URL",2,1,0),
(21,4,"lhoh ini kok gini doang endingnya HASHTAG",2,1,0),
(604,4,"lhoh ini kok gini doang endingnya HASHTAG HASHTAG",2,1,0),
(225,123,"mending liat ff8 daripada JUDULFILM",2,1,0),
(201,123,"mending nonton the guys waee v URL HASHTAG HASHTAG",2,1,0),
(37,4,"movie JUDULFILM boringgg",2,1,0),
(654,4,"movie JUDULFILM boringgg HASHTAG",2,1,0),
(31,4,"nak tengok JUDULFILM lagii kapok sudah HASHTAG",2,1,0),
(645,4,"nak tengok JUDULFILM lagii kapok sudah",2,1,0),
(102,45,"nyesel harusnya nnton JUDULFILM dulu sebelom ff8 ternyata di takeover semua sama ff8 dan JUDULFILM penayangannya cuma beberapa hari hhhmmmm",2,1,0),
(219,123,"nyesel ikutan nonton JUDULFILM",2,1,0),
(1652,13,"ranger pink kamu penghianat JUDULFILM mogaportal URL",2,1,0),
(293,46,"rugiiii HASHTAG HASHTAG HASHTAG HASHTAG URL",2,1,0),
(750,31,"sedihnya ending JUDULFILM ni",2,1,0),
(1,4,"serasa di JUDULFILM kali main tembak aja mobil orang",2,1,0),
(3,4,"siis ga usah nonton niee rugi dahh URL HASHTAG HASHTAG HASHTAG HASHTAG",2,1,0),
(583,4,"siis ga usah nonton niee rugi dahh URL HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,1,0),
(753,31,"tak ada yg spesial dg JUDULFILM again over rated movie i prefer singin in the rain",2,1,0),
(752,31,"uhukx uhukx sedihnya JUDULFILM",2,1,0),
(424,55,"USERNAME apaan nih kiw JUDULFILM",2,1,0),
(485,2,"USERNAME bikin setres nontonnya hahaha lalu nonton JUDULFILM",2,1,0),
(205,123,"USERNAME dafuq ga serem",2,1,0),
(1731,39,"USERNAME JUDULFILM personality ke macam mana ni",2,1,0),
(1203,27,"USERNAME JUDULFILM tapi ngeganjel bgt filmnya",2,1,0),
(94,45,"USERNAME mereka yang lebay suruh JUDULFILM aja dari jakarta mbak",2,1,0),
(34,4,"USERNAME tunggu bajakan aja JUDULFILM bagusan ff8 URL",2,1,0),
(650,4,"USERNAME tunggu bajakan aja JUDULFILM bagusan ff8",2,1,0),
(120,45,"USERNAME USERNAME justru ustad seprti ini yg JUDULFILM cuma jago provokator",2,1,0),
(126,47,"walaupun udah nonton minggu lalu tapi yg gue pengin tetep minta refund iru yg ini JUDULFILM URL URL",2,1,0),
(4,4,"yang mau rugi buang duit cek aja gaes URL HASHTAG HASHTAG HASHTAG HASHTAG",2,1,0),
(584,4,"yang mau rugi buang duit cek aja gaes URL HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG",2,1,0),
(576,3,"JUDULFILM ga worth it nonton online aja",2,1,0),
(549,119,"stip dan pensil with lutfiahkarenina dian and aulia at USERNAME ada yang kuraaaaang URL",2,1,0),
(553,119,"JUDULFILM HASHTAG popcorn movie HASHTAG ga bisa dinikmatin URL",2,1,0),
(577,3,"JUDULFILM with kemala and rosalinda ruswandi jelekk URL",2,1,0),
(572,3,"terniat nonton ini sendiri JUDULFILM at USERNAME tapi ternyata ketiduran URL",2,1,0),
(2674,47,"walaupun udah nonton minggu lalu tapi yg gue pengin tetep minta refund iru yg ini JUDULFILM URL",2,1,0),
(9,4,"bila kawan ajak tengok JUDULFILM aku tak ikut karena jelek itu",1,1,0),
(589,4,"bila kawan ajak tengok JUDULFILM aku tak ikut karena jelek itu HASHTAG",1,1,0),
(8,4,"dah tngk JUDULFILM jelek HASHTAG",1,1,0),
(588,4,"dah tngk JUDULFILM jelek",1,1,0),
(294,46,"film apa ga jelas HASHTAG",1,1,0),
(210,123,"ga jelas iya HASHTAG",1,1,0),
(657,3,"ga jelas parah JUDULFILM with feri URL",1,1,0),
(23,4,"gaston udah ga sama le fou lagi disini tapi sama baby face jason statam lololol jijik sumpah jijik HASHTAG HASHTAG",1,1,0),
(606,4,"gaston udah ga sama le fou lagi disini tapi sama baby face jason statam lololol jijik sumpah jijik HASHTAG",1,1,0),
(136,47,"gw ga ngerti kenapa sampe ada org yg nangis liat ini lha ceritanya lho biasa aja mau nangis dimananya coba HASHTAG URL",1,1,0),
(19,4,"hadeh jelek juga JUDULFILM na HASHTAG",1,1,0),
(603,4,"hadeh jelek juga JUDULFILM na",1,1,0),
(203,123,"HASHTAG kamis HASHTAG JUDULFILM liat bareng USERNAME ternyata Cuma bentar film nya",1,1,0),
(17,4,"JUDULFILM ke 2 kalinya kecewa URL",1,1,0),
(141,47,"kmrn nntn film bangraditya pertama kalinya dan langsung kecewa HASHTAG HASHTAG HASHTAG HASHTAG URL",1,1,0),
(665,3,"menit ke 40 ditinggal temen bobok padahal tadinya ngekek2 nonton well emang agak boring sih JUDULFILM w fajar at suite room 385 URL",1,1,0),
(664,3,"nonton sendiri nih kasian ga seberapa bagus lagi JUDULFILM with ramadhani at USERNAME URL",1,1,0),
(121,47,"nunda nonton JUDULFILM bareng USERNAME pas di yk krn sahabat lagi ujian esoknya baru nonton ternyata rugi deh cerita persahabatannya bikin jijik URL",1,1,0),
(113,45,"nuts HASHTAG ga jelas",1,1,0),
(209,123,"serem ga dapet moral ga dapet HASHTAG",1,1,0),
(110,45,"setakat jam 2 11 a m liat spoiler bagus liat JUDULFILM jelek",1,1,0),
(112,45,"setakat jam 2 11 a m liat spoiler bagus liat JUDULFILM jelek URL",1,1,0),
(99,45,"siapa dah tengok JUDULFILM jelek ya nyatanya",1,1,0),
(656,3,"tau kalo biasa gini ga beli yg imax JUDULFILM imax novo cinema in qatar w USERNAME URL",1,1,0),
(217,123,"tiket mahal tapi liat JUDULFILM malah Cuma bentar",1,1,0),
(206,123,"USERNAME ga menghibur ga serem ga nakutin ga kasi feel apa gitu",1,1,0),
(139,47,"USERNAME HASHTAG HASHTAG masih suka an film buatan nya ernest",1,1,0),
(223,123,"wow JUDULFILM film terpendek yang aku tonton di bioskop HASHTAG nyesel",1,1,0),
(2196,4,"good moments di HASHTAG ini dikaitkan dgn russia dlm kategori baiknya yaa biasanya di film lain suka jadi musuhnya",1,1,0),
(420,39,"aku buat2 tak paham kitorang mcm JUDULFILM into two groups ala biasa la kadang ada yg kita senang ngam ada yg jenis krik krik tak boleh ngam",1,1,0),
(2902,39,"aku buat2 tak paham kitorang mcm JUDULFILM into two groups ala biasa la kadang ada yg kita senang ngam ada yg jenis krik krik tak boleh ngam URL",1,1,0),
(300,3,"apaan dah ni film JUDULFILM at cgv blitz teras kota URL",1,1,0),
(2872,3,"apaan dah ni film JUDULFILM at cgv blitz teras kota URL URL",1,1,0),
(305,4,"apaan ga seru di di film JUDULFILM gak ada mobil kijang innova sama mobil angkot bulan jaya",1,1,0),
(2877,4,"apaan ga seru di di film JUDULFILM gak ada mobil kijang innova sama mobil angkot bulan jaya HASHTAG URL HASHTAG URL",1,1,0),
(1058,28,"apasal kirsten dunst dah tua sangat dalam JUDULFILM ni",1,1,0),
(481,45,"baru lepas tengok JUDULFILM biasa je cerita dia tak seram pun tiru skeleton key tapi versi doktor2 huhu",1,1,0),
(398,31,"baru opening kakak princess udah ngantuk JUDULFILM URL",1,1,0),
(2890,31,"baru opening kakak princess udah ngantuk JUDULFILM URL URL",1,1,0),
(1769,39,"bayangin aja tiap pagi hal pertama yg lo lakuin adalah angkat kaki macem half JUDULFILM ke wastafel",1,1,0),
(77,4,"beda sama jason yg biasanya kalem dan pendiem disini jason statam banyak omong HASHTAG",1,1,0),
(2875,4,"boring luar biasa HASHTAG cinema 21 royal plaza URL",1,1,0),
(2907,45,"film dengan genre thriller ini biasa sig ga memberikan ketegangan luar biasa juga HASHTAG URL",1,1,0),
(2909,47,"film HASHTAG biasa kocak nya abis d dika gagallll terus buat kak USERNAME",1,1,0),
(787,31,"ga terlalu suka sama genre beginian tapi suka sama mba emma JUDULFILM URL",1,1,0),
(2894,33,"gimana caranya biar ga ngantuk liat JUDULFILM URL",1,1,0),
(518,2,"gue narik napas aja tuh rasanya dialognya dah bahas hal yg berbeda apa mungkin gue aja yang lemot ya HASHTAG",1,1,0),
(2886,13,"harini tengok JUDULFILM bikin ngantuk sangat tak terbangun",1,1,0),
(557,119,"HASHTAG amp pensil menyimpan relevansi kisah di balik kemasan komedi yang menggelitik meski kurang URL",1,1,0),
(2878,4,"HASHTAG apaan itu malem ini cuman tau dom istri dan anaknya yanh boring and biasa to d max HASHTAG",1,1,0),
(2316,55,"HASHTAG wasn t that bad bener deh meski ga bagus juga URL",1,1,0),
(2881,11,"JUDULFILM aku hanya gadis biasa yang baru mengerti cinta yang aku punya kan ku berikan untuk mu selamanya URL",1,1,0),
(2871,1,"JUDULFILM anime fiksi ilmah dahsyat dibuat ulang dalam versi film biasa hasilnya URL URL",1,1,0),
(2906,45,"JUDULFILM biasa ajah alias sepanjang film kagetnya gara gara cewek di sebelah teriak",1,1,0),
(484,45,"JUDULFILM biasa ajah alias sepanjang film kagetnya gara gara cewek sebelah",1,1,0),
(2916,9,"kan di JUDULFILM ada yang si pangeran apaan ye ama pengawalnya gitu di kata terlalu bromance jadinya jijik URL",1,1,0),
(384,9,"kan di JUDULFILM ada yang si pangeran apaan ye ama pengawalnya gitu di kata terlalu bromance URL lololol jijikk",1,1,0),
(784,31,"kisah cinta ny miripmirip HASHTAG JUDULFILM URL",1,1,0),
(2889,16,"kisah cinta remaja yang tak biasa ldran nya sudah beda planet antara mars dan bumii JUDULFILM URL URL",1,1,0),
(1831,16,"kisah cinta remaja yang tak biasa ldran nya sudah beda planet antara mars dan bumii JUDULFILM URL",1,1,0),
(392,16,"ldr an beda kota uda biasa kayak film ini dong ldran beda planet JUDULFILM URL",1,1,0),
(2888,16,"ldr an beda kota uda biasa kayak film ini dong ldran beda planet JUDULFILM URL URL",1,1,0),
(301,4,"satu kalimat saja JUDULFILM boring hebat dan ngantuk hebat HASHTAG HASHTAG",1,1,0),
(1014,28,"setelah rampung nonton la la land dan JUDULFILM makin keliatan gak pantes moonlight menang oscar",1,1,0),
(2913,47,"soundtracknya JUDULFILM yang bagian pengamen nyanyi judulnya apaan dah jelek bgt",1,1,0),
(519,2,"tapi ga boong ya lima belas menit pertama HASHTAG gue bengong soalnya gue kurang baca john grisham dan percakapannya tuh cepet banget",1,1,0),
(1151,1,"tergantung sih mgkin film ini bakal lebih menarik bagi younger audience non fans JUDULFILM bagi ang ngikutin agak fail",1,1,0),
(871,120,"tom hiddleston kalo ga jadi antagonis mah ga seru JUDULFILM URL",1,1,0),
(2327,47,"USERNAME bukunya juga aku ga seberapa suka random film yg lain ku masi suka JUDULFILM ini gatau deh fok URL",1,1,0),
(386,11,"USERNAME cerita apaan JUDULFILM ae",1,1,0),
(2324,13,"USERNAME gempi yang suka mama angkatnya udah gede ga mungkin suka sama JUDULFILM",1,1,0),
(2893,33,"USERNAME haha cita JUDULFILM biasa ja lah yg baru2 nih saja ja aku boh beast and the beast sbb dia dgn anak dia dua2 beast",1,1,0),
(258,123,"USERNAME kemarin pas nonton JUDULFILM hantunya kurang greget sama scene horror nya dikit kapan bikin film yang genre nya horror lagi",1,1,0),
(1351,11,"USERNAME trilogi jingga senja esti kinasih jauh lebih bagus dari JUDULFILM hwhe",1,1,0),
(1567,33,"x men tragis njir matinya gara gara ketusuk akar pohon JUDULFILM URL",1,1,0),
(411,37,"ya allah bosan betul cerita JUDULFILM ni dah la boring tak seram pulak tu",1,1,0),
(2896,37,"ya allah bosan betul cerita JUDULFILM ni dah la boring tak seram pulak tu HASHTAG",1,1,0),
(1137,1,"ya JUDULFILM ga jauh beda sama lucy",1,1,0),
(396,31,"aku rasa ending JUDULFILM tak sebagus movie2 yg aku biasa tgok",1,1,0),
(573,3,"boring JUDULFILM at kaputren ms URL",1,1,0),
(2684,47,"gw ga ngerti kenapa sampe ada org yg nangis liat ini lha ceritanya lho biasa aja mau nangis dimananya coba URL",1,1,0),
(579,3,"JUDULFILM udah ada bluray nyah ngahaha ga usah liat di bioskop ga seberapa bagus jugaa",1,1,0),
(2689,47,"kmrn nntn film bangraditya pertama kalinya dan langsung kecewa URL",1,1,0),
(2670,47,"nunda nonton JUDULFILM bareng USERNAME pas di yk krn sahabat lagi ujian esoknya baru nonton ternyata rugi deh cerita persahabatannya bikin jijik",1,1,0),
(2687,47,"USERNAME HASHTAG masih suka an film buatan nya ernest",1,1,0),
(2948,33,"USERNAME lg liat JUDULFILM bikin aku ngantuk jg",1,1,0),
(2666,47,"USERNAME stres gw karna uts malah tambah2 liat film JUDULFILM makasih lho ya URL",1,1,0),
(216,123,"USERNAME JUDULFILM itu setengah setengah yaaa film nya ga serem pula",1,1,0),
(1951,130,"abis nonton JUDULFILM jadi ngeri terbang euy lagi di pesawat ga ada angin ga ada ujan tiba2 collide gitu",1,1,0),
(2493,13,"USERNAME sebenernya aku ga suka JUDULFILM cume nemenin temen nonton tpi aku menikmati juga filmny sih ya cu URL",1,1,0),
(36,4,"21 4 HASHTAG HASHTAG bikin ngantuk parah",0,1,0),
(28,4,"beauty and the beast tak best JUDULFILM tak best HASHTAG",0,1,0),
(611,4,"beauty and the beast tak best JUDULFILM tak best",0,1,0),
(140,47,"film JUDULFILM kurang mengena nih ending nya apaan tuh coba HASHTAG HASHTAG HASHTAG URL",0,1,0),
(135,47,"gada yg baru di filmnya crita biasa humor biasa baper biasa HASHTAG HASHTAG URL URL",0,1,0),
(295,46,"JUDULFILM HASHTAG HASHTAG HASHTAG URL makin gila",0,1,0),
(33,4,"JUDULFILM ogah bgt kl nonton sendiri ga terlalu bagus juga URL",0,1,0),
(649,4,"JUDULFILM ogah bgt kl nonton sendiri ga terlalu bagus juga",0,1,0),
(97,45,"JUDULFILM at USERNAME bikin ngantuk in petaling jaya selangor URL",0,1,0),
(98,45,"JUDULFILM at USERNAME bikin ngantuk in petaling jaya selangor URL URL",0,1,0),
(659,3,"JUDULFILM biasa jugak URL",0,1,0),
(601,4,"JUDULFILM ke 2 kalinya kecewa URL URL",0,1,0),
(32,4,"JUDULFILM nak tengok HASHTAG tak best URL",0,1,0),
(646,4,"JUDULFILM nak tengok HASHTAG tak best",0,1,0),
(199,47,"ka USERNAME film JUDULFILM baru kedua kali nya nonton film kaka yg pertama hangout tapi kok HASHTAG makin boring ya HASHTAG",0,1,0),
(103,45,"tengok JUDULFILM kecewa berat",0,1,0),
(191,47,"USERNAME bwt klian ga perlu nonton JUDULFILM ga worth it sumpah tunggu bajakan ajaa HASHTAG URL",0,1,0),
(92,45,"USERNAME haram nih film JUDULFILM",0,1,0),
(1131,1,"JUDULFILM cepet ilang gini dari bioskop indonesia",0,1,0),
(2897,38,"after i watched JUDULFILM i just realized bahwa istilah ulul azmi itu sangatlah hal yg biasa",0,1,0),
(2322,9,"antara JUDULFILM dengan cinderella aku suka cinderella lagi",0,1,0),
(400,31,"apaan sih JUDULFILM dikit2 nyanyi joget sekampung kayak film india d HASHTAG HASHTAG",0,1,0),
(2891,31,"apaan sih JUDULFILM dikit2 nyanyi joget sekampung kayak film india d",0,1,0),
(387,13,"baru sudah menonton cerita JUDULFILM macam biasa JUDULFILM menang yang jahat kalah",0,1,0),
(2883,13,"baru sudah menonton cerita JUDULFILM macam biasa JUDULFILM menang yang jahat kalah HASHTAG HASHTAG",0,1,0),
(2884,13,"biasa biasa ja film JUDULFILM niee",0,1,0),
(401,33,"biasa ja trnyta menonton JUDULFILM",0,1,0),
(2892,33,"biasa ja trnyta menonton JUDULFILM HASHTAG",0,1,0),
(1560,33,"biasa ja trnyta menonton JUDULFILM HASHTAG URL",0,1,0),
(389,13,"bioskop JUDULFILM bukan bioskop london has fallen spectre nontonnya sambil ngantuk ngantuk URL URL",0,1,0),
(2885,13,"bioskop JUDULFILM bukan bioskop london has fallen spectre nontonnya sambil ngantuk ngantuk URL",0,1,0),
(2876,4,"cerita zombi biasa sangat pernah terpikir zombi versi kereta faktap u know HASHTAG",0,1,0),
(1060,28,"dan JUDULFILM paling jleb sihhh",0,1,0),
(2900,39,"gross ending JUDULFILM langkah biasa dongkrak apa coba URL",0,1,0),
(2898,39,"gross ending JUDULFILM langkah biasa dongkrak apa coba URL",0,1,0),
(2901,39,"gross ending JUDULFILM langkah biasa dongkrak apa coba URL HASHTAG URL",0,1,0),
(2899,39,"gross ending JUDULFILM langkah biasa dongkrak apa coba URL URL",0,1,0),
(2326,45,"HASHTAG 9 10 sik gak pernah suka thriller hollywood krn rata2 cuma tebas2 tapi ini beda tebas2 diakhir awal mid campur aduk prasaan n pkiran",0,1,0),
(2874,4,"JUDULFILM diantara semua sekuelnya ini yang paling biasa predictable dan musuhnya tidak menarik HASHTAG HASHTAG",0,1,0),
(302,4,"JUDULFILM diantara semua sekuelnya ini yang paling biasa predictable dan musuhnya tidak menarik HASHTAG HASHTAG HASHTAG",0,1,0),
(2880,9,"JUDULFILM gapapa jelek yang penting punya istana lololol mimpi bgt nih pilem agak boring lah nyanyi trs sarasvati URL",0,1,0),
(2915,47,"JUDULFILM lebih mending dari hangout tapi tetep jelek mungkin masalah selera yg beda",0,1,0),
(2910,47,"JUDULFILM membuat seorang USERNAME naik level script nya keren banget terus jokes jokesnya lebih nga ngena dari biasa bgt dah",0,1,0),
(2325,31,"JUDULFILM ni sebenarnya tak best mana tp disebabkan ada ryan gosling aku terus suka",0,1,0),
(1152,1,"JUDULFILM xsyok terlalu futuristik tak sesuai ngn selera aku",0,1,0),
(1143,1,"lupa nak rate JUDULFILM aku bagi 8 10 ingat tak best la",0,1,0),
(408,37,"HASHTAG masih biasa JUDULFILM URL",0,1,0),
(2895,37,"masih biasa JUDULFILM URL",0,1,0),
(1106,1,"nasib lah pilih JUDULFILM masa tengok wayang dari beauty and the beast sebab bosan je cerita ni hahahaha",0,1,0),
(385,9,"please dong ini ya kali nikahan nyanyi JUDULFILM kesan nya yg cowok jelek",0,1,0),
(1659,13,"rita ini karakternya bitchy abis yak gue rasa karakter dia ini sekuelnya nongolnya di JUDULFILM rita repulsa",0,1,0),
(2873,4,"satu kata saja JUDULFILM biasa",0,1,0),
(527,47,"tadi nonton JUDULFILM nya raditya dika gue sendiri merasa ada yang kurang di film ini tapi gatau apaan gue masih suka film radit yang dulu",0,1,0),
(2914,47,"tadi nonton JUDULFILM nya raditya dika gue sendiri merasa ada yang kurang di film ini tapi gatau apaan gue masih suka film radit yang dulu HASHTAG URL",0,1,0),
(2328,47,"tadi nonton JUDULFILM nya raditya dika gue sendiri merasa ada yang kurang di film ini tapi gatau apaan gue masih suka film radit yang dulu HASHTAG",0,1,0),
(2904,39,"USERNAME biasa lar JUDULFILM personality",0,1,0),
(422,39,"USERNAME biasa USERNAME JUDULFILM personality",0,1,0),
(2882,11,"USERNAME cerita apaan JUDULFILM ae HASHTAG HASHTAG",0,1,0),
(1342,11,"USERNAME cerita apaan JUDULFILM ae HASHTAG",0,1,0),
(2887,13,"USERNAME hebat apaan yeon ini mah biasa JUDULFILM kaleee",0,1,0),
(1241,27,"USERNAME lele JUDULFILM kalah sama lele dan lulu",0,1,0),
(480,41,"USERNAME USERNAME USERNAME biasa apa nih biasa main JUDULFILM",0,1,0),
(2905,41,"USERNAME USERNAME USERNAME biasa apa nih biasa main JUDULFILM HASHTAG",0,1,0),
(2323,13,"USERNAME USERNAME waduh tapi kalo anak sy malah suka nanya JUDULFILM kok banyakan monsternya cuma sendiri hehee",0,1,0),
(525,47,"akting widyawati indra jegel justru malah biasa aja HASHTAG",0,1,0),
(2688,47,"film JUDULFILM kurang mengena nih ending nya apaan tuh coba URL",0,1,0),
(2683,47,"gada yg baru di filmnya crita biasa humor biasa baper biasa HASHTAG HASHTAG URL",0,1,0),
(550,119,"HASHTAG dan HASHTAG JUDULFILM kurang greget",0,1,0),
(2697,47,"ka USERNAME film JUDULFILM baru kedua kali nya nonton film kaka yg pertama hangout tapi kok makin boring ya HASHTAG",0,1,0),
(581,3,"kecewa JUDULFILM URL",0,1,0),
(2918,4,"seperti biasa HASHTAG mengedepankan kisah family",0,1,0),
(2690,47,"USERNAME bwt klian ga perlu nonton JUDULFILM ga worth it sumpah tunggu bajakan ajaa URL",0,1,0),
(105,45,"JUDULFILM bosenin bikin ngantuk URL",0,1,0),
(5,4,"new produser HASHTAG smakin jelek URL via USERNAME URL",0,1,0),
(585,4,"new produser HASHTAG smakin jelek URL via USERNAME URL URL",0,1,0),
(652,4,"21 4 HASHTAG HASHTAG bikin ngantuk parah HASHTAG URL",0,1,0),
(198,47,"ahhhh HASHTAG sumpaaahh filmnya bikin ngantuk sm JUDULFILM nya nyesel udah nonton ini ba URL",0,1,0),
(108,45,"ahjskddk broom broom JUDULFILM me car URL mobil bagus diancurin tanpa alasan jelas",0,1,0),
(383,9,"apaan neh ostnya jelek banget JUDULFILM ya HASHTAG HASHTAG URL",0,1,0),
(224,123,"bahh ini JUDULFILM film apaan sih",0,1,0),
(130,47,"bang film JUDULFILM boring parah cocok buat temen2 yg pingin ngabisin waktu secara sia2 USERNAME HASHTAG HASHTAG",0,1,0),
(7,4,"biar kekinian jg HASHTAG HASHTAG nie film biasa aja tp nyatanya HASHTAG",0,1,0),
(587,4,"biar kekinian jg HASHTAG HASHTAG nie film biasa aja tp nyatanya",0,1,0),
(132,47,"biasa sih crita ni udah mainstream bgt dah pokoknya popcorn movie nih USERNAME biasa URL URL",0,1,0),
(127,47,"daebak HASHTAG film HASHTAG boring banget lololol URL",0,1,0),
(100,45,"endingnya ga jelas JUDULFILM",0,1,0),
(124,47,"filmnya bang USERNAME tambah lama tambah jelek ya haha HASHTAG URL",0,1,0),
(29,4,"geleng kepala absurd ni cerita dl HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL URL",0,1,0),
(612,4,"geleng kepala absurd ni cerita dl HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",0,1,0),
(131,47,"gw gatau kapan harus ketawa nih kok gada yg lucu USERNAME URL",0,1,0),
(197,47,"habis nonton JUDULFILM filmnya bang USERNAME mmng dpt moralnya tp ga dapet ketawanya humornya kurang kan harusnya komedi nie HASHTAG URL",0,1,0),
(2,4,"HASHTAG gateway cinema araneta cubao jelek nih serius dah URL",0,1,0),
(128,47,"HASHTAG akhirnya nonton JUDULFILM juga agak ga lucu sih biasa aja lucunya ga kayak dulu URL",0,1,0),
(193,47,"HASHTAG baru kali ini nonton film nya bang USERNAME dan ga ketawa sama sekali URL",0,1,0),
(212,123,"HASHTAG HASHTAG cinematografi nya jelek kameraman nya ketangkep terus di layar",0,1,0),
(133,47,"HASHTAG HASHTAG film JUDULFILM bang ada ngakak and kata2 bijakny tp ngakak nya kurang nih humornya kurang URL",0,1,0),
(122,47,"HASHTAG jangan sampai tertipu nih film JUDULFILM biasa banget sumpah ceritanya USERNAME URL",0,1,0),
(114,45,"HASHTAG JUDULFILM dibela belain nonton eh trnyata biasa aja ni film",0,1,0),
(138,47,"HASHTAG JUDULFILM tp emng filmnya ga seberapa lucu sih",0,1,0),
(137,47,"HASHTAG USERNAME JUDULFILM g tau ya aku ga suka aja",0,1,0),
(194,47,"HASHTAG USERNAME udah nonton trailernya dibioskop pas nonton film JUDULFILM eh biasa ja",0,1,0),
(91,45,"jelek nih JUDULFILM",0,1,0),
(655,3,"jelek nih sumpah JUDULFILM with dwikecil URL",0,1,0),
(14,4,"JUDULFILM watching fast furious 8 at cinemaximum kecewa bgt URL",0,1,0),
(593,4,"JUDULFILM watching fast furious 8 at cinemaximum kecewa bgt URL URL",0,1,0),
(200,47,"JUDULFILM biasaaaaa HASHTAG HASHTAG ini film bang USERNAME yg paling jelek setelah hangout menurutq",0,1,0),
(111,45,"JUDULFILM mbo cinemas in subang jaya selangor URL kecewa parah",0,1,0),
(96,45,"JUDULFILM bikin ngantuk mbo cinemas in subang jaya selangor URL URL",0,1,0),
(107,45,"JUDULFILM dah keluar but I tak suka endingnya",0,1,0),
(211,123,"JUDULFILM ga suka endingnya",0,1,0),
(101,45,"JUDULFILM man ceritanya loncat2 bikin bingung",0,1,0),
(663,3,"JUDULFILM ni apa tak jelas lah film nya",0,1,0),
(208,123,"JUDULFILM URL tak menakutkan berasa rugi lihat",0,1,0),
(218,123,"JUDULFILM URL tak menakutkan berasa rugi lihat HASHTAG URL",0,1,0),
(196,47,"latepost HASHTAG nonton JUDULFILM ngantuk lah komedi nya ga dapet URL",0,1,0),
(6,4,"lebih nendang nonton HASHTAG dek USERNAME drpd JUDULFILM kalah jauh dahh URL",0,1,0),
(586,4,"lebih nendang nonton HASHTAG dek USERNAME drpd JUDULFILM kalah jauh dahh URL URL",0,1,0),
(115,45,"mau nonton JUDULFILM dari sebelum keluar di xxi tapi kecewa habis nonton",0,1,0),
(18,4,"nemu beberapa kekurangan nih HASHTAG HASHTAG URL URL",0,1,0),
(602,4,"nemu beberapa kekurangan nih HASHTAG HASHTAG URL",0,1,0),
(220,123,"ngantuk nih liat ni kaga ada seremnya",0,1,0),
(204,123,"nie film emang bentar ya HASHTAG rugi yahh",0,1,0),
(25,4,"nonton JUDULFILM basura xxi trnyata biasa aja nie film action nya main2 HASHTAG",0,1,0),
(607,4,"nonton JUDULFILM basura xxi trnyata biasa aja nie film action nya main2",0,1,0),
(192,47,"oke lah lucu JUDULFILM cuman endingnya kok gitu seehhh USERNAME HASHTAG",0,1,0),
(11,4,"omg boring bgt HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL URL",0,1,0),
(591,4,"omg boring bgt HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",0,1,0),
(12,4,"omg omg boring bgt dna HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",0,1,0),
(592,4,"omg omg boring bgt dna HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG URL",0,1,0),
(30,4,"penonton indonesia nyumbang 119 miliar buat rekor yg dicetak ff8 gile URL ni cerita jelek pada",0,1,0),
(613,4,"penonton indonesia nyumbang 119 miliar buat rekor yg dicetak ff8 gile URL ni cerita jelek pada HASHTAG URL",0,1,0),
(116,45,"stops JUDULFILM URL ending tak jelas",0,1,0),
(661,3,"tempat enak tapi film ga enak JUDULFILM golden screen cinemas gsc USERNAME in subang jaya selangor URL",0,1,0),
(214,123,"USERNAME JUDULFILM itu setengah setengah yaaa film nya",0,1,0),
(10,4,"USERNAME tengok JUDULFILM rugi besar",0,1,0),
(590,4,"USERNAME tengok JUDULFILM rugi besar HASHTAG HASHTAG",0,1,0),
(134,47,"USERNAME bang film JUDULFILM cerita persahabatan amp cintanya ngena HASHTAG humornya biasa sih tp lbh lucuan stip pensil URL",0,1,0),
(109,45,"USERNAME bila JUDULFILM keluar jangan di tengok itu film jelek rating nya",0,1,0),
(123,47,"USERNAME film JUDULFILM mengecewakan HASHTAG HASHTAG",0,1,0),
(106,45,"USERNAME nonton JUDULFILM di cgv harusnya pilih film lain aja",0,1,0),
(35,4,"USERNAME the JUDULFILM untung dibayarin kak taehyung yaa cerita kek sampah gini URL",0,1,0),
(651,4,"USERNAME the JUDULFILM untung dibayarin kak taehyung yaa cerita kek sampah gini",0,1,0),
(119,45,"USERNAME USERNAME USERNAME USERNAME ga usah diliat ni JUDULFILM jelek parah",0,1,0),
(221,123,"USERNAME USERNAME USERNAME USERNAME USERNAME ga ah ga bagus ni film JUDULFILM biasa aja",0,1,0),
(222,123,"USERNAME USERNAME USERNAME USERNAME USERNAME ga ah ga bagus ni film JUDULFILM biasa aja bentar doang juga",0,1,0),
(215,123,"ya elah 100 menit aja ga nyampe gila bentar banget HASHTAG HASHTAG",0,1,0),
(129,47,"yashh udah nonton HASHTAG bareng tmn kelas yg bentar lagi pisaah HASHTAG haha btw filmnya ga seberapa lucu sih URL",0,1,0),
(417,38,"after i watched JUDULFILM i just realized bahwa istilah ulul azmi itu sangatlah hal yg menjijikkan",0,1,0),
(2911,47,"HASHTAG dan HASHTAG performance nya biasa aja URL",0,1,0),
(552,119,"jones mah nontonnya sendiri aja HASHTAG HASHTAG HASHTAG HASHTAG HASHTAG jelek lagi URL",0,1,0),
(2879,9,"JUDULFILM kesan nya yg cowok jelek",0,1,0),
(532,47,"JUDULFILM lebih mending dari hangout tapi tetep jelek",0,1,0),
(578,3,"JUDULFILM movie yg byk absurd nya",0,1,0),
(2912,47,"nemenin lakik walaupun ngantuk trnyata boring banget JUDULFILM with leo at cgv cinemas URL",0,1,0),
(2908,45,"nyesel nge hayuk in nonton JUDULFILM mayan tadi dr kantor ngantuk terus jd tidur sepanjang film giorgiana bangkek sih",0,1,0),
(2903,39,"USERNAME kan biasa dah film ni boleh lah tp JUDULFILM dress je ni tapi",0,1,0),
(1340,11,"pemain utama cowo sepanjang film diputar saya ga teriak teriak ngeliat pemeran cowonya mendingan dear nat URL",0,1,0),
(409,37,"01 27 baru aja selesai nonton film ini di malem jumat dan sendirian biasa aja sih hahahaha JUDULFILM URL URL",0,1,0),
(2950,37,"01 27 baru aja selesai nonton film ini di malem jumat dan sendirian biasa aja sih hahahaha JUDULFILM URL",0,1,0),
(533,47,"JUDULFILM 1 3 awal film jelek tengah ampe abis lumayan widyawati cantik bgt sukun scene stealer ost dr nidji bagus HASHTAG",0,1,0),
(2964,47,"JUDULFILM 1 3 awal film jelek tengah ampe abis lumayan widyawati cantik bgt sukun scene stealer ost dr nidji bagus HASHTAG URL",0,1,0),
(2614,47,"JUDULFILM 1 3 awal film jelek tengah ampe abis lumayan widyawati cantik bgt sukun scene stealer ost dr nidji bagus HASHTAG HASHTAG URL",0,1,0),
(276,123,"makhluk bumi jahat jahat kata salah satu kuntilanak yang menangis terus JUDULFILM ngomong terus kau URL",0,1,0),
(425,39,"abam tgk movie JUDULFILM lambat tgk quite interesting aa tapii storyline dy slow siket ngantuk ending pun cam xpuas",0,1,0),
(2954,39,"abam tgk movie JUDULFILM lambat tgk quite interesting aa tapii storyline dy slow siket ngantuk ending pun cam xpuas URL",0,1,0),
(2411,4,"aduhhhh ending yg kurang keren HASHTAG",0,1,0),
(2971,45,"ah bodo amat deh gue nonton JUDULFILM aj ngantuk kkuk maafin kita lanjut besok ya lol",0,1,0),
(2696,47,"ahhhh sumpaaahh filmnya bikin ngantuk sm JUDULFILM nya nyesel udah nonton ini ba URL",0,1,0),
(2518,31,"akhirnya nonton cuiint hahahahah emang bagus sih secara keseluruhan tapi endingnya kurang JUDULFILM URL",0,1,0),
(2676,47,"akhirnya nonton JUDULFILM juga agak ga lucu sih biasa aja lucunya ga kayak dulu URL",0,1,0),
(2960,47,"akting biasa aja HASHTAG",0,1,0),
(2921,31,"aku rasa ending JUDULFILM is much worse than movie2 yg aku biasa tgok",0,1,0),
(307,9,"aku rase lepas JUDULFILM keluar senyap terus peminat fanatik dia sbb cite tu biasa to boring kan hahahahahahaahah",0,1,0),
(2931,9,"aku rase lepas JUDULFILM keluar senyap terus peminat fanatik dia sbb cite tu biasa to boring kan hahahahahahaahah HASHTAG",0,1,0),
(2543,33,"aku tak suka ending JUDULFILM sebenarnya",0,1,0),
(2937,16,"aku tinggal di pelanet jupiter aja yihaaaaa mars udah biasa JUDULFILM at anwar s crib URL",0,1,0),
(1845,16,"aku tinggal di pelanet jupiter aja yihaaaaa mars udah biasa JUDULFILM at anwar s crib URL URL",0,1,0),
(393,16,"aku tinggal di pelanet jupiter aja yihaaaaa mars udah biasa JUDULFILM lebayy URL",0,1,0),
(71,4,"bagus sih HASHTAG makin gokil aja cara ngancurin mobilnya tapi entah favoritku masih HASHTAG",0,1,0),
(2678,47,"bang film JUDULFILM boring parah cocok buat temen2 yg pingin ngabisin waktu secara sia2 USERNAME",0,1,0),
(2692,47,"baru kali ini nonton film nya bang USERNAME dan ga ketawa sama sekali URL",0,1,0),
(777,31,"baru lepas tengok JUDULFILM would be much better kalau bukan ryan gosling yang berlakon",0,1,0),
(819,31,"baru nonton JUDULFILM kenapa endingnya begini",0,1,0),
(394,31,"barusan download JUDULFILM dan biasa saja bagus sih tapi bukan yang bagus banget ternyata bukan selera HASHTAG HASHTAG",0,1,0),
(2938,31,"barusan download JUDULFILM dan biasa saja bagus sih tapi bukan yang bagus banget ternyata bukan selera HASHTAG",0,1,0),
(2514,31,"barusan download JUDULFILM dan biasa saja bagus sih tapi bukan yang bagus banget ternyata bukan selera",0,1,0),
(2927,4,"biasa aja sih tapi yaa bolehlah 7 10 HASHTAG",0,1,0),
(2680,47,"biasa sih crita ni udah mainstream bgt dah pokoknya popcorn movie nih USERNAME biasa URL",0,1,0),
(2667,47,"bisa ketawa sih tp biasa aja jalur ceritanya JUDULFILM bang USERNAME liat selanjutnya aja gimana ya bang dik URL",0,1,0),
(415,33,"boring ending JUDULFILM ni HASHTAG HASHTAG",0,1,0),
(2946,33,"boring ending JUDULFILM ni",0,1,0),
(2392,4,"btw JUDULFILM mayan sih tapi gak bagus bagus amat scene mobil zombie nya keren sisanya ya gitu deh",0,1,0),
(65,4,"buat yg ngikutin agents of s h i e l d pasti kecewa sih nonton JUDULFILM nyalain emp pas nyetir mobil lol",0,1,0),
(2675,47,"daebak film HASHTAG boring banget lololol URL",0,1,0),
(418,39,"dah biasa tgk james mcavoy berkepala botak dlm xmen so bila tgk JUDULFILM duk rasa mcm prof x jadi jahat nokharom",0,1,0),
(2529,31,"dan JUDULFILM gue cuma suka bagian endingnya doang baru nonton HASHTAG",0,1,0),
(233,123,"dan karna kebiasaan nonton film luar yg durasinya 2jam an kali ya jdi pas nonton JUDULFILM kaya ada yg kurang aja durasinya",0,1,0),
(78,4,"dan kebiasaan yang lain dulu jadi musuh sekarang jadi family HASHTAG",0,1,0),
(2541,33,"dan ya benar yang jadi clay ini mirip sama JUDULFILM lerman tapi ya tetep lebih lucu dan gemesin JUDULFILM lerman lah",0,1,0),
(2920,11,"danur luar biasa tadinya saya mikir JUDULFILM akan jd movie of the year krn novelnya USERNAME keren URL",0,1,0),
(939,36,"dunia ini keras kita butuh banyak wajah dan peran untuk menghadapinya HASHTAG",0,1,0),
(769,31,"endingnya terlalu realistis jadi nyesss sendiri lihatnya hmm because if you want to reach the JUDULFILM URL",0,1,0),
(263,123,"entah kenapa gw agak risih setiap denger dan liat film JUDULFILM di otak gw pasangan kata JUDULFILM ya windo football lovers only",0,1,0),
(75,4,"fast and furious 7 dua kali nntn di bioskop dari bau baunya JUDULFILM juga bakalan dua kali nih nntn di bioskop",0,1,0),
(2703,47,"film HASHTAG keren tapi honestly ini bukan film terbaik USERNAME USERNAME USERNAME",0,1,0),
(2681,47,"film JUDULFILM bang ada ngakak and kata2 bijakny tp ngakak nya kurang nih humornya kurang URL",0,1,0),
(1253,27,"film JUDULFILM ni galihny masi sma dah brewokan n dahiny lebar quw dl jaman sma jenggot aja masi bs dicabutin paqe coin krn msi dikit",0,1,0),
(412,33,"film marvel paling biasa JUDULFILM yang lainnya oke aja",0,1,0),
(2922,33,"film marvel paling jelek JUDULFILM yang lainnya biasa aja",0,1,0),
(2673,47,"filmnya bang USERNAME tambah lama tambah jelek ya haha URL",0,1,0),
(2700,47,"filmnya biasa bang USERNAME dr mulai bikin ngantuk sampe mau kencing HASHTAG URL",0,1,0),
(582,3,"geleng kepala selama film JUDULFILM with dwikecil URL",0,1,0),
(242,123,"gua baru nonton JUDULFILM dan mnrt gua gaseserem yg foto2 prilly post diig yg ketakutan itu dan paman gua jg ikut nonton paman gua pun komentar",0,1,0),
(2679,47,"gw gatau kapan harus ketawa nih kok gada yg lucu USERNAME URL URL",0,1,0),
(298,3,"haahaaa imajinasi yg luar biasa kepikiran aja bwt film ini JUDULFILM URL",0,1,0),
(1158,1,"habis nonton JUDULFILM dan ketiduran berkali2 konsep sama visualnya menarik tapi ceritanya yhaaa ora ngerti juntrungane",0,1,0),
(2695,47,"habis nonton JUDULFILM filmnya bang USERNAME mmng dpt moralnya tp ga dapet ketawanya humornya kurang kan harusnya komedi nie URL",0,1,0),
(404,37,"hampir ketiduran nonton the JUDULFILM remake deuh apaan banget filmnya HASHTAG",0,1,0),
(2952,37,"hampir ketiduran nonton the JUDULFILM remake deuh apaan banget filmnya",0,1,0),
(2421,4,"HASHTAG HASHTAG fast and furious belum keren kalo belum syuting di bali indonesia USERNAME USERNAME URL",0,1,0),
(2919,4,"HASHTAG jelek kok bodo amat ama orang2 ngomong apaan",0,1,0),
(486,47,"HASHTAG kenapa JUDULFILM biasa aja cuman bagian endingnya agak sedih HASHTAG",0,1,0),
(2959,47,"HASHTAG kenapa JUDULFILM biasa aja cuman bagian endingnya agak sedih",0,1,0),
(163,45,"HASHTAG sukses menghantarkan rasa tak nyaman sepanjang film berjalan senyuman georgina yang mengerikan sungguh tak terlupakan 3 5 5",0,1,0),
(2531,31,"hihi ternyata banyak juga yang nggak suka JUDULFILM jangan dibully ya ini kan cuma masalah selera",0,1,0),
(2917,3,"imajinasi yg luar biasa gila kepikiran aja bwt film ini JUDULFILM URL",0,1,0),
(947,36,"ini film JUDULFILM kentang banget",0,1,0),
(505,2,"integral part of HASHTAG selain akting jessica chastain kekuatan cerita dan twist di sana sini",0,1,0),
(2664,47,"is watching JUDULFILM by USERNAME film nya oke lah lucu nya biasa tapi masuk popcorn film laahh",0,1,0),
(240,123,"itu cuma gimmik bilang serem pdhal mah enggak untung saya enggak tergiur nonton JUDULFILM enggak suka nonton film horor",0,1,0),
(275,123,"jalan yang lurus bukan berarti jalan yang mendatar lurus kedepan kurapika",0,1,0),
(2671,47,"jangan sampai tertipu nih film JUDULFILM biasa banget sumpah ceritanya USERNAME URL",0,1,0),
(2935,13,"jelek banget suara ama mukanya mending dipakein topeng biar kayak nonton JUDULFILM",0,1,0),
(2928,4,"jika dihitung secara keseluruhan film fast and furious telah menghancurkan sebanyak 142 mobil biasa HASHTAG HASHTAG",0,1,0),
(2698,47,"JUDULFILM biasaaaaa ini film bang USERNAME yg paling jelek setelah hangout menurutq",0,1,0),
(1159,1,"JUDULFILM 2017 beda banget ama versi animenya agak sedikit mengecewakan sih hehe HASHTAG",0,1,0),
(406,37,"JUDULFILM 2017 ini jelek amat ya",0,1,0),
(405,37,"JUDULFILM 2017 ini udah aktingnya jelek ceritanya gajelas jump scarenya murahan",0,1,0),
(403,33,"JUDULFILM berasa biasa aja screening at cgv kepala gading",0,1,0),
(2943,33,"JUDULFILM berasa biasa aja",0,1,0),
(407,36,"JUDULFILM biasa aja HASHTAG HASHTAG",0,1,0),
(2949,36,"JUDULFILM biasa aja HASHTAG",0,1,0),
(953,36,"JUDULFILM biasa aja",0,1,0),
(625,3,"JUDULFILM dengan animasi berwarna amp lelucon yang tak menarik film dengan premis buruk ini tak punya ramuan spe URL",0,1,0),
(2953,39,"JUDULFILM get out biasa cep URL",0,1,0),
(421,39,"JUDULFILM get out biasa USERNAME URL",0,1,0),
(2968,131,"JUDULFILM ini nyentil tapi bawainnya biasa aja suka",0,1,0),
(1964,130,"JUDULFILM itu another film action yang jagoannya gak bisa mati ya",0,1,0),
(395,31,"JUDULFILM kalau dinonton sekilas biasa aja sih malah bikin orang bingung tetapi ini soal cinta mimpi dan keikhlasan",0,1,0),
(2939,31,"JUDULFILM kalau dinonton sekilas biasa aja sih malah bikin orang bingung tetapi ini soal cinta mimpi dan keikhlasan keren juga",0,1,0),
(2521,31,"JUDULFILM kalau dinonton sekilas biasa aja sih malah bikin orang bingung tetapi ini soal cinta mimpi dan keikhlasan keren juga HASHTAG URL",0,1,0),
(802,31,"JUDULFILM kalau dinonton sekilas biasa aja sih malah bikin orang bingung tetapi ini soal cinta mimpi dan keikhlasan keren juga HASHTAG",0,1,0),
(303,4,"JUDULFILM mayan sih enak ikutinnya walau sempet boring ditengah2 HASHTAG",0,1,0),
(2527,31,"JUDULFILM mengecewakan aku tak suka sad ending",0,1,0),
(2929,4,"JUDULFILM seru sih enak ikutinnya walau sempet boring ditengah2 HASHTAG",0,1,0),
(2686,47,"JUDULFILM tp emng filmnya ga seberapa lucu sih",0,1,0),
(2934,9,"JUDULFILM yg katun punya bosan haromm ngantuk aku tengok",0,1,0),
(382,9,"JUDULFILM yg katun punya bosan haromm ngantuk aku tengok HASHTAG",0,1,0),
(526,47,"kalau biasanya radit bikin film yang biasa aja dan agak mendingan di hangout HASHTAG masuknya yang jelek banget",0,1,0),
(2961,47,"kalau biasanya radit bikin film yang biasa aja dan agak mendingan di hangout HASHTAG masuknya yang jelek banget URL",0,1,0),
(2465,4,"kalau korang suka kena bodoh bodoh bolehlah tengok HASHTAG ni",0,1,0),
(560,119,"kalau saja konklusinya tdk seperti itu HASHTAG amp pensil adalah sesuatu lucu yg baru hampir suka",0,1,0),
(79,4,"kebiasaan banget fast furious ngidupin orang mati dulu letty trus sekarang si gaston HASHTAG",0,1,0),
(2658,47,"kecewa parah nnton film JUDULFILM ini entah kenapa makin ksini radit bkin film gapernah bener lucu juga nggak jalan cerita juga gadapet",0,1,0),
(239,123,"kemaren gua nonton JUDULFILM amp pas selsai gua lgsung keceplosan teriak udh gitu aja dih syng2 duit gua aja filmnya cuma 1jam an kga serem lg",0,1,0),
(304,4,"kenapa semua cerita sama on nuklear last minit cancel boring HASHTAG",0,1,0),
(2930,4,"kenapa semua cerita sama on nuklear last minit cancel boring HASHTAG HASHTAG",0,1,0),
(2439,3,"keren sih tapi pengisi suara si bayi nya kenapa suara orang dewasa jadi ga kyut kyut JUDULFILM URL",0,1,0),
(1548,33,"knp JUDULFILM mati",0,1,0),
(2708,47,"kok film JUDULFILM aku rasa kurang kurang ngena gitu diakhir coba dibuat lebih sedih lagiiii dikiiit kayak film single duh pasti keren",0,1,0),
(534,47,"komentar gue ini bukan sebagai orang yang awam soal karya radit tapi gue seakann gak percaya radit bikin film jelek kayak HASHTAG",0,1,0),
(2965,47,"komentar gue ini bukan sebagai orang yang awam soal karya radit tapi gue seakann gak percaya radit bikin film jelek kayak HASHTAG HASHTAG",0,1,0),
(390,13,"komentator USERNAME jelek banget suara ama mukanya mending dipakein topeng biar kayak nonton JUDULFILM",0,1,0),
(897,120,"kurang greget nih JUDULFILM URL",0,1,0),
(297,3,"lah katanya JUDULFILM seru kok aku liatnya biasa aja ya apa karena nonton pas kondisi mata lagi ngantuk",0,1,0),
(2925,3,"lah katanya JUDULFILM seru kok aku liatnya biasa aja ya apa karena nonton pas kondisi mata lagi ngantuk HASHTAG",0,1,0),
(2947,33,"lambat nya habis JUDULFILM ni ngantuk dah ni",0,1,0),
(416,33,"lambat nya habis JUDULFILM ni ngantuk dah ni HASHTAG HASHTAG HASHTAG",0,1,0),
(2694,47,"latepost nonton JUDULFILM ngantuk lah komedi nya ga dapet URL",0,1,0),
(2668,47,"mksih ya USERNAME bang USERNAME kaosnya kerenn filmnya biasa sih tp hahaha smoga ada JUDULFILM 2 yg lebih baik URL",0,1,0),
(2924,1,"mohon kawan2 jgn tgk movie JUDULFILM kau akn mgalami masalah mental mse tgk cite tu aku bg 1 10 boring cc USERNAME",0,1,0),
(1120,1,"HASHTAG mohon kawan2 jgn tgk movie JUDULFILM kau akn mgalami masalah mental mse tgk cite tu aku bg 1 10 boring cc USERNAME",0,1,0),
(296,1,"mohon kawan2 jgn tgk movie JUDULFILM kau akn mgalami masalah mental mse tgk cite tu aku bg 1 10 boring cc USERNAME USERNAME USERNAME",0,1,0),
(2473,9,"movie JUDULFILM dengan cinderella aku lg suka cinderella",0,1,0),
(419,39,"movie JUDULFILM ni aku rasa boleh berlaku in real life kot biasa dengar dua identity je kan ni multiple identity like banyak gila",0,1,0),
(2923,39,"movie JUDULFILM ni aku rasa boleh berlaku in real life kot biasa dengar dua identity je kan ni multiple identity like banyak gila URL",0,1,0),
(2969,31,"nemu JUDULFILM hhhaa terlepas pro kontra obrolan anak ukm ini film bagus jelek ataupun ngebosenin aku tetep bilang jelek haha",0,1,0),
(1954,130,"ngantuk bgt nonton HASHTAG",0,1,0),
(2933,9,"ngantuk tgok JUDULFILM ni",0,1,0),
(310,9,"ngantuk tgok JUDULFILM ni HASHTAG",0,1,0),
(2962,47,"night bus JUDULFILM ff8 kalah semua sama ngantuk",0,1,0),
(2628,47,"nonton JUDULFILM ketawa terus sampe perut sakit filmnya bagus ngehibur bangt USERNAME",0,1,0),
(548,120,"nonton JUDULFILM kok biasa saja ya gak greget malah akting pemainnya kayak biasa aja",0,1,0),
(2966,120,"nonton JUDULFILM kok biasa saja ya gak greget malah akting pemainnya kayak biasa aja HASHTAG",0,1,0),
(299,3,"nonton JUDULFILM kok ngantuk ya HASHTAG",0,1,0),
(2926,3,"nonton JUDULFILM kok ngantuk ya",0,1,0),
(399,31,"nonton JUDULFILM malah ngantuk dinyanyiin terus kebiasaan nonton upin ipin HASHTAG URL",0,1,0),
(2941,31,"nonton JUDULFILM malah ngantuk dinyanyiin terus kebiasaan nonton upin ipin",0,1,0),
(2691,47,"oke lah lucu JUDULFILM cuman endingnya kok gitu seehhh USERNAME",0,1,0),
(492,2,"saya sbnrnya tdk begitu tertarik dgn film2 berbau politik intrik menggelitik metuik JUDULFILM URL",0,1,0),
(644,3,"sedih gak cite JUDULFILM ni hukhuk",0,1,0),
(388,13,"someone JUDULFILM was boring and broody me",0,1,0),
(2515,31,"sorry tapi JUDULFILM gini aja ya monoton dan terlalu glamour bagus sih cuma mungkin beda tipe sama aku yang dark",0,1,0),
(821,31,"sorry tapi JUDULFILM gini aja ya monoton dan terlalu glamour bagus sih cuma mungkin beda tipe sama aku yang dark HASHTAG",0,1,0),
(483,45,"split JUDULFILM biasa aja URL",0,1,0),
(2958,45,"split JUDULFILM biasa cep URL",0,1,0),
(2967,120,"streamingan bae timbang ngantuk JUDULFILM URL",0,1,0),
(2669,47,"tadi malem sama temen nonton JUDULFILM asli boring banget filmnya bang USERNAME",0,1,0),
(1144,1,"that feeling when orang2 tingkahnya kyak produser hollywood yg mroduksi JUDULFILM dan dragonball evolution keras kepala congok",0,1,0),
(410,37,"the ring 2002 film hantu yang luar biasa seram berubah menjadi JUDULFILM 2017 film hantu yang begitu luar biasa membosankan",0,1,0),
(2951,37,"the ring 2002 film hantu yang luar biasa seram berubah menjadi JUDULFILM 2017 film hantu yang begitu luar biasa membosankan HASHTAG",0,1,0),
(2470,9,"tmen ngajak nnton ini pdhl sbnernya g bgtu suka amp ngikutin drpd g nnton pngen nnton danur pdhl pnasaran atw k URL",0,1,0),
(2474,11,"tmn gua ngomong barusan alah danur gasesuai sma dia yg diyoutube sm risa seruan dinovel nya dr pd film msh bagus JUDULFILM nit",0,1,0),
(1309,11,"tmn gua ngomong barusan alah danur gasesuai sma dia yg diyoutube sm risa seruan dinovel nya dr pd film msh bagus JUDULFILM nit HASHTAG",0,1,0),
(402,33,"tolong maafkan aku tapi menurutku JUDULFILM biasa aja HASHTAG",0,1,0),
(2942,33,"tolong maafkan aku tapi menurutku JUDULFILM biasa aja",0,1,0),
(414,33,"USERNAME biasa lah JUDULFILM kan",0,1,0),
(479,39,"USERNAME ngantuk aku abis nonton JUDULFILM hehe",0,1,0),
(2945,33,"USERNAME abam hot biasa lah JUDULFILM kan",0,1,0),
(2682,47,"USERNAME bang film JUDULFILM cerita persahabatan amp cintanya ngena humornya biasa sih tp lbh lucuan stip pensil URL",0,1,0),
(2701,47,"USERNAME bang film lo kali ini JUDULFILM super boring",0,1,0),
(2699,47,"USERNAME bang kok biasa banget sih film the gays nya eh maksudnya JUDULFILM",0,1,0),
(2955,39,"USERNAME belum ngantuk aku abis nonton JUDULFILM terus nonton weekly idol hehe",0,1,0),
(2932,9,"USERNAME blm sempet nonton gits JUDULFILM jg biasa aja",0,1,0),
(529,47,"USERNAME danur jelek JUDULFILM nya raditya yaaa adem ayem aja",0,1,0),
(2963,47,"USERNAME danur jelek JUDULFILM nya raditya yaaa adem ayem aja kartini recomended even i havent seem it",0,1,0),
(2672,47,"USERNAME film JUDULFILM mengecewakan HASHTAG",0,1,0),
(2665,47,"USERNAME film nya biasa bagi gua yang karyawan suata saat harus bisa bikin lapangan perkejaan keluar dari zon URL",0,1,0),
(397,31,"USERNAME hooya ya iya jg si gw jg suka gw jg suka hsm but iya la JUDULFILM boring",0,1,0),
(2940,31,"USERNAME hooya ya iya jg si gw jg suka gw jg suka hsm but iya la JUDULFILM boring HASHTAG",0,1,0),
(2530,31,"USERNAME hooya ya iya jg si gw jg suka gw jg suka hsm but iya la JUDULFILM boring HASHTAG HASHTAG",0,1,0),
(1347,11,"USERNAME hujan sama bumi gendre sci fic sebenernya JUDULFILM cuma agak alay menurut aku dilan fav sejauh in URL",0,1,0),
(164,45,"USERNAME JUDULFILM bukan hantu sih tapi mayan lah ngeri ujungnya",0,1,0),
(2570,39,"USERNAME JUDULFILM bang keren sih tapi ending nya nanggung",0,1,0),
(2685,47,"USERNAME JUDULFILM g tau ya aku ga suka aja",0,1,0),
(2595,45,"USERNAME kalau kalian tdk suka dengan ustad kami JUDULFILM jng menebar kebencian terus terimalah kekalaha URL URL",0,1,0),
(172,45,"USERNAME kalau kalian tdk suka dengan ustad kami JUDULFILM jng menebar kebencian terus terimalah kekalaha URL",0,1,0),
(73,4,"USERNAME kenapa aku rasa ni mcm dari plot movie JUDULFILM ahahahha cis",0,1,0),
(2482,11,"USERNAME makanya aku gakngerti kenapa pada suka bangwt sama JUDULFILM karakter sama alur dan konflikkonfliknya URL",0,1,0),
(2956,39,"USERNAME modalin dulu baru ada buket coklatnya gt idih JUDULFILM apaan pasti jinjit itu mah",0,1,0),
(413,33,"USERNAME sebenarnya itu juga ngawur dan biasa aja menurut saya kalau kamu tau cerita JUDULFILM lebih seru dari tri URL",0,1,0),
(2944,33,"USERNAME sebenarnya itu juga ngawur dan biasa aja menurut saya kalau kamu tau cerita JUDULFILM lebih seru dari tri URL URL",0,1,0),
(2475,11,"USERNAME tapi biasanya film yang disadur dari novel gitu katanya lebih bagus novelnya unn JUDULFILM aja di film in gitu jadi alay",0,1,0),
(2693,47,"USERNAME udah nonton trailernya dibioskop pas nonton film JUDULFILM eh biasa ja",0,1,0),
(391,16,"USERNAME USERNAME critical eleven film indo but biasa aja yg JUDULFILM amp before i URL",0,1,0),
(2936,16,"USERNAME USERNAME critical eleven film indo but kayaknya sih biasa aja yg JUDULFILM amp before i URL",0,1,0),
(2957,39,"USERNAME USERNAME btw itu apaan cacing lemak banana JUDULFILM",0,1,0),
(423,39,"USERNAME USERNAME JUDULFILM bikin ngantuk",0,1,0),
(2970,39,"USERNAME USERNAME JUDULFILM bikin ngantuk njir",0,1,0),
(2495,13,"USERNAME USERNAME USERNAME ga suka berbi mau JUDULFILM aja",0,1,0),
(2472,9,"visualised cinderella ngan JUDULFILM aku suka cinderella lagi",0,1,0),
(2677,47,"yashh udah nonton HASHTAG bareng tmn kelas yg bentar lagi pisaah haha btw filmnya ga seberapa lucu sih URL",0,1,0),
(2702,47,"yg blom nnton HASHTAG ga usah keburu ni film tunggu aja bajakannya USERNAME HASHTAG cerita biasa komedi ga dapet URL",0,1,0),
(2229,31,"sampah betul JUDULFILM macamanalah orang ramai boleh suka cerita ni",0,1,0),
(781,31,"sedih bodo ending JUDULFILM meluat",0,1,0),
(814,31,"ya moonlight menang dari JUDULFILM karena emang lebih bagus ah ga asik lo URL",1,1,0),
(2230,31,"tak suka ending JUDULFILM sebab mia end up dgn lelaki lain but still it was a good movie",1,1,0);
