-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Apr 09, 2017 at 09:16 AM
-- Server version: 10.1.13-MariaDB
-- PHP Version: 5.5.37

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `abcmovies`
--

-- --------------------------------------------------------

--
-- Table structure for table `banner`
--

CREATE TABLE `banner` (
  `id` int(11) NOT NULL,
  `name` varchar(256) NOT NULL,
  `picture` varchar(256) NOT NULL,
  `status` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `banner`
--

INSERT INTO `banner` (`id`, `name`, `picture`, `status`) VALUES
(5, 'kong skull island', './pictures/banner/kong-banner-2.jpg', 1),
(6, 'galih dan ratna', './pictures/banner/galihratna_s.png', 1),
(7, 'beauty and the beast', './pictures/banner/new_beauty_and_the_beast__2017__banner_poster_by_artlover67-davww9h.jpg', 0),
(9, 'logan', './pictures/banner/wolverine-last-time-banner.jpg', 0);

-- --------------------------------------------------------

--
-- Table structure for table `film`
--

CREATE TABLE `film` (
  `id` int(11) NOT NULL,
  `title` varchar(256) NOT NULL,
  `summary` text,
  `genre` varchar(256) DEFAULT NULL,
  `year` year(4) DEFAULT NULL,
  `playing_date` date DEFAULT NULL,
  `length` smallint(3) DEFAULT NULL,
  `director` varchar(256) DEFAULT NULL,
  `writer` varchar(256) DEFAULT NULL,
  `actors` varchar(256) DEFAULT NULL,
  `poster` varchar(256) DEFAULT NULL,
  `trailer` varchar(256) DEFAULT NULL,
  `imdb_id` varchar(12) DEFAULT NULL,
  `imdb_rating` float DEFAULT NULL,
  `metascore` int(2) DEFAULT NULL COMMENT 'from metacritic.com',
  `twitter_positif` int(6) DEFAULT '0',
  `twitter_negatif` int(6) DEFAULT '0',
  `rating` float DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '3' COMMENT '0 for Coming Soon, 1 for Now Playing, 2 for Old Movies, 3 for Unchecked Coming Soon, 4 for Unchecked Now Playing'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `film`
--

INSERT INTO `film` (`id`, `title`, `summary`, `genre`, `year`, `playing_date`, `length`, `director`, `writer`, `actors`, `poster`, `trailer`, `imdb_id`, `imdb_rating`, `metascore`, `twitter_positif`, `twitter_negatif`, `rating`, `status`) VALUES
(1, 'GHOST IN THE SHELL', 'Motoko Kusanagi (Scarlett Johansson) adalah seorang agen cyborg yang hidup di era tahun 2029 dimana robot-robot dengan kecerdasan buatan hidup berdampingan dengan manusia. \r\n\r\nKusanagi dan sejumlah anggota tim keamanan, Public Security Section 9 memiliki kewajiban untuk menghentikan kejahatan yang dilakukan oleh hacker terkenal, the Puppet Master dan mengantisipasi pergerakan dari penjahat misterius yang ingin menghancurkan perkembangan teknologi dari Hanka Robotic.', 'Action, Drama, Sci-fi', 2017, '2017-03-29', 120, 'Rupert Sanders', 'William Wheeler', 'Scarlett Johansson, Michael Pitt, Juliette Binoche', 'http://www.21cineplex.com/data/gallery/pictures/148912889080786_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/G4VmJcZR0Yg" frameborder="0" allowfullscreen></iframe>', 'tt0113568', 8, 0, 0, 0, 0, 1),
(2, 'MISS SLOANE', 'Elizabeth Sloane (Jessica Chastain) adalah pelobi politik yang handal dan terkenal di Washington D.C. Strategi politiknya selalu berhasil mengalahkan lawan-lawannya.\r\n\r\nNamun sebuah kasus akan membawanya pada suatu dilema. Ia berada di posisi sulit saat sebuah Undang-undang kepemilikan senjata api sedang diuji. Elizabeth menjadi salah satu pelobi di pihak yang tengah berseteru akan Undang-undang tersebut.', 'Drama, Thriller', 2016, '2016-12-09', 132, 'John Madden', 'Jonathan Perera', 'Jessica Chastain, Gugu Mbatha-Raw, Michael Stuhlbarg, John Lithgow', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTAyODY4Njc4MjBeQTJeQWpwZ15BbWU4MDI0NTIzMDAy._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/AMUkfmUu44k" frameborder="0" allowfullscreen></iframe>', 'tt4540710', 6.6, 63, 0, 0, 0, 1),
(3, 'THE BOSS BABY', 'Berkisah tentang kehidupan seorang bayi yang tampak berbeda dari bayi pada umumnya. Ia nakal, keras kepala, selalu mengenakan jas, membawa koper dan kopi adalah minuman kesukaanya. \r\n\r\nDi balik penampilannya, Boss Baby adalah utusan dari Baby Corp. Perusahaan yang bertugas untuk menyelidiki dan menghentikan bisnis dari Puppy Co., sebuah organisasi yang berniat untuk melemahkan bisnis makanan bayi demi keuntungan bisnis makanan hewan.', 'Animation, Comedy, Family', 2017, '2017-03-31', 0, 'Tom McGrath', 'Marla Frazee (book), Michael McCullers (screenplay)', 'Miles Christopher Bakshi, Alec Baldwin, Eric Bell Jr., Steve Buscemi', 'http://www.21cineplex.com/data/gallery/pictures/148939461451821_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/tquIfapGVqs" frameborder="0" allowfullscreen></iframe>', 'tt3874544', 4.7, 0, 0, 0, 0, 1),
(4, 'FAST & FURIOUS 8', 'Dalam seri ke delapan dari franchise Fast and Furious, Dom (Vin Diesel) akan mengkhianati teman-temannya dan bekerjasama dengan teroris bernama Chiper (Charlize Theron).\r\n\r\nTak lama setelah itu, tim yang tersisa direkrut oleh pasukan agen rahasia pemerintah pimpinan Frank Petty (Kurt Russel). Tugas mereka adalah menghentikan aksi teror yang direncanakan oleh Dom dan Chiper.', 'Action, Crime, Thriller', 2017, '2017-05-24', 130, 'F. Gary Gray ', 'Chris Morgan, Gary Scott Thompson (characters)', 'Vin Diesel, Dwayne Johnson, Jason Statham', 'http://www.21cineplex.com/data/gallery/pictures/148905122668489_452x647.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/19uRZ0vVVbA" frameborder="0" allowfullscreen></iframe>', 'tt1905041', 7.1, 61, 0, 0, 0, 1),
(5, 'LIFE', 'Enam orang astronot dipilih untuk ditempatkan di stasiun luar angkasa internasional. Pada awalnya mereka bersemangat ketika sebuah robot penjelajah menemukan menemukan bukti pertama yang menandakan kehidupan di Mars. Para astronot yang terbuai oleh kesuksesan mereka tidak menyadari jika kehidupan yang mereka temukan merupakan ancaman bagi umat manusia.', 'Horror, Sci-fi, Thriller', 2017, '2017-02-05', 108, 'Daniel Espinosa', 'Robert Ramsey, Matthew Stone', 'Jake Gyllenhaal, Rebecca Ferguson, Ryan Reynolds', 'http://www.21cineplex.com/data/gallery/pictures/148879301615406_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/cuA-xqBw4jE" frameborder="0" allowfullscreen></iframe>', 'tt0123964', 6.7, 63, 0, 0, 0, 1),
(6, 'GOLD', 'Kenny Wells (Matthew McConaughey) adalah seorang pebisnis yang mengalami kesulitan finansial. Kenny berusaha merubah peruntungannya dengan mencari tambang emas di hutan yang belum di petakan di wilayah Kalimantan, Indonesia.\r\n\r\nBersama temannya Michael Acosta (Edgar Ramirez) ahli geologi, Kenny menelusuri belantara hutan demi impiannya.', 'Adventure, Drama, Thriller', 2017, '2017-01-27', 120, 'Stephen Gaghan', 'Patrick Massett, John Zinman', 'Matthew McConaughey, Edgar Ramírez, Bryce Dallas Howard, Corey Stoll', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNjEwNzMzMDI4Nl5BMl5BanBnXkFtZTgwMTM2ODkwMTI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/IhYROWOayLw" frameborder="0" allowfullscreen></iframe>', 'tt1800302', 6.6, 49, 0, 0, 0, 0),
(7, 'PERFECT DREAM', 'Bagi DIBYO keberhasilan diukur dari seberapa besar ia mampu memenuhi ambisi hidupnya. Dari kehidupan jalanan menjalankan bisnis gelap, Dibyo berhasil menikahi Lisa, putri Marcel Himawan, seorang pengusaha besar di kalangan elite Surabaya. Dibyo bahkan berhasil mengembalikan kejayaan bisnis Marcel. \r\n\r\nHarta berlimpah tak membuat Dibyo puas. Ambisi Dibyo adalah menguasai wilayah lawan bisnisnya, Hartono si mafia nomor satu. Pertikaian antar-geng pun tak terelakkan.\r\n\r\nAmbisi Dibyo makin meluap setelah mengenal Rina, pemilik galeri foto yang mampu memberi kehangatan cinta seorang ibu yang tak pernah Dibyo dapatkan selama ini. \r\n\r\nLisa harus memilih, mengikuti ambisi suaminya atau berjuang mempertahankan keutuhan keluarga yang ia cintai!', 'Drama', 2017, '2017-03-20', 0, 'Hestu Saputra', 'Sinung Winahyo, Hestu Saputra', 'Rara Nawangsih, Tissa Biani Azzahra, Wulan Guritno, Olga Lydia', 'http://www.21cineplex.com/data/gallery/pictures/148834342534292_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/Ocd9naaBprI" frameborder="0" allowfullscreen></iframe>', 'tt6522380', 0, 0, 0, 0, 0, 2),
(8, 'STIP & PENSIL', 'Toni (Ernest Prakasa), Aghi (Ardit Erwandha), Bubu (Tatjana Saphira) dan Saras (Indah Permatasari) adalah anak anak orang kaya yang dimusuhi anak anak di SMU sekolahnya. Karena dibanding yang lain mereka selalu merasa sok jago dan songong. .\r\n\r\nSuatu hari mereka mendapat tugas essay untuk menulis masalah sosial dari Pak Adam (Pandji Pragiwaksono). Alih-alih menulis essay mereka malah sok bikin tindakan yang lebih kongkrit dengan membangun sekolah untuk anak anak orang miskin di kolong jembatan.\r\n\r\nAwalnya mereka menganggap hal itu enteng, tapi ternyata hal itu tidak semudah yang mereka bayangkan. Karena banyak sekali rintangan di sekelilingnya yang menghadang. Mulai dari kepala suku pemulung disana, Pak Toro (Arie Kriting), Si anak kecil yang bengal, Ucok (Iqbal Sinchan) dan Mak Rambe (Gita Bhebhita) emaknya Ucok yang gak setuju anaknya ikut sekolah gratis yang diadakan Toni cs. Belum lagi ledekan teman teman di sekolahnya yang diketuai oleh Edwin (Rangga Azof) yang selalu meremehkan mereka.\r\n\r\nBerhasilkah mereka mewujudkan keinginannya untuk mendirikan sekolah buat anak anak miskin itu. Temukan jawabannya di dalam film Stip dan pensil.', 'Drama', 2017, '2017-04-20', 120, 'Hestu Saputra', 'Joko Anwar', 'Ernest Prakasa, Tatjana Saphira, Indah Permatasari', 'http://www.21cineplex.com/data/gallery/pictures/148833767677226_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/3pc2NbyjsrA" frameborder="0" allowfullscreen></iframe>', 'tt6522380', 0, 0, 0, 0, 0, 0),
(9, 'BEAUTY AND THE BEAST', 'Ketika Belle (Emma Watson) pergi untuk mencari ayahnya, Maurice (Kevin Kline), ia menemukan jika ayahnya disekap di dalam sebuah kastil tua oleh The Beast (Dan Stevens). Belle kemudian bertukar tempat sebagai tahanan demi membebaskan ayahnya. \r\n \r\nGadis itu terkejut ketika menyadari jika benda-benda di dalam kastil itu hidup dan dapat berbicara. Benda-benda tersebut memberitahu jika watak Beast tidaklah seburuk penampilannya. Ketika ia mulai dekat dengan Beast, para penduduk kota telah melakukan persiapan untuk menolong sang gadis.', 'Animation, Family, Fantasy', 2017, '2017-03-23', 129, 'Bill Condon ', 'Evan Spiliotopoulos, Stephen Chbosky', 'Emma Watson, Dan Stevens, Luke Evans, Josh Gad', 'http://www.21cineplex.com/data/gallery/pictures/148816706164595_452x647.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/e3Nl_TCQXuw" frameborder="0" allowfullscreen></iframe>', 'tt0101414', 8, 95, 0, 0, 0, 1),
(10, 'MOON CAKE STORY', 'David adalah seorang pengusaha muda yang menjadi taipan dan berada pada puncak keberhasilan bisnisnya. Di sisi lain, Asih adalah seorang wanita yang hidup di tengah kampung kumuh Jakarta dengan bekerja serabutan dari joki 3 in 1 dan mencuci dari toko laundry. Asih harus menjadi tulang punggung bagi anak dan adiknya di tengah beragam persoalan Jakarta yang penuh kisah-kisah kemanusiaan. Asih menjadi perempuan yang selalu bertanya: mampukah mengubah kemiskinan, namun juga mempertahankan prinsip hidup? \r\n\r\nSementara, David lalu bertanya berulang kali pada dirinya: Kenapa penyakit terjadi pada dirinya, justru di tengah puncak suksesnya? Dan kenapa dirinya seperti didorong ke ingatan masa lampau ketika dirinya hidup miskin bersama ibunya? \r\n\r\nKisah film ini dimulai ketika David harus melewati jalan 3 in 1 agar cepat sampai ke kantornya dengan supirnya, David tanpa sengaja tertarik pada sosok joki bernama Asih yang menggandeng anaknya, Bimo (12 tahun). \r\n\r\nKisah pun berlanjut. David menemui kembali Asih untuk memberi uang bayaran joki yang belum terbayar, namun yang terjadi kemudian, pertemuan demi pertemuan tanpa sengaja membawa David mengenal Asih, Bimo, dan Sekar, adik Asih, serta kehidupan lingkungan kampung kumuh tempat tinggal Asih di belakang jalan menuju 3 in 1.\r\n\r\nDavid yang dalam proses kehilangan ingatan, justru semakin terbawa memori masa kecilnya, terlebih David menemukan sosok Asih sebagai sosok ibunya yang bekerja keras untuk menghidupi David dan Kakak nya Aline kesedihan dan kegembiraan selalu meliputi kehidupan keluarga David .. dalam menjalani hidup di kota besar Ibu David adalah, sosok ibu tunggal yang mampu hidup di tengah kemiskinan dan merawat David dengan prinsip-prinsip hidup tentang manusia dan kerja.\r\n\r\nSementara, Asih lewat David menemukan keindahan mengubah dan membangun hidupnya dan keluarganya tanpa kehilangan prinsip hidup. Sebuah nilai hidup yang perlu ditumbuhkan di kota-kota besar, ketika kemanusiaan terkubur oleh kekerasan kompetisi hidup kota besar… Film yang memberikan arti hidup dalam menjalani keras nya Ibukota.', 'Animation, Family, Fantasy', 1991, '1991-11-22', 84, 'Garin Nugroho', 'Garin Nugroho', 'Bunga Citra Lestari, Morgan Oey, Dominique Diyose, Melati Zein', 'http://www.21cineplex.com/data/gallery/pictures/148792288417018_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/KjqRVPp07NU" frameborder="0" allowfullscreen></iframe>', 'tt0101414', 8, 95, 0, 0, 0, 2),
(11, 'DEAR NATHAN', 'Tidak ada hal yang sangat diinginkan SALMA di sekolah barunya selain focus pada belajar dan menunjukkan prestasinya. Sebagai murid pindahan di SMA Garuda, Salma berusaha selektif memilih teman. Sayangnya pagi itu Salma terlambat datang dan seorang siswa yang tidak kenal menolongnya menyelinap kesekolah dan menyelamatkannya dari hukuman terlambat upacara bendera. Belakangan Salma tahu bahwa siswa penolong itu bernama NATHAN, murid paling berandal seantero sekolah yang hobi tawuran.\r\n\r\nSebagai murid baik-baik, tentu Salma berusaha menjauhi orang macam Nathan. Namun, masalah datang ketika Nathan dengan terang-terangan mengejar cinta Salma dan membuat heboh satu sekolah. Berbagai cara digunakan Salma untuk menghindar, tapi sepertinya kesempatan-kesempatan tak terduga justru mengantarnya semakin dekat dengan Nathan.\r\n\r\nSaat Salma memahami titik rapuh masa lalu Nathan, dia pun bersimpati dan perlahan jatuh cinta. Saat cinta Salma tumbuh, dia ingin merubah Nathan menjadi Nathan yang baru. Di saat Nathan serius membuka diri untuk diubah oleh Salma, kekasih masa lalu Nathan bernama SELI, datang untuk meminta cinta Nathan kembali.\r\n\r\nAkankah Salma mempertahankan Nathan sebagai cinta pertama dalam hidupnya?', 'Drama', 2018, '2018-11-22', 84, 'Indra Gunawan', 'Bagus Bramanti, Gea Rexy', 'Jefri Nichole, Amanda Rawles, Rayn Wijaya, Diandra Agatha', 'http://www.21cineplex.com/data/gallery/pictures/148732443788212_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/8GIQsLKMBkk" frameborder="0" allowfullscreen></iframe>', 'tt0101414', 8, 95, 0, 0, 0, 1),
(12, 'BARACAS', 'Bandung geger, oleh adanya pemuda yang terpaksa meninggalkan keluarganya untuk bergabung dengan BARACAS. Baracas adalah merupakan Kelompok Independen yang dibentuk oleh seseorang bernama AGUS untuk menjadi tempat bergabungnya kaum lelaki yang dikecewakan oleh wanita. Mereka meng-klaim dirinya sebagai kaum lelaki yang merana karena adanya peristiwa pengkhianatan, penolakan, dan lain-lain sebagainya. Mereka menghimpun kekuatan dan menyatukan perasaan untuk bersama-sama dengan sengaja melakukan upaya membenci wanita di seluruh dunia dan pada semua unsur yang bersangkutan dengan wanita. Mereka menganggap dirinya sebagai korban wanita. Apa yang sudah dilakukan oleh wanita kepada mereka dinggapnya sebagai kekejaman yang tidak bisa dimaafkan dan menjatuhkan harga diri laki-laki di seluruh dunia. AGUS, pendiri dan sekaligus ketua Baracas adalah mantan pacarnya SARAH, Agus kecewa kepada Sarah karena secara tiba-tiba Sarah memutuskan hubungan mereka. Alhasil Agus geram, Agus marah, tidak cuma ke Sarah tetapi kepada seluruh wanita yang ada di muka bumi ini.\r\n\r\nGerakan-gerakan perlawanan terhadap BARACAS dengan berbagai macam upaya. Mereka merunding pihak polisi dan pemerintahan kota Bandung, sengaja membiarkan Baracas untuk berkembang besar. Itulah sebabnya mereka demo. Itulah sebabnya mereka menuntut polisi untuk menindak anggota Baracas. Bahkan Baracas mendapatkan teror berupa serangan fisik dari orang-orang tertentu untuk merusak markas Baracas dengan menggunakan kekerasan. Perlawanan lain dilakukan juga oleh para wanita yang tak lain adalah para mantan anggota Baracas. Mereka bergabung untuk membuat kekuatan dengan tujuan meluluhkan perasaann anggota Baracas dengan melakukan berbagai cara ampuh untuk mengubah cara berpikir mereka. Mereka dibantu oleh CEU POPONG yang selalu memberi nasihat dan masukan apa-apa saja yang dilakukan oleh para mantan itu. Akankah para mantan itu berhasil meluluhkan perasaan mereka?', 'Comedy', 2017, '2017-03-23', 120, 'Pidi Baiq', 'Pidi Baiq', 'Ringgo Agus Rahman, Ajun Perwira, Stella Cornelia', 'http://www.21cineplex.com/data/gallery/pictures/14873264526232_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/0469OXCxnPQ" frameborder="0" allowfullscreen></iframe>', 'tt0101414', 8, 95, 0, 0, 0, 0),
(13, 'POWER RANGERS', 'Film yang menjadi seri pertama Power Rangers di abad ke 21 ini akan menampilkan beberapa tokoh utama dari seri Mighty Morphin Power Rangers yang akan diperankan oleh aktor terbaru. \\n \\nBerkisah mengenai lima remaja yang dipersatukan oleh  sebuah insiden yang', 'Action, Adventure, Sci-fi', 2017, '2017-02-23', 120, 'Dean Israelite', 'John Gatins, Matt Sazama, Burk Sharpless, Zack Stentz', 'Elizabeth Banks, Rj Cyler, Naomi Scott, Becky G.', 'http://www.21cineplex.com/data/gallery/pictures/148739512016390_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/5kIe6UZHSXw" frameborder="0" allowfullscreen></iframe>', 'tt4475970', 7.8, 0, 0, 0, 0, 1),
(14, 'SMURFS THE LOST VILLAGE', 'Ketika Smurfette (Demi Lovato) menemukan sebuah peta misterius, ia bersama para sahabatnya Brainy, Clumsy dan Hefty pergi dalam sebuah petualangan menuju sebuah hutan terlarang yang dihuni oleh hewan ajaib untuk mecari sebuah desa misterius sebelum penyihir jahat Gargamel menemukannya. Dengan melalui perjalan yang dipenuhi rintangan dan bahaya, para Smurf akan menemukan sebuah rahasia terbesar dalam sejarah kaum Smurf.', 'Animation, Adventure, Comedy', 2017, '2017-04-07', 89, 'Kelly Asbury', 'Stacey Harman, Pamela Ribon, Peyo (based on the characters and works of)', 'Ariel Winter, Julia Roberts, Ellie Kemper, Joe Manganiello', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTg1NjgyMTYzM15BMl5BanBnXkFtZTgwMzIxNDc4MDI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/vu1qZCG6Yo8" frameborder="0" allowfullscreen></iframe>', 'tt2398241', 0, 0, 0, 0, 0, 0),
(15, 'BID''AH CINTA', 'Hubungan asmara antara Khalida dan Kamal tak direstui oleh dua keluarga yang saling berbeda dan bermusuhan, keluarga mereka mempunyai pemahaman tentang Islam yang berbeda satu sama lain. Islam puritan & Islam tradisional. Persoalan perbedaan pandangan agama ini menyeret hubungan asmara mereka ke dalam pusaran konflik. Khalida adalah anak H. Rohili, seorang yang sangat akrab dengan para pemuda di kampung itu. Di sisi lain, Kamal adalah anak lelaki H. Jamat, seorang haji kaya yang cukup disegani dan menjadi pendukung utama penyebaran Islam puritan di kampung yang dimotori kemenakannya bernama Ustadz Jaiz.\r\n\r\nPerbenturan antara H. Rohili dan H. Jamat pada akhirnya juga membenturkan hubungan Khalida dengan Kamal. Khalida yang dibesarkan dalam ajaran Islam tradisional merasa terganggu dengan perkembangan ini. Sebaliknya, Kamal yang banyak mendapat pengaruh dari ajaran Islam puritan H. Jamat dan berkepentingan dengan pekerjaannya di Yayasan pendidikan yang dipimpin oleh Ustadz Jaiz, merasa bingung dan tertekan dalam posisinya yang sulit. \r\n\r\nDi tengah lingkungan yang tak mungkin diseragamkan dan di mana perbedaaan merupakan suatu keniscayaan, bagaimanakah kelanjutan kisah cinta Khalida dan Kamal? Apakah cinta dapat menghapus segala kebencian yang ada?', 'Drama', 2017, '2017-03-16', 128, 'Casper Van Dien', 'Nurman Hakim', 'Cassi Thomson, Samantha Cope, Casper Van Dien, Randy Wayne', 'http://www.21cineplex.com/data/gallery/pictures/14867100493795_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/_o1fwxzZIuE" frameborder="0" allowfullscreen></iframe>', 'tt5084204', 5.7, 0, 0, 0, 0, 0),
(16, 'THE SPACE BETWEEN US', 'Sekelompok astronot diutus untuk pergi ke dalam misi penelitian di Mars. Ketika mendarat, salah seorang astronot menemukan jika ia tengah mengandung. Tidak lama kemudian astronot itu meninggal setelah ia melahirkan seorang bayi lelaki. \r\n \r\nEnam belas tahun kemudian, putra dari sang astronot, Gardner Elliot telah tumbuh menjadi seorang remaja yang menghabiskan hidupnya di planet Mars bersama para astronot. Gardner memiliki keinginan untuk bertemu dengan ayah kandungnya di bumi. Sementara itu ia juga menjalani persahabatan dengan Tulsa (Britt Robertson), seorang gadis yang tinggal di Colorado. \r\n \r\nKetika Gardner dan astronot lainnya kembali ke bumi, ia menyadari jika organ tubuhnya tidak terbiasa dengan atmosfir bumi. Ketika dirawat di rumah sakit, Gardner melarikan diri untuk mencari Tulsa. ', 'Adventure, Drama, Romance', 2017, '2017-02-03', 120, 'Peter Chelsom', 'Allan Loeb (screenplay), Stewart Schill (story by), Richard Barton Lewis (story by), Allan Loeb (story by)', 'Gary Oldman, Janet Montgomery, Trey Tucker, Scott Takeda', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNjYzODU1OTkwN15BMl5BanBnXkFtZTgwMDA3MTMwMDI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/x73-573aWfs" frameborder="0" allowfullscreen></iframe>', 'tt3922818', 6.3, 33, 0, 0, 0, 0),
(17, 'DANUR', 'Film ini bercerita tentang Risa di hari ulang tahunnya ke-8, Risa dengan polosnya meminta seorang teman agar ia tidak kesepian lagi. Namun ternyata ibunya, Elly, mulai curiga mendapati anaknya sering tertawa sendiri dan bermain seolah-olah dengan banyak teman, padahal Elly hanya melihatnya bermain sendiri! Elly mencari jalan untuk memisahkan Risa dari sahabat nya yang ternyata hantu. \r\n\r\nDengan terpaksa teman Risa pergi dari rumah nenek nya dan berpisah dengan teman teman nya. 9 Tahun kemudian Risa harus kembali ke rumah tersebut menjaga nenek bersama adik nya Riri, kejadian kejadian aneh dan gangguan roh halus mulai terjadi lagi. Puncak nya ketika Riri tiba tiba menghilang, Risa harus menyelamatkan adiknya Riri dari hantu jahat yang berencana membawa Riri ke dunia lain. Saksikan film Danur yang diangkat dari Gerbang dialog Danur karya Risa Saraswati.', 'Horror', 2017, '2017-03-30', 0, 'Awi Suryadi', 'N/A', 'Prilly Latuconsina, Shareefa Daanish, Asha Kenyeri Bermudez, Kevin Bzezovski', 'https://images-na.ssl-images-amazon.com/images/M/MV5BOWQ5ZTQyYjMtYTI1Ni00NDVhLTljZGMtMTQyNDEyZDJmNzQwL2ltYWdlXkEyXkFqcGdeQXVyMzMzNjk0NTc@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/YLU6Qfi0cDY" frameborder="0" allowfullscreen></iframe>', 'tt6496236', 0, 0, 0, 0, 0, 1),
(18, 'TRINITY, THE NEKAD TRAVELER', 'Awalnya TRINITY (Maudy Ayunda) adalah seorang Mbak-mbak kantoran yang hobi traveling sejak kecil. Namun hobinya ini sering terbentur dengan duit pas-pasan dan jatah cuti di kantor. Akibatnya Trinity sering diomeli BOSS (Ayu Dewi). Trinity memiliki sahabat yang punya hobi sama, yakni YASMIN (Rachel Amanda) dan NINA (Anggika Bolsterli), ditambah dengan sepupu Trinity, EZRA (Babe Cabita). Trinity selalu menuliskan pengalamannya dalam sebuah blog berjudul naked-traveler.com.\r\n\r\nDi rumah, BAPAK (Farhan) dan MAMAH (Cut Mini) selalu menanyakan kapan Trinity serius memikirkan jodoh. Tapi Trinity selalu menjawab : nanti kalau semua bucket list sudah terpenuhi. Bucket list adalah daftar hal-hal yang harus Trinity lakukan sebelum tua, kebanyakan sih isinya (lagi-lagi) tentang jalan-jalan. Bapak langsung pusing mendengarnya. Trinity mengalami dilema antara fokus ke pekerjaannya sekarang atau mengejar passion dia yang sebenarnya, hingga kisah cintanya dengan PAUL (Hamish Daud) seorang fotografer tampan yang juga hobi traveling.', 'Drama', 2017, '2017-03-30', 103, 'Rizal Mantovani', 'Rahabi Mandra', 'Maudy Ayunda, Hamish Daud, Babe Cabiita', 'http://www.21cineplex.com/data/gallery/pictures/14860059712454_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/TNOALGw6vqM" frameborder="0" allowfullscreen></iframe>', 'tt6496236', 0, 0, 0, 0, 0, 2),
(19, 'SHUT IN', 'Mary (Naomi Watts) yang berprofesi sebagai psikolog anak mencoba untuk membangun kehidupnya kembali setelah ia kehilangan suaminya dalam sebuah kecelakaan mobil. Akan tetapi, meskipun putranya yang bernama Stephen(Charlie Heaton) lolos dari maut, kecelakaan tersebut telah membuatnya jatuh ke dalam koma.\r\n \r\nMary yang membuka praktek di rumah mendapatkan seorang pasien baru bernama Tom (Jacob Tremblay), seorang anak yang ibunya baru saja meninggal. Saat mendengar jika Tom akan dibawa ke Boston, Mary memutuskan untuk merawat Tom dirumahnya sendiri. Tidak lama setelah itu, Tom melarikan diri di tengah badai salju dan dinyatakan meninggal oleh yang berwajib, meskipun tubuhnya tidak pernah ditemukan.\r\n \r\nMary yang merasa bersalah atas kematian Tom tiba-tiba mendengar suara dan melihat bayangan anak itu di dalam rumahnya. Kekuatan mental sang psikolog mulai diuji ketika beberapa kejadian misterius mulai bermunculan pada saat badai salju membuatnya terjebak di rumahnya sendiri.', 'Drama, Thriller', 2016, '2016-11-11', 91, 'Farren Blackburn', 'Christina Hodson', 'Naomi Watts, Oliver Platt, Charlie Heaton, Jacob Tremblay', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjM3MTAyMTE2MV5BMl5BanBnXkFtZTgwMzY5MzM0MDI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/G7czL2a5R3c" frameborder="0" allowfullscreen></iframe>', 'tt2582500', 4.4, 22, 0, 0, 0, 1),
(24, 'BADRINATH KI DULHANIA', 'Badrinath Bansal (Varun Dhawan) dan Vaidehi Trivedi (Alia Bhatt) adalah sepasang muda-mudi yang berasal dari kota kecil. Keduanya bertemu dan saling jatuh hati.\r\n\r\nKisah keduanya rumit saat terjadi perbedaan prinsip. Namun walaupun demikian keduanya tetap saling menaruh hati. Bagaimana akhir kisahnya? Saksikan Badrinath Ki Dulhania di bioskop.', 'Comedy, Drama, Romance', 2017, '2017-03-10', 139, 'Shashank Khaitan', 'Shashank Khaitan', 'Varun Dhawan, Alia Bhatt, Gauhar Khan, Girish Karnad', 'http://www.21cineplex.com/data/gallery/pictures/148905796917849_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/ztX-iGlZ_Ug" frameborder="0" allowfullscreen></iframe>', 'tt6277440', 0, 0, 0, 0, 0, 2),
(25, 'DANGAL', 'Mahavir Singh Phogat (Aamir Khan) yang pernah menjuarai sebuah turnamen gulat memiliki mimpi untuk memenangkan medali emas untuk kompetisi gulat dunia. Namun, masalah finansial memaksanya pensiun dari karirnya sebagai pegulat profesional. Pada saat itu Phogat mengharapkan jika kelak anak lelakinya dapat meneruskan cita-citanya. Akan tetapi Phogat merasa putus asa setelah istrinya melahirkan empat anak perempuan. Beberapa tahun kemudian ia melihat kedua anak perempuannya, Geeta dan Babita mengalahkan dua orang anak laki-laki. Phogat menyadari bakat mereka dan mulai melatih anak-anaknya menjadi pegulat profesional.', 'Action, Biography, Drama', 2016, '2016-12-21', 161, 'Nitesh Tiwari', 'Piyush Gupta, Shreyas Jain, Nikhil Mehrotra, Nitesh Tiwari', 'Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh, Sanya Malhotra', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ4MzQzMzM2Nl5BMl5BanBnXkFtZTgwMTQ1NzU3MDI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/x_7YlGv9u1g" frameborder="0" allowfullscreen></iframe>', 'tt5074352', 9, 0, 0, 0, 0, 2),
(26, 'NOBITA AND THE BIRTH OF JAPAN', 'DORAEMON THE MOVIE: NOBITA AND THE BIRTH OF JAPAN - Dalam film Doraemon terbaru, Nobita dan teman-teman menempuh perjalanan waktu untuk kembali ke Jepang di masa prasejarah dimana mereka akan membangun sebuah kota impian. Di waktu yang sama, mereka bertemu dengan seorang bocah bernama Kukuru yang berada dalam masalah karena sukunya ditindas oleh dukun misterius bernama Gigazombie. Mampukah Nobita dan kawan-kawan menyelamatkan Kukuru beserta anggota sukunya yang tertindas?', 'Animation', 2016, '2016-01-26', 103, 'Shinnosuke Yakuwa', 'Shinnosuke Yakuwa, Higashi Shimzu', 'Wasabi Mizuta, Megumi Ohara, Yumi Kakazu, Subaru Kimura, Tomokazu Seki', 'http://www.21cineplex.com/data/gallery/pictures/148705623580169_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/aPtam_mNZdA" frameborder="0" allowfullscreen></iframe>', '', 0, 0, 0, 0, 7, 2),
(27, 'GALIH DAN RATNA', 'Cinta pertama. Atau cinta monyet. Atau apalah itu. Semua pasti pernah merasakannya, terutama di masa-masa remaja yang indah. Tetapi ini tidak pernah dirasakan oleh GALIH (Refal Hady), seorang siswa SMA teladan tetapi introvert yang hidup dalam bayang-bayang almarhum ayahnya dan tuntutan ibunya yang harus struggle sebagai single-mother. \r\n\r\nRATNA (Sheryl Sheinafia), seorang siswi yang baru saja pindah ke SMA tempat Galih bersekolah. Pintar dan berbakat namun ia sendiri tidak tahu passion hidupnya apa. Ia hidup tanpa tujuan, selalu mengejar hal-hal yang sangat instan. Layaknya anak millenials saat ini. \r\n\r\nDi suatu sore, di lapangan belakang sekolah, Galih dan Ratna pun bertemu. Sebuah pertemuan yang sederhana. Ratna tertarik dengan walkman yang sedang didengarkan oleh Galih. Galih membiarkan Ratna mendengarkan kaset mixtape pemberian Ayahnya. \r\n\r\nInikah yang disebut dengan cinta pertama? Yang manis, menggebu-gebu, dan juga pahit? Yang berawal dari sebuah momen sederhana di lapangan belakang sekolah? Pada akhirnya, cinta pertama inilah yang membawa Galih dan Ratna ke tahap baru dalam kehidupan mereka. Sebuah tahap pendewasaan dimana tanggung-jawab, tuntutan, dan passion saling berperang dan akhirnya berdamai. Dan cinta pertama inilah yang akan selalu menjadi sebuah kenangan yang tidak akan mereka lupakan.', 'Drama', 2017, '2017-03-09', 112, 'Lucky Kuswandi', 'Fathan Todjon, Lucky Kuswandi', 'Refal Hady, Sheryl Sheinafia, Joko Anwar, Marissa Anita', 'http://www.21cineplex.com/data/gallery/pictures/14864580058957_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/Ks0lO3zCWOQ" frameborder="0" allowfullscreen></iframe>', '', 0, 0, 0, 0, 0, 2),
(28, 'HIDDEN FIGURES', 'Berkisah tentang tim ahli matematika wanita Afrika-Amerika yang memiliki peran penting dalam sejarah NASA.\r\n\r\nKatherine G. Johnson (Taraji P. Henson), Dorothy Vaughan (Octavia Spencer) dan Mary Jackson (Janelle Monae) adalah sosok penting dibalik keberhasilan NASA dalam proyek pertama mereka membawa manusia keluar angkasa.\r\n\r\nKetiganya merupakan ahli matematika yang membuat perhitungan terhadap pesawat yang akan digunakan pada misi pertama NASA untuk mendarat di bulan.', 'Biography, Drama, History', 2016, '2017-01-06', 126, 'Theodore Melfi', 'Allison Schroeder (screenplay), Theodore Melfi (screenplay), Margot Lee Shetterly (based on the book by)', 'Taraji P. Henson, Octavia Spencer, Janelle Monáe, Kevin Costner', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjQxOTkxODUyN15BMl5BanBnXkFtZTgwNTU3NTM3OTE@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/RK8xHq6dfAo" frameborder="0" allowfullscreen></iframe>', 'tt4846340', 7.9, 74, 0, 0, 0, 1),
(29, 'JOHN WICK: CHAPTER 2', 'Berlanjut dari film John Wick yang pertama, film ini kembali menampilkan Keanu Reeves sebagai pensiunan pembunuh bayaran, John Wick yang kembali beraksi. Kali ini John harus harus menghadapi krisis identitas yang mempertanyakan jati dirinya sebagai seorang suami yang bersedih atas kematian istrinya atau seorang pembunuh bayaran internasional tanpa belas kasihan.', 'Action, Crime, Thriller', 2017, '2017-02-10', 122, 'Chad Stahelski', 'Derek Kolstad, Derek Kolstad (based on characters created by)', 'Keanu Reeves, Riccardo Scamarcio, Ian McShane, Ruby Rose', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjE2NDkxNTY2M15BMl5BanBnXkFtZTgwMDc2NzE0MTI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/XGk2EfbD_Ps" frameborder="0" allowfullscreen></iframe>', 'tt4425200', 8.5, 75, 0, 0, 9, 2),
(30, 'KONG SKULL ISLAND', 'Pada tahun 1970an, sekelompok tim penjelajah dikirim untuk menelusuri sebuah pulau misterius bernama Skull Island yang terletak di samudera Hindia. Mereka segera menyadari ancaman yang terdapat di pulau tersebut sebab Skull Island adalah rumah dari kera raksasa bernama King Kong yang memiliki kekuatan dahsyat dan kecerdasan yang menyerupai manusia.', 'Action, Adventure, Fantasy', 2017, '2017-03-10', 119, 'Jordan Vogt-Roberts', 'Dan Gilroy (screenplay), Max Borenstein (screenplay), John Gatins (story), Dan Gilroy (story), Merian C. Cooper (original story), Edgar Wallace (original story)', 'Tom Hiddleston, Corey Hawkins, Brie Larson, Samuel L. Jackson', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTUwMzI5ODEwNF5BMl5BanBnXkFtZTgwNjAzNjI2MDI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/44LdLqgOpjo" frameborder="0" allowfullscreen></iframe>', 'tt3731562', 0, 0, 0, 0, 0, 1),
(31, 'LA LA LAND', 'Mia (Emma Stone), seorang perempuan yang bercita-cita tinggi untuk menjadi aktris kerap berpapasan dengan Sebastian (Ryan Gosling), musisi jazz yang bercita-cita untuk mendirikan klub jazznya sendiri. \r\n\r\nKedua orang tersebut akhirnya saling jatuh cinta dan bakhan Mia pun mulai menyukai musik Jazz. Pada suatu hari, Mia mulai meragukan kemampuannya setelah ia kerap gagal dalam mengikuti audisi film. Sebastian yang percaya dengan kemampuan akting Mia, kerap mendorong kekasihnya agar tidak menyerah. Sementara itu, Mia berpikir bahwa Sebastian terpaksa bergabung kedalam band terkenal demi mencari nafkah untuk mereka berdua. \r\n\r\nPada akhirnya, perbedaan dan perdebatan diantara keduanya pun kian melebarkan jarak diantara mereka.', 'Comedy, Drama, Musical', 2016, '2016-12-25', 128, 'Damien Chazelle', 'Damien Chazelle', 'Ryan Gosling, Emma Stone, Amiée Conn, Terry Walters', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/0pdqf4P9MB8" frameborder="0" allowfullscreen></iframe>', 'tt3783958', 8.5, 93, 0, 0, 0, 2),
(32, 'LION', 'Ketika Saroo baru berusia lima tahun, ia hidup dalam kemiskinan bersama ibu dan saudara-saudaranya di sebuah kota di India. Saroo dan kakak lelakinya, Guddu sering pergi bersama untuk mengemis di sebuah stasiun kereta. Pada suatu hari, Guddu memberitahu adiknya jika ia akan naik kereta ke kota lain. Mendengar perkataan ini, Saroo memohon kakanya untuk ikut bersamanya. Guddu mengabulkan permohonan adiknya dan pada saat mereka sampai di tempat tujuan, Guddu memberitahu Saroo untuk menunggunya di sebuah peron kereta. \r\n\r\nSaat Guddu tidak kunjung kembali, Saroo mulai mencari saudaranya dengan memasuki sebuah kereta yang membawanya ke tempat yang jauh. Karena sang anak tidak dapat memberitahu polisi alamat tempat tinggalnya, ia dinyatakan sebagai anak terlantar. Bocah India tersebut pada akhirnya diadopsi oleh sepasang suami-istri yang berasal dari Australia.\r\n\r\nKetika Saroo hidup dengan keluarga barunya, ia dibesarkan sebagai anak Australia pada umumnya dan kemampuannya untuk berbicara dalam bahasa Hindi kian menghilang. Sementara itu, ibu kandungnya di India tidak berhenti untuk mencari anaknya.', 'Drama', 2016, '2017-01-06', 118, 'Garth Davis', 'Saroo Brierley (adapted from the book ', 'Sunny Pawar, Abhishek Bharate, Priyanka Bose, Khushi Solanki', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjA3NjkzNjg2MF5BMl5BanBnXkFtZTgwMDkyMzgzMDI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/-RNI9o06vqo" frameborder="0" allowfullscreen></iframe>', 'tt3741834', 8, 69, 0, 0, 0, 2),
(33, 'LOGAN', 'Pada tahun 2024, Logan (Hugh Jackman) dan Profesor Charles Xavier (Patrick Stewart) harus bertahan tanpa X-Men ketika perusahaan yang dipimpin oleh Nathaniel Essex menghancurkan dunia. Keadaan menjadi semakin rumit dengan kemampuan regenerasi mutan logan yang mulai menghilang dan Xavier yang menderita Alzheimer. Logan harus mengalahkan Nathaniel Essex dengan bantuan seorang anak perempuan bernama Laura Kinney yang merupakan hasil kloning dari Wolverine', 'Action, Drama, Sci-fi', 2017, '2017-03-03', 136, 'James Mangold', 'James Mangold (story by), Scott Frank (screenplay), James Mangold (screenplay), Michael Green (screenplay)', 'Hugh Jackman, Patrick Stewart, Dafne Keen, Boyd Holbrook', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjI1MjkzMjczMV5BMl5BanBnXkFtZTgwNDk4NjYyMTI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/DekuSxJgpbY" frameborder="0" allowfullscreen></iframe>', 'tt3315342', 8.7, 77, 0, 0, 7.5, 2),
(34, 'LONDON LOVE STORY 2', '“Aku bersyukur..\r\nsemua hari hariku begitu berarti..\r\nDan Aku akan tetap minta sama Tuhan, \r\nuntuk ambil nyawa aku satu hari sebelum Tuhan ambil nyawanya\r\nKarena setiap detak jantungnya, adalah detik berharga untuk aku”\r\n\r\nCaramel sangat bahagia. Betapa tidak, impiannya sejak kecil untuk melihat dan bermain salju akhirnya terwujud karena Dave memberinya hadiah kejutan liburan ke Swiss untuk merayakan ulang tahun Caramel.\r\n\r\nsaat mereka akan berangkat menggunakan kereta dari stasiun St. Pancras International London ke Swiss, Tiba-tiba Dave tidak bisa berangkat bersama Caramel.\r\n\r\nSesampainya di sana, Sam yang sudah menjemput Caramel membawa Caramel makan malam di sebuah resto terbaik di kota Zurich, hingga Caramel sangat terkesan.\r\n\r\nSayangnya kebahagiaan Caramel menikmati hari pertamanya di Swiss, terganggu karena kemunculan Gilang, seorang chef sekaligus cucu pemilik restoran di Swiss. Gilang meminta Caramel untuk menemuinya di sebuah restoran. Caramel datang dan menemui Gilang. Gilang memberikan sebuah hadiah untuk Caramel.\r\n\r\nSetelah itu Gilang meminta Caramel menemuinya lagi keesokan harinya. Apakah Dave tahu tentang ini, Apakah Gilang mengetahui kalau Caramel adalah tunangan Dave..??', 'Drama', 2017, '2017-03-03', 100, 'Asep Kusdinar', 'Sukhdev Singh, Tisa TS', ' Ramzi. Salshabilla Adriani. Mawar Eva', 'http://www.21cineplex.com/data/gallery/pictures/148611950965983_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/_OeuFCIpFhg" frameborder="0" allowfullscreen></iframe>', 'tt3315342', 8.7, 77, 0, 0, 0, 2),
(35, 'MAX STEEL', 'Max McGrath (Ben Winchell) adalah seorang remaja berusia 16 tahun yang tengah beradaptasi dengan lingkungan barunya. Tidak lama sejak kepindahannya, ia menemukan bahwa sang almarhum ayah yang pernah bekerja sebagai ilmuwan telah mewariskan kekuatan super yang dapat merubah energi di sekelilingnya. \r\n\r\nKemudian Max juga bertemu dengan alien bernama Steel yang melatihnya untuk menggunakan kekuatannya sebagai seorang super hero bernama Max Steel. Ketika keduanya saling bekerja sama dalam misi membela kebenaran, beberapa makhluk misterius dari galaksi lain memburu Max untuk merebut kekuatan yang dimilikinya.', 'Action, Adventure, Family', 2016, '2016-10-14', 92, 'Stewart Hendler', 'Christopher Yost', 'Ben Winchell, Josh Brener, Maria Bello, Andy Garcia', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2MTMwOTk3N15BMl5BanBnXkFtZTgwMDI5OTYxMDI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/Tf4sa0BVJVw" frameborder="0" allowfullscreen></iframe>', 'tt1472584', 4.6, 22, 0, 0, 6.5, 2),
(36, 'JAKARTA UNDERCOVER', 'MOAMMAR EMKAS JAKARTA UNDERCOVER - Demi mengejar cita-citanya menjadi wartawan, Pras (Oka Antara) berangkat ke Jakarta untuk berguru pada Djarwo (Lukman Sardi), pemimpin redaksi sebuah majalah berita. Idealisme Pras mulai luntur saat menyadari bahwa kecemerlangan tulisannya dimanfaatkan oleh kantornya untuk tujuan tertentu.\r\n\r\nJiwa Pras memberontak. Apalagi setelah ia bertemu Awink (Ganindra Bimo), penari malam, yang membawanya berkenalan dengan Yoga (Baim Wong), sosok penting di dunia bisnis "gelap" Jakarta. Di sisi lain, Pras bertemu dengan Laura (Tiara Eve), perempuan super model yang membuat hidupnya berbeda, begitupun Laura yang menganggap Pras anomali dari kebanyakan lelaki yang ditemuinya di Jakarta.\r\n\r\nTanpa disadari, Pras berada di tengah pusaran dunia antah berantah Jakarta. Semakin dalam ia menggali, semakin jauh ia terseret ke dalamnya. Bagaimana Pras menghadapi kerasnya kehidupan di Jakarta?', 'Drama', 2016, '2016-10-14', 107, 'Stewart Hendler', 'Christopher Yost', 'Ben Winchell, Josh Brener, Maria Bello, Andy Garcia', 'http://www.21cineplex.com/data/gallery/pictures/148523068742889_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/5zMCsU5ncrM" frameborder="0" allowfullscreen></iframe>', 'tt1472584', 4.6, 22, 0, 0, 0, 2),
(37, 'RINGS', 'Film yang merupakan seri ketiga dari trilogi The Ring ini terjadi sebelum pembuatan video terkutuk yang akan membunuh siapa saja yang pernah menontonnya. Selain itu film ini juga berfokus pada keseharian seorang pelajar bernama Julia (Matilda Lutz) dan kekasihnya, Holt (Alex Roe). \r\n\r\nKhawatir akan hubungan mereka yang semakin renggang, Julia memutuskan untuk pergi menemui Holt. Ketika ia sampai, Julia menemukan jika kekasihnya adalah anggota dari sebuah klub yang menyebarkan video terkutuk Samara. Selain itu, Julia harus dihadapkan dengan kenyataan bahwa Holt telah menonton video tersebut enam setengah hari yang lalu dan mereka harus menemukan jalan untuk menghentikan kutukan Samara sebelum terlambat.', 'Drama, Horror', 2017, '2017-02-03', 102, 'F. Javier Gutiérrez', 'David Loucka (screenplay), Jacob Estes (screenplay), Akiva Goldsman (screenplay), David Loucka (story by), Jacob Estes (story by), Kôji Suzuki (based on the novel ', 'Matilda Anna Ingrid Lutz, Alex Roe, Johnny Galecki, Vincent D''Onofrio', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNjU1NDAxNTg0MF5BMl5BanBnXkFtZTgwNzUxMjEwMTI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/uukQ_6szDm8" frameborder="0" allowfullscreen></iframe>', 'tt0498381', 4.5, 25, 0, 0, 0, 2),
(38, 'SILENCE', 'Berkisah mengenai kedua misionaris Katholik (Andrew Garfield and Adam Driver) yang menghadapi ujian atas keyakinan merek ketika keduanya pergi ke Jepang untuk mencari guru mereka yang hilang (Liam Neeson) - tepat di saat keberadaan umat Katholik terancam di Jepang', 'Drama, History', 2016, '2017-01-13', 160, 'Martin Scorsese', 'Jay Cocks (screenplay), Martin Scorsese (screenplay), Shûsaku Endô (based on the novel by)', 'Andrew Garfield, Adam Driver, Liam Neeson, Tadanobu Asano', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjY3OTk0NjA2NV5BMl5BanBnXkFtZTgwNTg3Mjc2MDI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/A0KUWzfugg4" frameborder="0" allowfullscreen></iframe>', 'tt0490215', 7.5, 79, 0, 0, 0, 2),
(39, 'SPLIT', 'Ketika ketiga gadis remaja sedang menunggu ayah mereka di dalam mobil, seorang pria misterius menculik dan membawa mereka ke dalam sebuah bunker. Sang penculik yang bernama Kevin (James McAvoy) adalah seorang pria dengan gangguan jiwa yang membuatnya memiliki 23 kepribadian yang berbeda, yang diantaranya adalah seorang wanita dan anak berumur 9 tahun yang bernama Hedwig. \r\n \r\nSebagai salah satu gadis yang diculik, Casey berusaha meloloskan diri dengan meyakinkan salah satu kepribadian Kevin untuk melepaskan mereka. Akan tetapi hal tersebut tidaklah mudah, terlebih setelah Hedwig memperingatkan mereka akan the Beast yang merupakan kepribadian Kevin yang paling berbahaya.', 'Horror, Thriller', 2016, '2017-01-20', 117, 'M. Night Shyamalan', 'M. Night Shyamalan', 'James McAvoy, Anya Taylor-Joy, Betty Buckley, Haley Lu Richardson', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZTJiNGM2NjItNDRiYy00ZjY0LTgwNTItZDBmZGRlODQ4YThkL2ltYWdlXkEyXkFqcGdeQXVyMjY5ODI4NDk@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/84TouqfIsiI" frameborder="0" allowfullscreen></iframe>', 'tt4972582', 7.5, 62, 0, 0, 0, 2),
(40, 'SURGA YANG TAK DIRINDUKAN 2', 'Pertemuan dengan Arini membuat Meirose menjadi ragu dengan pilihan hidupnya selama ini. Arini begitu tulus menyayangi dirinya dan Akbar, dan berharap agar Meirose kembali pada Pras. Mereka sudah menjadi keluarga. Apalagi ketika sosok Pras muncul dihadapannya, Meirose tidak bisa mengingkari bahwa cintanya pada laki-laki bijak itu masih ada dalam hatinya. Bahkan Arini didukung Nadia, berusaha keras menarik Meirose kembali.\r\n\r\nMeirose bingung, maju dengan kehidupannya yang baru, yang dia sendiri tidak tahu akan jadi seperti apa, ataukah mundur pada kehidupannya yang lama, yang ingin dia tinggalkan selama ini, tapi menjanjikan hal yang lebih pasti bagi masa depannya?\r\n\r\nAda apa dibalik motivasi Arini yang menggebu-gebu meminta Meirose kembali dalam kehidupan rumah tangganya yang sudah harmonis selama ini?\r\n\r\nApa yang akan dilakukan Pras, akankah dia kembali menerima Meirose? Sementara, dia meragukan kemampuannya untuk bersikap adil sebagaimana yang diwajibkan Allah pada laki-laki yang memilih berpoligami?\r\n\r\nSiapa juga Dokter Syarief(Reza Rahardian) yang tiba-tiba hadir di tengah-tengah persoalan mereka?\r\n\r\nLalu mengapa surga itu tiba-tiba menjadi dirindukan sekarang?', 'Drama', 2017, '2017-02-09', 121, 'Hanung Bramantyo, Meisa Felaroze', 'Alim Sudio, Hanung Bramantyo, Manoj Punjabi', 'Reza Rahadian, Raline Shah, Laudya Cynthia Bella, Fedi Nuril', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTZiZjU4MDEtOWFjZS00YWZkLTg1MGMtNDcxNTdhMDE3NWU2XkEyXkFqcGdeQXVyNjU3MzA0NjE@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/DpUXJVbb894" frameborder="0" allowfullscreen></iframe>', 'tt5946936', 0, 0, 0, 0, 0, 2),
(41, 'ULAR TANGGA', 'FINA (20), mahasiswi berwatak serius dan memiliki potensi indigo, sebenarnya sudah memiliki firasat buruk. Mimpi buruk yang muncul dalam tidurnya seperti menghidupkan alarm bahaya dalam diri FINA. Hal itu terkait dengan rencana mendaki gunung tim pecinta alam kampusnya. Kebetulan, tim yang akan berangkat dalam pendakian itu dipimpin BAGAS (21), kekasih FINA. BAGAS tidak percaya pada kekhawatiran FINA. Ia malah membujuk FINA untuk tetap berangkat bersama tim pecinta alam yang beranggotakan empat mahasiswa lain: MARTHA, WILLIAM, DODOY, dan LANI. Pada tahap awal, perjalanan mereka dibantu GINA, seorang pendaki dan penunjuk jalan yang sudah lebih dulu berpengalaman dan mengenal medan di gunung tersebut.\r\n\r\nSayangnya, peringatan GINA agar mereka memilih jalan yang aman, tidak diindahkan oleh teman-teman FINA. Tanpa mereka sadari, jalan yang mereka pilih mengantarkan mereka menuju pohon tua yang angker dan rumah misterius di gunung yang memiliki cerita kelam di masa lalu. FINA baru menyadari bahaya mengancam dirinya dan teman-temannya. Kemunculan dua hantu anak kecil, SANIA dan TANIA, seolah menjadi pertanda akan bahaya yang mengancam mereka. Mereka tersesat di gunung, dan terpaksa bertahan di rumah misterius yang sudah kosong bertahun-tahun.\r\n\r\nNamun, saat mereka berkeinginan turun gunung segalanya sudah terlambat. Kejadian buruk menimpa mereka satu per satu. Semua itu diawali dengan penemuan permainan kuno ular tangga yang terbuat dari kayu, di bawah pohon angker itu. Penemuan itu memunculkan kembali hantu yang sangat berbahaya. Hantu yang penuh kemarahan karena pohon angker yang menjadi tempat tinggalnya, dirusak pada masa lalu. Seseorang telah memotong cabang pohon tersebut dan membuatnya menjadi ukiran permainan ULAR TANGGA. Peristiwa terkutuk yang memakan korban jiwa.', 'Thriller', 2016, '1970-01-01', 94, 'Arie Azis', 'N/A', 'Shareefa Daanish, Guntur Triyoga, Fauzan Nasrul, Alessia Cestaro', 'http://ia.media-imdb.com/images/M/MV5BNTA4OWE2MDItZGQ2My00YWU2LTkyOWYtMWViMDQ0YjcyMmEzXkEyXkFqcGdeQXVyMjIyNDU1OTg@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/NgATJRgFlHg" frameborder="0" allowfullscreen></iframe>', 'tt5742836', 0, 0, 0, 0, 0, 2),
(42, 'GUARDIANS OF THE GALAXY 2', 'Pada seri kedua film Guardian of the Galaxy, Peter Quills (Chris Pratt) dan para Guardians kembali melanjutkan petualangan mereka dengan menjelajahi bagian terluar dari kosmos. Kali ini, persahabatan para Guardians akan diuji pada saat mereka mengungkap misteri dari silsilah keluarga Peter Quill. Di film ini juga, seorang musuh lama akan muncul kembali untuk membantu para Guardians dalam misi mereka', 'Action, Adventure, Sci-fi', 2017, '2017-06-17', 137, 'James Gunn', 'James Gunn, Dan Abnett', 'Chris Pratt, Zoe Saldana, Sylvester Stallone', 'http://www.21cineplex.com/data/gallery/pictures/149086206646137_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/duGqrYw4usE" frameborder="0" allowfullscreen></iframe>', 'tt3896198', 0, 0, 0, 0, 0, 0),
(43, 'THE INFILTRATOR', 'Seorang pejabat Bea Cukai AS Robert Mazur (Bryan Cranston) melakukan penyamaran untuk menyusup ke dalam jaringan perdagangan narkoba yang diatur oleh mafia besar asal Kolumbia, Pablo Escobar.\r\n\r\nMazur menyamar sebagai Bob Musella seorang pengusaha pencucian uang. Dengan penuh resiko yang mengancam keselamatan jiwanya, Mazur bersama agen lainnya mencoba membongkar praktik pencucian uang yang dilakukan Pablo dengan bangkir korup dan 85 gembong narkoba lainnya.', 'Biography, Crime, Drama', 2016, '2016-07-13', 127, 'Brad Furman', 'Ellen Sue Brown (screenplay), Robert Mazur (based on the book on)', 'Bryan Cranston, Leanne Best, Daniel Mays, Tom Vaughan-Lawlor', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTEwNzM2NjY2MTNeQTJeQWpwZ15BbWU4MDQ3MDI3Njgx._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/N7_M4hjXW1I" frameborder="0" allowfullscreen></iframe>', 'tt1355631', 7.1, 66, 0, 0, 0, 0),
(44, 'AFTERMATH', 'Seorang supervisor konstruksi Roman (Arnold Schwarzenegger) sangat bahagia menunggu kedatangan istri dan anaknya pulang kembali ke rumah. Sayangnya, harapan Roman berkumpul bersama keluarganya pupus, ia tidak akan pernah bisa bertemu lagi dengan istri dan anaknya di rumah. Keluarganya meninggal dalam kecelakaan pesawat.\r\n\r\nDi ketahui penyebab kecelakaan tersebut adalah akibat kelalaian pengatur lalu lintas udara yang saat itu bertugas, Jake (Scoot McNairy) bertanggung jawab pada kecelakaan tersebut. Sakit hati dengan kejadian tersebut, Roman bersikeras membalaskan dendamnya dan ingin Jake membayar rasa kehilangannya akan orang-orang yang dikasihinya.', 'Short, Horror', 1994, '1994-10-08', 30, 'Nacho Cerdà', 'Nacho Cerdà', 'Pep Tosar, Jordi Tarrida, Ángel Tarris, Xevi Collellmir', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTc5MDY1MTU4M15BMl5BanBnXkFtZTcwMTU1OTAzMQ@@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/ZN8toxhSn9Y" frameborder="0" allowfullscreen></iframe>', 'tt0159241', 6, 0, 0, 0, 0, 0);
INSERT INTO `film` (`id`, `title`, `summary`, `genre`, `year`, `playing_date`, `length`, `director`, `writer`, `actors`, `poster`, `trailer`, `imdb_id`, `imdb_rating`, `metascore`, `twitter_positif`, `twitter_negatif`, `rating`, `status`) VALUES
(45, 'GET OUT', 'Film ini mengisahkan seorang pemuda berkulit hitam bernama Chris (Daniel Kaluuya) yang mengunjungi rumah orang tua kekasihnya yang berkulit putih Rose (Allison Williams).\r\n\r\nDia tak pernah mengira kunjungannya akan menjadi sebuah kejadian yang buruk bagi dirinya hingga seorang pria sesama kulit hitam memperingatkannnya untuk "keluar". Kemudian Chris menyadari bahwa untuk "Keluar" jauh lebih sulit dari yang ia bayangkan.', 'Horror, Mystery', 2017, '2017-02-24', 104, 'Jordan Peele', 'Jordan Peele', 'Daniel Kaluuya, Allison Williams, Catherine Keener, Bradley Whitford', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNTE2Nzg1NjkzNV5BMl5BanBnXkFtZTgwOTgyODMyMTI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/sRfnevzM9kQ" frameborder="0" allowfullscreen></iframe>', 'tt5052448', 8.3, 83, 0, 0, 0, 1),
(46, 'KARTINI', 'Kartini tumbuh dengan melihat langsung bagaimana ibu kandungnya, Ngasirah (Christine Hakim) menjadi orang terbuang di rumahnya sendiri, dianggap pembantu hanya karena tidak mempunyai darah ningrat. Ayahnya, Raden Sosroningrat (Deddy Sutomo), yang mencintai Kartini dan keluarga juga tidak berdaya melawan tradisi.\r\n\r\nSepanjang hidupnya, Kartini memperjuangkan kesetaraan hak bagi semua orang, tidak peduli ningrat atau bukan, terutama hak pendidikan untuk perempuan. Bersama kedua saudarinya, Roekmini (Acha Septriasa) dan Kardinah (Ayushita Nugraha), Kartini mendirikan sekolah untuk kaum miskin dan menciptakan lapangan kerja untuk rakyat di Jepara dan sekitarnya. \r\n\r\nFilm Kartini adalah perjuangan emosional dari sosok Kartini yang harus melawan tradisi dan bahkan menentang keluarganya sendiri untuk memperjuangkan kesetaraan hak untuk semua orang di Indonesia.', 'Biography, Drama, Family', 2017, '2017-04-01', 122, 'Hanung Bramantyo', 'Bagus Bramanti, Hanung Bramantyo, Hanung Bramantyo, Robert Ronny (additional stories), Robert Ronny (story)', 'Adinia Wirasti, Reza Rahadian, Christine Hakim, Dian Sastrowardoyo', 'https://images-na.ssl-images-amazon.com/images/M/MV5BZDZjY2EzZjAtODQzOC00NmE1LTk1MGYtOGQ4YWYyN2I3NmY0XkEyXkFqcGdeQXVyMTE4OTcyMA@@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/ePQV41Rk9uw" frameborder="0" allowfullscreen></iframe>', 'tt5882416', 0, 0, 0, 0, 0, 0),
(47, 'THE GUYS', 'Alfi, seorang karyawan yang bercita-cita jadi bos, ingin mendapatkan cinta Amira, teman sekantornya. Namun, masalah timbul ketika Via, gebetan abadinya, yang tadinya mengabaikan Alfi, mulai menujukkan rasa cinta..  Di satu sisi, ketika Alfi dekat dengan Amira, ternyata', 'Drama', 2017, '2017-11-20', 84, 'Raditya Dika', 'Raditya Dika', 'Raditya Dika, Pevita Pearce, Marthino Lio', 'http://www.21cineplex.com/data/gallery/pictures/148964775232770_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/JxTmtJ0Fc2U" frameborder="0" allowfullscreen></iframe>', 'tt0319470', 6.5, 60, 0, 0, 0, 1),
(48, 'LABUAN HATI', 'Bia, Indi dan Maria adalah tiga perempuan yang bertemu di Labuan Bajo, Flores, NTT. Hidup di atas kapal, menyelam, bertemu komodo hingga menginap di sebuah pulau yang sama... Tiga perempuan dengan latar belakang berbeda, alasan berbeda, dan tujuan berbeda dengan cepat bersahabat karena kecintaan yang sama: kepada laut, permukaan maupun kedalaman.\r\n\r\nDan ada Mahesa, instruktur diving yang terus mendampingi mereka, yang kemudian menjadi salah satu alasan mereka merasa ada yang salah dengan hidup masing-masing.\r\n\r\nPadahal... tak ada yang salah. Setiap perempuan berhak bersedih atas masa lalu, berhak berbahagia untuk hari ini, dan berhak selalu punya harapan akan masa depan, tanpa perlu mengutuk hidup yang tak melulu baik-baik saja.', 'Drama', 2017, '2017-11-20', 101, 'Lola Amaria', 'Titien Wattimena', 'Kelly Tandiono, Nadine Chandrawinata, Ully Triani', 'http://www.21cineplex.com/data/gallery/pictures/148964668873702_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/D3S_F07qmkY" frameborder="0" allowfullscreen></iframe>', 'tt0319470', 6.5, 60, 0, 0, 0, 1),
(49, 'HAND OF STONE', 'Hands of Stone akan berkisah tentang kehidupan Roberto Duran (Edgar Ramirez) yang menjadi seorang petinju profesional saat masih berusia 16 tahun. \r\n\r\nDibawah pelatih Ray Arcel (Robert De Niro) Ia menjadi salah satu petarung hebat di masanya dengan mengalahkan petinju terkenal Sugar Ray Leonard.', 'Drama', 2017, '2017-11-20', 110, 'Jonathan Jakubowicz', 'Jonathan Jakubowicz', 'Edgar Ramirez, Ellen Barkin, John Turturro', 'http://www.21cineplex.com/data/gallery/pictures/14897369646193_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/1W1L0WnVnjY" frameborder="0" allowfullscreen></iframe>', 'tt0319470', 6.5, 60, 0, 0, 0, 0),
(50, 'THE WORST YEARS OF MY LIFE', 'MIDDLE SCHOOL: THE WORST YEARS OF MY LIFE\r\n\r\nRafe Khatchadorian (Griffin Gluck) adalah remaja yang memiliki imajinasi tinggi. Namun ia punya banyak masalah, mulai dengan pacar sang Ibu sampai lingkungan baru di sekolah. \r\n\r\nMasalah terbesar Rafe adalah sang kepala sekolah Dwight (Andrew Daly) yang selalu mengekang kreativitas murid di sekolah dan ketat terhadap peraturan. \r\n\r\nMisi dilakukan Rafe bersama Leo (Thomas Barbusca) dan teman-tema sekolanya untuk membalas perlakuan sang kepala sekolah yang otoriter.', 'Comedy, Family', 2016, '2016-10-07', 92, 'Steve Carr', 'Chris Bowman (screenplay), Hubbel Palmer (screenplay), Kara Holden (screenplay), James Patterson (based on the book by), Chris Tebbetts (based on the book by)', 'Griffin Gluck, Lauren Graham, Alexa Nisenson, Andrew Daly', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNjQzMTczNjI0Ml5BMl5BanBnXkFtZTgwODY5MTY5OTE@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/XQtjPUyS6ZY" frameborder="0" allowfullscreen></iframe>', 'tt4981636', 6.1, 51, 0, 0, 0, 0),
(51, 'SWEET 20', 'Fatmawati (Niniek L Karim), nenek 70 tahun cerewet yang tinggal bersama putranya seorang dosen, Aditya (Lukman Sardi), menantu (Cut Mini), dan 2 orang cucu (Kevin Julio, Alexa Key). Fatmawati selalu membanggakan Aditya, sampai suatu hari ia mengetahui akan dikirim ke panti jompo. Hal yang membuatnya sangat terpukul dan pergi dari rumah. Di perjalanan ia melihat studio foto “Forever Young”, dan berniat mengambil foto untuk di pemakamannya kelak. Namun setelah berfoto Fatmawati berubah menjadi 50 tahun lebih muda, dan kembali berusia 20 tahun. Fatmawati pun memulai kehidupan yang baru dan mengganti namanya menjadi Mieke, seperti nama artis idolanya Mieke Wijaya. Seiring berjalannya waktu, Mieke mendapat kesempatan untuk meraih mimpinya menjadi penyanyi, sesuatu yang tidak bisa dilakukannya pada saat muda dulu. Keunikan Mieke muda dengan gaya bicara dan seleranya yang masih seperti nenek 70 tahun, justru membuat 3 pria jatuh hati padanya, seorang produser musik (Morgan Oey), cucu laki-lakinya, dan Hamzah (Slamet Rahardjo) yang mencintainya sejak sama-sama muda dulu.\r\n\r\nHingga suatu peristiwa terjadi, yang membuat Mieke harus memilih untuk melanjutkan kehidupan barunya, atau kembali menjadi Fatmawati.', 'Comedy, Family', 2016, '2016-10-07', 92, 'Steve Carr', 'Chris Bowman (screenplay), Hubbel Palmer (screenplay), Kara Holden (screenplay), James Patterson (based on the book by), Chris Tebbetts (based on the book by)', 'Griffin Gluck, Lauren Graham, Alexa Nisenson, Andrew Daly', 'http://www.21cineplex.com/data/gallery/pictures/149086177359456_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/dZb6uIoVFIg" frameborder="0" allowfullscreen></iframe>', 'tt4981636', 6.1, 51, 0, 0, 0, 0),
(52, 'THE CURSE', 'Shelina seorang pengacara ekspatriat Indonesia bekerja disalah satu law firm ternama di Melbourne Australia.\r\n \r\nSuatu malam Shelina didatangi roh halus di rumahnya. Penampakan roh halus itu semakin hari semakin jelas dan sangat menakutkan. Akhirnya Shelina memanggil paranormal dari Indonesia guna melakukan pengusiran. Hasil ritual paranormal menemukan, roh halus itu mendatangi Shelina untuk menyampaikan pesan. Dan roh halus itu mempunyai kaitan yang sangat erat dengan Shelina.\r\n \r\nTeka teki dibalik kedatangan roh halus, membuat Shelina harus menghadapi sesuatu yang sangat menakutkan.', 'Sci-Fi, Horror', 2017, '2017-09-11', 92, 'David Keith', 'David Chaskin (screenplay)', 'Wil Wheaton, Claude Akins, Malcolm Danare, Cooper Huckabee', 'https://images-na.ssl-images-amazon.com/images/M/MV5BOTZhM2M1NGItZTdhNS00ODMxLWJjYTQtNTQ2Yzg4ZWZhMTM2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/rvmN3mZIqdI" frameborder="0" allowfullscreen></iframe>', 'tt0092809', 4.9, 0, 0, 0, 0, 0),
(53, 'SURAU DAN SILEK', 'Adil (11th) adalah seorang anak yatim yang sangat menginginkan Ayah nya masuk surga dengan cara menjadi anak yang shaleh. Di saat yang bersamaan Adil juga sangat berambisi memenangkan pertandingan Silat di kampungnya. Ambisi Adil ini di dasari oleh kekalahan yang di alaminya pada pertandingan periode sebelumnya. Adil di kalahkan oleh Hardi (11Th) dengan kecurangan. Namun hal ini tidak di akui oleh Hardi. Karena menurut Hardi, Adil hanya mencari-cari alasan atas kekalahannya. Teman seperguruan Adil yang juga merupakan sahabatnya; Dayat (11th) dan Kurip (11th) ikut mendukung upaya membalaskan dendam kekalahan tersebut. \r\n \r\nDengan semangat yang tinggi mereka mempersiapkan diri menuju pertandingan berikutnya yang akan di adakan 6 bulan lagi. Dalam masa persiapan tersebut tiga sekawan; Adil, Dayat dan Kurip mengalami berbagai rintangan; Mulai dari guru silat mereka Rustam (27) yang pergi merantau, keinginan Adil untuk menjadi anak shaleh yang kadang bertentangan dengan ambisinya, pertikaian yang terjadi di antara Tiga Sekawan dalam memandang makna silat, Hardi dan kawan-kawan yang selalu mem-bully Adil, Dayat dan Kurip serta pencarian guru silat pengganti yang gagal disaat waktu menuju pertandingan terus berjalan.\r\n \r\n Rani (11th) merupakan teman sekolah Tiga sekawan (Adil, Kurip dan Dayat). Rani yang mengagumi Adil secara diam diam berusaha untuk mencarikan solusi terhadap kegalauan yang di hadapi oleh teman-temannya. Berkat usaha Rani inilah semua rintangan yang di hadapi oleh Tiga sekawan ini dapat teratasi. Berhasilkah Tiga Sekawan menemukan guru silat serta memenangkan pertandingan? ', 'Drama, Religi', 2017, '2017-09-11', 92, 'Arief Malinmudo', 'Arief Malinmudo', 'Dewi Irawan, Gilang Dirga, Komo Ricky', 'http://www.21cineplex.com/data/gallery/pictures/148956125842101_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/unyKxrBdHdA" frameborder="0" allowfullscreen></iframe>', 'tt0092809', 4.9, 0, 0, 0, 0, 0),
(54, 'HITAM & PUTIH', 'Ruanli dan Ashui adalah kakak beradik. Ruanli bekerja sebagai pelatih bela diri sedangkan Ashui diam-diam bekerja sebagai pemain film tanpa tahu Ruanli.\r\n\r\nSementara Yurong adalah seorang wanita polisi yang sedang menyamar, dia sedang menyelidiki kasus Narkoba kelompok Chutian. Chutian adalah direktur utama berasal dari Hongkong, dia berbisnis tempat hiburan tapi sebenarnya berbisnis gelap narkoba. \r\n\r\nRuanli dan Megda sedang berakting sebagai polisi dan penjahat. Disaat yang bersamaan Ashi dan Jinmao membawa tas hitam dengan uang. Ashi dan Jinmao kira Ruanli adalah polisi, kaget dan buru-buru kabur dengan membawa uang. Untuk menghindar dari kejaran Ruanli, uang itu di simpannya di sebuah motor yang ternyata itu adalah motor Ashui. \r\n\r\nRuanli, Adang, Azun dan Ganni merencanakan untuk menyelamatkan Ashui dari tangan Chutian. Terjadi pertukaran antara Ashui dengan Tas hitam tanpa diduga ternyata Chutian merencanakan sesuatu sampai Chutian berhasil membawa kabur Ashui sebagai sandera. Chutian berhasil di kepung, dengan akal liciknya dia berusaha membuang barang bukti demi menghindar dari hukum. \r\n\r\nBagaimana akhir kisahnya, saksikan di bioskop mulai 13 April 2017.', 'Drama, Action', 2010, '2017-04-13', 91, 'Daud Radex', 'Susan Yu', 'Roger Danuarta, Guntur Triyoga, Sunny Pang', 'http://www.21cineplex.com/data/gallery/pictures/148956110023905_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/vhiK5cDluhc" frameborder="0" allowfullscreen></iframe>', 'tt5351016', 0, 0, 0, 0, 0, 0),
(55, 'MENGEJAR HALAL', 'Kisah Haura berawal dengan batalnya pernikahan Haura dan Shidiq. Kegagalan pernikahan membuat Haura menjadi wanita yang terobsesi pada pernikahan sempurna, baginya butuh pria sempurna untuk mendapatkan pernikahan sempurna. Ditengah kegalauan menanti sosok pria sempurna, Haura dipertemukan dengan sosok Halal, pria yang memiliki semua yang diharapkan haura ada pada pasangan hidupnya.\r\n\r\nHaura melakukan segala cara demi menjadikan Halal pasangan hidupnya, Hubungan Haura dengan saudara dan sahabat-sahabatnya mulai renggang karena sikap egois Haura yang semakin tak terkendali kala mengejar Halal. Mampukah Haura mendapatkan Halal dan meraih pernikahan sempurna impiannya?', 'Drama, Comedy', 2010, '2010-11-01', 75, 'M. Amrul Ummami', 'M. Ali Ghifari', 'Inez Ayuningtyas, Abdul Kaafi, Ressa Rere, Ryan Qori, Ahmad Rhezanov', 'http://www.21cineplex.com/data/gallery/pictures/148956160311346_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/skSeKOOvMgg" frameborder="0" allowfullscreen></iframe>', 'tt5351016', 0, 0, 0, 0, 0, 0),
(56, 'NIGHT BUS', 'Bis Babad mengangkut beberapa penumpang menuju Sampar, sebuah kota yang terkenal kaya akan sumber daya alamnya namun terjadi konflik berkepanjangan. Sampar dijaga ketat oleh aparat pemerintah pusat yang siap siaga melawan pasukan Samerka (Sampar Merdeka), para milisi pemberontak yang menuntut kemerdekaan atas tanah kelahiran mereka.\r\n\r\nSetiap penumpang bis memiliki tujuannya masing- masing : mencari penghidupan yang lebih baik, memenuhi kebutuhan keluarga, menyelesaikan masalah pribadi atau sesederhana ingin pulang ke kampung halaman.\r\n\r\nMereka berpikir bahwa ini akan menjadi perjalanan seperti biasa, tanpa mereka sadari ada penyusup masuk ke dalam bis, membawa pesan penting yang harus di sampaikan ke Sampar. \r\n\r\nKehadiran penyusup membahayakan semua penumpang, orang paling dicari oleh kedua pihak yang bertikai, perintahnya temukan hidup atau mati!!\r\n\r\nSituasi menjadi semakin menegangkan ketika seluruh penumpang harus memperjuangkan hidupnya di antara desingan peluru. \r\n\r\nMereka bahkan harus menghadapi pihak lain yang justru tidak menginginkan konflik berakhir. Kaum oportunis, pemelihara konflik karena mereka hidup dari konflik, kesadisan dan kebengisan mereka semakin memberikan teror pada para penumpang bus.\r\n\r\nTidak ada yang tahu, siapa akan hidup dan siapa akan mati?!', 'Drama, Thriller, Action', 2007, '2007-05-11', 135, 'Emil Heradi', 'Rahabi Mandra', 'Yayu Unru, Teuku Rifnu Wikana, Hana Prinantina', 'http://www.21cineplex.com/data/gallery/pictures/148947703512087_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/VO9hVH6k3F0" frameborder="0" allowfullscreen></iframe>', 'tt0865924', 6.8, 0, 0, 0, 0, 1),
(57, 'BEST FRIEND FOREVER', 'Berkisah tentang ke empat remeja perempuan, Bianca(19th), Laura(18th), Sascha(19th) dan Tammy(18th) berencana menghabiskan jumat malam bersama. Kali ini Bianca merencanakan dengan sangat tertata, tidak seperti malam-malam sebelumnya. Namun, kenyataan tak seperti apa yang mereka berempat bayangkan. Rencana yang Bianca buat berubah 180 derajat, dan menjadi malapetaka.\r\n\r\nBianca, Laura, Sascha dan Tammy menjalani malam yang penuh dengan malapetaka yang datang hilir berganti menghampiri mereka berempat.\r\n\r\nPerjuangan Bianca, Laura, Sascha dan Tammy keluar dari situasi buruk, berujung Bianca harus kehilangan jejak pria idamannya. Yang membuat Bianca marah besar, sehingga memicu perkelahian diantara mereka berempat.\r\n\r\nDi malam yang sama Keempat sahabat ini menghadapi aksi-aksi berbahaya yang hampir merenggut nyawa dan membuat persahabatan mereka hancur.\r\n\r\nTingkah polos Bianca, Sascha, Tammy dan Laura dalam mengahadapi masalah membuat kekonyolan yang sangat lucu dan mampu memberikan arti tersendiri diantara mereka.\r\n\r\nNamun apakah Bianca, Sascha, Tammy dan Laura akan keluar dari mala petaka yang mengejar mereka pada malam itu ? Apa mungkin persahabatan mereka kembali baik seperti semula. Mampukah Bianca bertemu pria idamannya, serta siapakah pria idaman Bianca ? Saksikan kisah mereka dalam film Best Friends Forever, yang akan tayang di bioskop 6 April 2017.', 'Short, Comedy', 2012, '2012-07-19', 0, 'Estelle Linden', 'M. Rizkhi Faiz', 'Wendy Wilson, Kezia Karamoy, Yova Gracia, Ineke Valentina', 'http://www.21cineplex.com/data/gallery/pictures/148947679482206_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/WFox4ttcPM8" frameborder="0" allowfullscreen></iframe>', 'tt2558934', 0, 0, 0, 0, 0, 1),
(65, 'PHILLAURI', 'Seorang pemuda asal Mangalik, Kanan (Suraj Sharma) menikahi sebuah pohon sebagai ritual tolak bala agar dapat menikahi wanita pilihannya. \r\n\r\nNamun tanpa di sangka-sangka pohon yang ia nikahi tersebut berisi roh halus yang kemudian terus mengikuti langkah Kanan.', 'Comedy, Drama, Fantasy', 2017, '2017-03-24', 134, 'Anshai Lal', 'Anvita Dutt', 'Anushka Sharma, Diljit Dosanjh, Suraj Sharma, Mehreen Pirzada', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5Mjc3MTYyMl5BMl5BanBnXkFtZTgwMTgzNDkzMTI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/uCTr7MGFK0U" frameborder="0" allowfullscreen></iframe>', 'tt5502766', 7.5, 0, 0, 0, 0, 2),
(68, 'SMURFS THE LOST VILLAGE', 'Ketika Smurfette (Demi Lovato) menemukan sebuah peta misterius, ia bersama para sahabatnya Brainy, Clumsy dan Hefty pergi dalam sebuah petualangan menuju sebuah hutan terlarang yang dihuni oleh hewan ajaib untuk mecari sebuah desa misterius sebelum penyihir jahat Gargamel menemukannya. Dengan melalui perjalan yang dipenuhi rintangan dan bahaya, para Smurf akan menemukan sebuah rahasia terbesar dalam sejarah kaum Smurf.', 'Animation, Adventure, Comedy', 2017, '2017-04-07', 89, 'Kelly Asbury', 'Stacey Harman, Pamela Ribon, Peyo (based on the characters and works of)', 'Ariel Winter, Julia Roberts, Ellie Kemper, Joe Manganiello', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTg1NjgyMTYzM15BMl5BanBnXkFtZTgwMzIxNDc4MDI@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/8LdpyRBE0aA" frameborder="0" allowfullscreen></iframe>', 'tt2398241', 0, 0, 0, 0, 0, 1),
(69, 'SPIRITED AWAY', 'Film animasi karya sutradara ternama Jepang Hayao Miyazaki ini bercerita tentang kisah seorang gadis berumur 10 tahun bernama Chihiro dan kedua orangtuanya yang masuk ke sebuah tempat yang terlihat sebagai sebuah taman hiburan yang terabaikan. \r\n\r\nSetelah kedua orangtuanya berubah menjadi babi raksasa, Chihiro bertemu dengan sosok misterius Haku yang menjelaskan kepadanya bahwa tempat mereka berada adalah sebuah resort di mana makhluk supernatural berisitrahat dari alam duniawi. Untuk dapat membebaskan kedua orangtuanya, Chihiro harus bekerja di sebuah bath house yang dikepalai oleh penyihir bernama Yubaba.', 'Animasi, Drama', 2001, '2003-03-28', 122, 'Hayao Miyazaki', 'Hayao Miyazaki', 'Rumi Hiiragi, Miyu Irino, Mari Natsuki, Takashi Naitô', 'https://images-na.ssl-images-amazon.com/images/M/MV5BMTk3NTM1NTg1Ml5BMl5BanBnXkFtZTgwOTgzMTMyMDE@._V1_SX300.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/ByXuk9QqQkk" frameborder="0" allowfullscreen></iframe>', 'tt0245429', 8.6, 94, 0, 0, 0, 2),
(70, 'CRITICAL ELEVEN', 'Melalui Critical Eleven, pemenang Piala Citra Reza Rahadian dan Adinia Wirasti menghidupkan Ale dan Anya dari novel national bestseller karya Ika Natassa, pasangan muda yang bertemu dan saling terpikat dalam penerbangan Jakarta-Sydney. Pertemuan itu membawa mereka ke jenjang pernikahan, dan membuat keduanya mengambil keputusan besar sebagai pasangan karena pengorbanan yang harus dilakukan salah satu dari mereka: pindah ke New York.\r\n\r\nKota yang tidak pernah tidur ini ternyata membawa berkah bagi keduanya: kehamilan Anya yang mengubah hidup mereka. Sampai Ale dan Anya diterjang sebuah insiden yang membuat mereka tidak hanya mempertanyakan cinta, namun juga bergumul dengan ego dan harus memilih: menyerah dalam amarah atau menyembuhkan luka dan bertahan dalam ketidakpastian. Pilihan sulit itu bertambah pelik dengan kehadiran seseorang yang sudah lama mencintai Anya.', 'Drama', 2017, '2017-01-15', 120, 'Monty Tiwa', 'Jenny Jusuf, Ika Natassa', ' Reza Rahadian, Mark C. Fullhardt, Hannah Al Rashid', 'http://www.21cineplex.com/data/gallery/pictures/149155653948865_300x430.jpg', '<iframe width="854" height="480" src="https://www.youtube.com/embed/tn-IiueNqsY" frameborder="0" allowfullscreen></iframe>', 'tt6426714', 0, 0, 0, 0, 0, 0),
(71, 'GUARDIANS OF THE GALAXY VOL. 2', 'Pada seri kedua film Guardian of the Galaxy, Peter Quills (Chris Pratt) dan para Guardians kembali melanjutkan petualangan mereka dengan menjelajahi bagian terluar dari kosmos. Kali ini, persahabatan para Guardians akan diuji pada saat mereka mengungkap misteri dari', NULL, NULL, NULL, NULL, NULL, NULL, NULL, '149086206646137', NULL, NULL, NULL, NULL, 0, 0, 0, 3),
(72, 'MIDDLE SCHOOL: THE WORST YEARS OF MY LIFE', 'Rafe Khatchadorian (Griffin Gluck) adalah remaja yang memiliki imajinasi tinggi. Namun ia punya banyak masalah, mulai dengan pacar sang Ibu sampai lingkungan baru di sekolah.   Masalah terbesar Rafe adalah sang kepala sekolah Dwight (Andrew Daly) yang', 'Comedy, Family', 2016, '2016-10-07', 92, 'Steve Carr', 'Chris Bowman (screenplay), Hubbel Palmer (screenplay), Kara Holden (screenplay), James Patterson (based on the book by), Chris Tebbetts (based on the book by)', 'Griffin Gluck, Lauren Graham, Alexa Nisenson, Andrew Daly', 'https://images-na.ssl-images-amazon.com/images/M/MV5BNjQzMTczNjI0Ml5BMl5BanBnXkFtZTgwODY5MTY5OTE@._V1_SX300.jpg', NULL, 'tt4981636', 6.1, 51, 0, 0, 0, 3);

-- --------------------------------------------------------

--
-- Table structure for table `review`
--

CREATE TABLE `review` (
  `id` int(11) NOT NULL,
  `film_id` int(11) NOT NULL,
  `email` varchar(256) NOT NULL,
  `rating` tinyint(2) NOT NULL,
  `review` text NOT NULL,
  `tanggal` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `review`
--

INSERT INTO `review` (`id`, `film_id`, `email`, `rating`, `review`, `tanggal`) VALUES
(4, 26, 'meloniaseven@gmail.com', 7, 'Great. Love this one. Super funny. So many lovable characters (I love the batman!!)', '2017-03-08 21:56:21'),
(5, 33, 'meloniaseven@gmail.com', 6, 'Meh, not that great.\r\nSangat mengecewakan ya buat yg udah nonton semua seri xmen. Ini film yg memang buat jadi akhirnya dr xmen, tapi ya ampun, mengecewakan deh pokoknya. Ceritanya ga jelas, karakteristiknya Wolverine The Legend yg dr awal cerita itu immortal + ageless, sekarang tiba-tiba jadi tua dan sakit"an. Darimana bisa kayak gitu? Ga dijelasin. Sama kayak film xmen sebelumnya (Future Past), ga jelas darimana awalnya. Top deh.', '2017-03-08 21:56:21'),
(6, 35, 'meloniaseven@gmail.com', 6, 'Film apa ini, ga jelas banget', '2017-03-08 21:58:49'),
(8, 29, 'scooby@gmail.com', 9, 'Top deh. Suka banget gw sama film ini.', '2017-03-08 21:59:50'),
(9, 33, 'scooby@gmail.com', 9, 'action-nya keren banget brooohhh!! love laura!!', '2017-03-08 21:59:50'),
(12, 35, 'scooby@gmail.com', 7, 'yahh oke lahh', '2017-03-09 17:36:27'),
(14, 29, 'meloniaseven@gmail.com', 9, 'dayumm sooo coooolllll', '2017-03-13 21:08:06');

-- --------------------------------------------------------

--
-- Table structure for table `tweets`
--

CREATE TABLE `tweets` (
  `id` int(11) NOT NULL,
  `film_id` int(11) NOT NULL,
  `tweet` varchar(256) NOT NULL,
  `status` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `email` varchar(256) NOT NULL COMMENT 'cannot be changed',
  `password` varchar(256) NOT NULL,
  `name` varchar(256) NOT NULL,
  `birthdate` date DEFAULT NULL,
  `picture` varchar(256) DEFAULT './pictures/default.png',
  `role` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1 for user, 0 for admin'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`email`, `password`, `name`, `birthdate`, `picture`, `role`) VALUES
('admin@abcmovies.co.id', '21232f297a57a5a743894a0e4a801fc3', 'Admin of ABCMovies', '1995-12-25', './pictures/1488602184adm.png', 0),
('meloniaseven@gmail.com', '3e4063d6f38d738b1e6608a2c1f119d8', 'Melania Laniwati', '1995-02-07', './pictures/1488602110mel.jpg', 1),
('scooby@gmail.com', '38371fef7d829c7f8b0e2fedf7a04334', 'Scooby Doo', '1992-01-03', './pictures/1488602156sco.jpg', 1);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `banner`
--
ALTER TABLE `banner`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `film`
--
ALTER TABLE `film`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `review`
--
ALTER TABLE `review`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tweets`
--
ALTER TABLE `tweets`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `banner`
--
ALTER TABLE `banner`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;
--
-- AUTO_INCREMENT for table `film`
--
ALTER TABLE `film`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=81;
--
-- AUTO_INCREMENT for table `review`
--
ALTER TABLE `review`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;
--
-- AUTO_INCREMENT for table `tweets`
--
ALTER TABLE `tweets`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
